export const chapter007 = {
  id: 7,
  title: '남겨진 온기',
  scenes: [
    { id: 'c7-title', mode: 'black', center: 'CHAPTER 7\n\n남겨진 온기' },
    { id: 'c7-morning', mode: 'city', narration: true, text: '다음 날 아침. 하루는 임무를 나갔고, 모모도 길드의 심부름으로 자리를 비운 상태였다.' },
    { id: 'c7-alone', mode: 'city', speaker: '주인공', text: '어제 만든 검의 감각이 아직 남아 있다. 조금만 더 연습해 보자.' },
    { id: 'c7-training-ground', mode: 'battle', narration: true, text: '이른 시간의 훈련소는 한산했다. 멀리서 몇몇 헌터가 몸을 푸는 소리만 들렸다.' },
    { id: 'c7-first-manifest', mode: 'battle', narration: true, text: '손을 펼치자 푸른 입자가 모였다. 어제보다 빠르게 짧은 검의 형태가 잡혔다.' },
    { id: 'c7-first-swing', mode: 'battle', narration: true, text: '검을 천천히 휘둘러 보았다. 손에 전해지는 무게도, 움직일 때 흐트러지는 감각도 전보다 선명했다.' },
    { id: 'c7-choice-training', mode: 'battle', speaker: '주인공', text: '조금 더 해도 괜찮을 것 같다.', choices: [
      { id: 'c7-train-steady', label: '호흡을 고르며 천천히 반복한다.', reply: '서두르지 말자. 오래 유지하는 것부터 익히면 된다.', traits: { cautious: 2 } },
      { id: 'c7-train-push', label: '한 번만 더 강하게 휘둘러 본다.', reply: '이번에는 끝까지 형태를 붙잡아 보자.', traits: { brave: 2 }, flags: ['pushed_training_limit'] },
      { id: 'c7-train-recall', label: '하루가 알려준 방법을 떠올린다.', reply: '억지로 힘을 주지 말고, 자연스럽게 형태를 떠올리자.', trust: { haru: 1 }, traits: { calm: 1 } }
    ] },
    { id: 'c7-repeat', mode: 'battle', narration: true, text: '검을 거두고 다시 만들었다. 몇 번을 반복하자 손끝의 빛이 조금씩 흐려졌다.' },
    { id: 'c7-warning', mode: 'battle', speaker: '주인공', text: '조금 어지럽네. 여기까지만 할까.' },
    { id: 'c7-last-attempt', mode: 'battle', narration: true, text: '그렇게 생각하면서도 마지막으로 한 번 더 검을 만들었다.' },
    { id: 'c7-drain', mode: 'battle', narration: true, text: '형태가 잡히기도 전에 시야가 흔들렸다. 검은 손안에서 빛으로 흩어졌고, 다리에 힘이 풀렸다.' },
    { id: 'c7-collapse', mode: 'black', narration: true, text: '바닥에 손을 짚으려 했지만 늦었다. 그대로 의식이 끊어졌다.' },
    { id: 'c7-warmth', mode: 'black', narration: true, text: '얼마나 지났는지 알 수 없었다. 차갑게 식은 몸 안으로 따뜻한 감각이 천천히 퍼졌다.' },
    { id: 'c7-presence', mode: 'black', narration: true, text: '누군가 가까이 있는 것 같았다. 희미한 목소리도 들린 듯했지만 말을 알아들을 수는 없었다.' },
    { id: 'c7-wake', mode: 'battle', narration: true, text: '눈을 떴을 때는 훈련장 한쪽에 혼자 누워 있었다. 어지러움은 가라앉았고, 숨도 편해져 있었다.' },
    { id: 'c7-wake-thought', mode: 'battle', speaker: '주인공', text: '누가 도와준 건가…….' },
    { id: 'c7-vice-arrive', mode: 'battle', narration: true, text: '몸을 일으키고 있을 때 정장을 단정하게 차려입은 남자가 훈련장 안으로 들어왔다.' },
    { id: 'c7-vice-find', mode: 'battle', speaker: '부길드장', text: '여기 계셨군요. 몸은 괜찮으십니까?' },
    { id: 'c7-mc-answer', mode: 'battle', speaker: '주인공', text: '네. 잠깐 무리했던 것 같습니다.' },
    { id: 'c7-vice-call', mode: 'battle', speaker: '부길드장', text: '다행이군요. 길드장님께서 찾고 계십니다. 걸을 수 있으시면 함께 가시죠.' },
    { id: 'c7-walk-guild', mode: 'city', narration: true, text: '부길드장과 함께 길드로 돌아가는 동안 그는 더 묻지 않았다. 주인공도 방금 전의 온기에 관해서는 입을 열지 않았다.' },
    { id: 'c7-return-room', mode: 'city', narration: true, text: '길드장실에 들어서자 길드장은 책상 위의 서류를 한쪽으로 밀어 두었다.' },
    { id: 'c7-guildmaster-greeting', mode: 'city', speaker: '길드장', text: '왔어? 훈련하다 쓰러졌다는 얘기는 들었어. 지금은 괜찮고?' },
    { id: 'c7-choice-answer', mode: 'city', speaker: '주인공', text: '길드장은 가볍게 말했지만 내 얼굴을 살피고 있었다.', choices: [
      { id: 'c7-answer-apology', label: '무리했다고 인정한다.', reply: '네. 제 한계를 제대로 판단하지 못했습니다.', trust: { guildmaster: 1 }, traits: { cautious: 1 } },
      { id: 'c7-answer-fine', label: '지금은 괜찮다고 답한다.', reply: '지금은 괜찮습니다. 다음부터는 조심하겠습니다.', traits: { calm: 1 } },
      { id: 'c7-answer-work', label: '부른 이유를 묻는다.', reply: '몸은 괜찮습니다. 저를 부르신 이유가 따로 있습니까?', traits: { brave: 1 } }
    ] },
    { id: 'c7-guildmaster-relax', mode: 'city', speaker: '길드장', text: '그렇게 긴장할 필요 없어. 혼내려고 부른 건 아니니까.' },
    { id: 'c7-guildmaster-question', mode: 'city', speaker: '길드장', text: '여기 생활은 좀 익숙해졌어?' },
    { id: 'c7-mc-life', mode: 'city', speaker: '주인공', text: '아직 모르는 게 많지만, 주변에서 많이 도와주고 있습니다.' },
    { id: 'c7-guildmaster-response', mode: 'city', speaker: '길드장', text: '그럼 다행이네. 계속 잡일만 맡길 수도 없고, 슬슬 정식 의뢰를 경험해 볼 때가 됐어.' },
    { id: 'c7-guildmaster-mission', mode: 'city', speaker: '길드장', text: '내일 인접 도시에서 오는 물자를 중간 지점에서 받아 오는 일이 있어. 동행할 헌터도 한 명 붙을 거야.' },
    { id: 'c7-mc-first-mission', mode: 'city', speaker: '주인공', text: '제가 맡아도 괜찮겠습니까?' },
    { id: 'c7-guildmaster-assure', mode: 'city', speaker: '길드장', text: '처음부터 혼자 보내진 않아. 동행하는 사람 말 잘 듣고, 이상하다 싶으면 바로 돌아와. 그 정도면 돼.' },
    { id: 'c7-mission-card', mode: 'status', center: '정식 의뢰\n\n인접 도시 물자 인계 지원\n\n내일 아침 도시 외곽에서 동행 헌터와 합류\n중간 지점에서 물자를 인계받은 뒤\n길드까지 무사히 복귀할 것' },
    { id: 'c7-vice-last-word', mode: 'city', speaker: '부길드장', text: '출발 시간과 집결 장소는 의뢰서에 적혀 있습니다. 오늘은 충분히 쉬어 두십시오.' },
    { id: 'c7-final', mode: 'black', speaker: '주인공', text: '첫 정식 의뢰다. 긴장됐지만, 훈련장에서 느꼈던 따뜻한 감각이 이상하게 마음에 남아 있었다.' },
    { id: 'c7-clear', mode: 'black', center: 'CHAPTER 7 CLEAR' },
    { id: 'c7-end', mode: 'black', ending: true, center: '첫 정식 의뢰를 부여받았다.' }
  ]
};