export const chapter008 = {
  id: 8,
  title: '처음 만난 힐러',
  scenes: [
    { id: 'c8-title', mode: 'black', center: 'CHAPTER 8\n\n처음 만난 힐러' },
    { id: 'c8-next-morning', mode: 'city', narration: true, text: '다음 날 아침, 주인공은 약속한 시간보다 조금 일찍 도시 외곽의 집결 장소에 도착했다.' },
    { id: 'c8-wait', mode: 'city', narration: true, text: '성문을 드나드는 사람들 사이로 의뢰서를 몇 번이나 다시 확인했다. 아직 아무도 자신을 찾지 않는 것 같았다.' },
    { id: 'c8-mc-nervous', mode: 'city', speaker: '주인공', text: '장소는 여기 맞는데…….' },
    { id: 'c8-sena-call', mode: 'city', speaker: '세나', text: '혹시 오늘 물자 인계 의뢰로 오셨어요?' },
    { id: 'c8-sena-wait', mode: 'city', narration: true, text: '뒤를 돌아보자 한 여성이 손을 가볍게 들어 보였다. 눈에 띄는 무기는 없었고 작은 가방 하나만 메고 있었다.' },
    { id: 'c8-mc-confirm', mode: 'city', speaker: '주인공', text: '네, 맞습니다.' },
    { id: 'c8-sena-intro', mode: 'city', speaker: '세나', text: '잘됐네요. 저는 세나예요. 오늘은 회복과 지원을 맡을 거예요.' },
    { id: 'c8-mc-intro', mode: 'city', speaker: '주인공', text: '저는 {{playerName}}입니다. 잘 부탁드립니다.' },
    { id: 'c8-sena-smile', mode: 'city', speaker: '세나', text: '네, 저도 잘 부탁드려요.' },
    { id: 'c8-small-pause', mode: 'city', narration: true, text: '짧은 인사가 끝나자 다시 조용해졌다. 주인공이 무슨 말을 해야 할지 고민하는 사이 세나가 먼저 의뢰서를 펼쳤다.' },
    { id: 'c8-sena-mission-check', mode: 'city', speaker: '세나', text: '중간 지점까지 가서 물자를 받고 돌아오면 돼요. 길 자체는 어렵지 않아요.' },
    { id: 'c8-mc-question', mode: 'city', speaker: '주인공', text: '세나 씨는 이 길을 자주 다니셨습니까?' },
    { id: 'c8-sena-answer-route', mode: 'city', speaker: '세나', text: '몇 번 다녀왔어요. 갈림길도 거의 없어서 길을 잃을 일은 없을 거예요.' },
    { id: 'c8-sena-notice', mode: 'city', narration: true, text: '세나는 의뢰서를 접다가 주인공의 굳은 표정을 보고 잠깐 멈췄다.' },
    { id: 'c8-sena-calm', mode: 'city', speaker: '세나', text: '첫 정식 의뢰라서 긴장되죠?' },
    { id: 'c8-choice-nervous', mode: 'city', speaker: '주인공', text: '들킨 것 같아 조금 머쓱해졌다.', choices: [
      { id: 'c8-nervous-honest', label: '솔직하게 인정한다.', reply: '네. 실수하지 않을까 조금 걱정됩니다.', trust: { sena: 1 }, traits: { cautious: 1 } },
      { id: 'c8-nervous-hide', label: '괜찮다고 답한다.', reply: '괜찮습니다. 준비는 하고 왔습니다.', traits: { calm: 1 } },
      { id: 'c8-nervous-ask', label: '조심할 점을 묻는다.', reply: '처음이라서요. 제가 특히 조심해야 할 게 있습니까?', trust: { sena: 2 }, traits: { cautious: 1 } }
    ] },
    { id: 'c8-sena-reassure', mode: 'city', speaker: '세나', text: '실수해도 괜찮아요. 혼자 하는 임무도 아니고, 모르는 건 그때그때 물어보면 돼요.' },
    { id: 'c8-sena-light-joke', mode: 'city', speaker: '세나', text: '제가 먼저 길을 잘못 들지만 않으면 별일 없을 거예요.' },
    { id: 'c8-mc-relax', mode: 'city', narration: true, text: '장난인지 진담인지 알기 어려운 말에 긴장이 조금 풀렸다.' },
    { id: 'c8-two-party', mode: 'status', center: '파티 편성\n\n주인공  전투\n세나  회복·지원\n\n파티 인원  2명' },
    { id: 'c8-depart', mode: 'city', narration: true, text: '두 사람은 성문을 지나 중간 지점으로 향했다.' },
    { id: 'c8-road-start', mode: 'forest-exit', narration: true, text: '도시에서 멀어질수록 길은 한산해졌다. 한동안은 흙길을 밟는 소리만 이어졌다.' },
    { id: 'c8-sena-conversation', mode: 'forest-exit', speaker: '세나', text: '어제 무기를 처음 구현했다고 들었어요.' },
    { id: 'c8-mc-surprised', mode: 'forest-exit', speaker: '주인공', text: '그 이야기도 들으셨습니까?' },
    { id: 'c8-sena-guild-talk', mode: 'forest-exit', speaker: '세나', text: '길드 안에서는 소식이 빨라요. 무리해서 쓰러졌다는 얘기까지 같이 들었고요.' },
    { id: 'c8-mc-awkward', mode: 'forest-exit', speaker: '주인공', text: '그건…… 조금 창피하네요.' },
    { id: 'c8-sena-kind', mode: 'forest-exit', speaker: '세나', text: '처음엔 힘 조절이 어렵죠. 오늘은 무리하지 마세요. 물자를 받으러 가는 임무지, 실력을 증명하러 가는 임무는 아니니까요.' },
    { id: 'c8-choice-talk', mode: 'forest-exit', speaker: '주인공', text: '세나의 말투는 차분했고 재촉하는 느낌이 없었다.', choices: [
      { id: 'c8-talk-thanks', label: '신경 써줘서 고맙다고 말한다.', reply: '알겠습니다. 신경 써주셔서 감사합니다.', affection: { sena: 1 }, trust: { sena: 1 } },
      { id: 'c8-talk-role', label: '회복 능력에 관해 묻는다.', reply: '회복은 다친 뒤에 바로 사용할 수 있는 겁니까?', trust: { sena: 2 }, traits: { cautious: 1 } },
      { id: 'c8-talk-mission', label: '임무에 집중하겠다고 말한다.', reply: '네. 오늘은 지시를 잘 따르겠습니다.', trust: { sena: 1 }, traits: { calm: 1 } }
    ] },
    { id: 'c8-sena-heal-answer', mode: 'forest-exit', speaker: '세나', text: '가벼운 상처라면 바로 괜찮아져요. 그래도 일부러 다칠 필요는 없어요. 피할 수 있으면 피하는 게 제일 좋죠.' },
    { id: 'c8-mc-heal-thought', mode: 'forest-exit', narration: true, text: '회복이라는 말을 듣자 어제 훈련장에서 느꼈던 따뜻한 감각이 잠깐 떠올랐다.' },
    { id: 'c8-mc-almost-ask', mode: 'forest-exit', speaker: '주인공', text: '혹시 어제 훈련소에…….' },
    { id: 'c8-sena-look', mode: 'forest-exit', speaker: '세나', text: '네?' },
    { id: 'c8-mc-stop-question', mode: 'forest-exit', speaker: '주인공', text: '아닙니다. 나중에 여쭤보겠습니다.' },
    { id: 'c8-sena-accept', mode: 'forest-exit', speaker: '세나', text: '그래요. 생각나면 편하게 물어보세요.' },
    { id: 'c8-break', mode: 'forest-exit', narration: true, text: '조금 더 걷다가 세나가 길가의 평평한 바위를 가리켰다.' },
    { id: 'c8-sena-rest', mode: 'forest-exit', speaker: '세나', text: '잠깐 물 마시고 갈까요? 시간은 충분해요.' },
    { id: 'c8-mc-rest-answer', mode: 'forest-exit', speaker: '주인공', text: '네. 그러죠.' },
    { id: 'c8-rest-scene', mode: 'forest-exit', narration: true, text: '짧게 쉬는 동안 세나는 오늘 받을 물자의 수량과 돌아갈 길을 다시 확인했다. 주인공에게도 의뢰서를 건네며 같이 살펴보게 했다.' },
    { id: 'c8-sena-practical', mode: 'forest-exit', speaker: '세나', text: '임무 중에 애매한 게 생기면 혼자 판단하지 말고 먼저 말해주세요. 둘이 같이 확인하는 게 더 안전해요.' },
    { id: 'c8-mc-agree', mode: 'forest-exit', speaker: '주인공', text: '알겠습니다.' },
    { id: 'c8-road-resume', mode: 'forest-exit', narration: true, text: '다시 길을 나섰을 때는 처음보다 발걸음이 한결 가벼워져 있었다.' },
    { id: 'c8-near-point', mode: 'danger', narration: true, text: '중간 지점이 가까워질 무렵, 앞서 걷던 세나가 갑자기 멈췄다.' },
    { id: 'c8-mc-why-stop', mode: 'danger', speaker: '주인공', text: '왜 그러세요?' },
    { id: 'c8-sena-quiet', mode: 'danger', speaker: '세나', text: '잠깐만요. 조용히 해봐요.' },
    { id: 'c8-silence', mode: 'danger', narration: true, text: '조금 전까지 들리던 새소리가 끊겨 있었다. 바람도 멎은 듯 주변의 풀이 움직이지 않았다.' },
    { id: 'c8-rustle', mode: 'danger', narration: true, text: '잠시 뒤, 길 오른쪽 수풀 깊은 곳에서 무언가가 바닥을 긁는 소리가 났다.' },
    { id: 'c8-sena-position', mode: 'danger', speaker: '세나', text: '제 옆으로 와요. 아직 보이지 않으니까 먼저 움직이지 말고요.' },
    { id: 'c8-mc-ready', mode: 'danger', narration: true, text: '주인공은 손안에 짧은 검을 구현하고 세나의 옆에 섰다.' },
    { id: 'c8-first-shadow', mode: 'danger', narration: true, text: '수풀 사이로 검은 형체 하나가 모습을 드러냈다. 그 뒤에서도 낮은 울음소리가 연달아 들렸다.' },
    { id: 'c8-sena-count', mode: 'danger', speaker: '세나', text: '하나가 아니네요.' },
    { id: 'c8-nightmares', mode: 'battle', center: '악몽 무리 출현' },
    { id: 'c8-sena-ready', mode: 'battle', speaker: '세나', text: '멀리 떨어지지만 마세요. 제가 보이는 곳에서 움직여요.' },
    { id: 'c8-first-clash', mode: 'battle', narration: true, text: '악몽들이 동시에 달려들었다. 주인공은 가장 가까운 개체의 공격을 짧은 검으로 받아내고 옆으로 흘렸다.' },
    { id: 'c8-mc-fight', mode: 'battle', narration: true, text: '훈련용 표적과는 달랐지만 몸은 예상보다 빠르게 반응했다. 검도 첫 충돌만으로 무너지지는 않았다.' },
    { id: 'c8-sena-style', mode: 'battle', narration: true, text: '세나는 공격을 크게 피하지 않고 필요한 만큼만 몸을 틀었다. 팔을 스친 상처는 곧바로 따뜻한 빛에 감싸여 사라졌다.' },
    { id: 'c8-healing-sense', mode: 'battle', narration: true, text: '그 빛을 보는 순간, 주인공은 훈련장에서 의식을 잃었을 때 느꼈던 온기를 떠올렸다.' },
    { id: 'c8-memory-link', mode: 'battle', speaker: '주인공', text: '이 느낌…….' },
    { id: 'c8-sena-focus', mode: 'battle', speaker: '세나', text: '오른쪽 봐요!' },
    { id: 'c8-choice-battle', mode: 'battle', speaker: '주인공', text: '생각을 멈추고 다시 검을 들었다.', choices: [
      { id: 'c8-battle-guard', label: '세나의 앞을 지킨다.', reply: '제가 앞을 막겠습니다. 뒤를 부탁드립니다.', trust: { sena: 2 }, traits: { considerate: 1 } },
      { id: 'c8-battle-together', label: '서로의 위치를 확인하며 싸운다.', reply: '서로 보이는 거리에서 움직이겠습니다.', trust: { sena: 2 }, traits: { cautious: 1 } },
      { id: 'c8-battle-charge', label: '가까운 악몽부터 빠르게 밀어낸다.', reply: '수가 더 늘기 전에 앞쪽부터 줄이겠습니다.', traits: { brave: 2 } }
    ] },
    { id: 'c8-battle-turn', mode: 'battle', narration: true, text: '두 사람은 서로의 위치를 확인하며 악몽들을 하나씩 밀어냈다. 주인공의 움직임은 거칠었지만 세나가 빈틈을 바로 메워 주었다.' },
    { id: 'c8-last-nightmare', mode: 'battle', narration: true, text: '마지막 남은 악몽이 갑자기 방향을 틀어 세나에게 달려들었다.' },
    { id: 'c8-sena-judgment', mode: 'battle', narration: true, text: '세나는 발톱의 방향을 보고 몸을 틀었다. 가벼운 상처만 감수하고 바로 반격하려는 움직임이었다.' },
    { id: 'c8-mc-misread', mode: 'battle', narration: true, text: '하지만 주인공의 눈에는 세나가 미처 피하지 못한 것처럼 보였다.' },
    { id: 'c8-danger', mode: 'black', speaker: '주인공', text: '위험해.' },
    { id: 'c8-shield', mode: 'battle', narration: true, text: '생각하기도 전에 몸이 먼저 움직였다. 주인공은 세나를 밀어내며 악몽 앞을 막았다.' },
    { id: 'c8-injury', mode: 'black', center: '푹—' },
    { id: 'c8-wound', mode: 'battle', narration: true, text: '발톱이 옆구리를 깊게 파고들었다. 뜨거운 통증과 함께 다리에 힘이 빠졌다.' },
    { id: 'c8-sena-shock', mode: 'battle', speaker: '세나', text: '왜 막았어요? 저는 피할 수 있었는데!' },
    { id: 'c8-mc-fall', mode: 'battle', speaker: '주인공', text: '위험해 보였습니다…….' },
    { id: 'c8-heal-fail-start', mode: 'battle', narration: true, text: '세나가 곧바로 상처에 손을 얹었다. 익숙한 따뜻한 빛이 번졌지만 찢어진 상처는 닫히지 않았다.' },
    { id: 'c8-sena-confused', mode: 'battle', speaker: '세나', text: '잠깐만요. 왜 안 낫는 거죠?' },
    { id: 'c8-final', mode: 'black', narration: true, text: '의식이 흐려지는 가운데 다시 따뜻한 감각이 느껴졌다. 이번에는 그 온기의 주인이 누구인지 알 수 있었다.' },
    { id: 'c8-clear', mode: 'black', center: 'CHAPTER 8 CLEAR' },
    { id: 'c8-end', mode: 'black', ending: true, center: '첫 정식 의뢰 도중 주인공이 부상을 입었다.' }
  ]
};