export const chapter009 = {
  id: 9,
  title: '동굴의 밤',
  scenes: [
    { id: 'c9-title', mode: 'black', center: 'CHAPTER 9\n\n동굴의 밤' },
    { id: 'c9-return-battle', mode: 'battle', narration: true, text: '주인공이 쓰러지자 세나는 곧바로 그의 앞을 막아섰다. 남아 있던 악몽들이 다시 거리를 좁혀 왔다.' },
    { id: 'c9-sena-call', mode: 'battle', speaker: '세나', text: '{{playerName}} 씨, 정신 차려요. 지금 여기서 멈추면 안 돼요.' },
    { id: 'c9-mc-faint', mode: 'battle', narration: true, text: '대답하려 했지만 목소리가 나오지 않았다. 옆구리에서 번지는 통증 때문에 숨을 들이쉬는 것조차 힘들었다.' },
    { id: 'c9-smoke-start', mode: 'battle', narration: true, text: '세나는 한 손으로 주인공을 붙잡고 다른 손을 바닥에 뻗었다. 희뿌연 연무가 순식간에 주변을 뒤덮었다.' },
    { id: 'c9-sena-command', mode: 'battle', speaker: '세나', text: '눈 감고 제 어깨 잡아요. 제가 데리고 갈게요.' },
    { id: 'c9-escape', mode: 'danger', narration: true, text: '악몽들의 울음소리가 연무 속에서 뒤엉켰다. 세나는 주인공의 팔을 자신의 어깨에 걸치고 숲 안쪽으로 이동했다.' },
    { id: 'c9-weight', mode: 'danger', narration: true, text: '주인공의 체중이 실릴 때마다 세나의 걸음이 흔들렸다. 그래도 멈추지 않고 나무와 바위 사이를 골라 악몽들의 감각을 흩뜨렸다.' },
    { id: 'c9-cave-find', mode: 'cave', narration: true, text: '얼마나 이동했는지 알 수 없을 무렵, 바위 틈 뒤편에서 사람 하나가 겨우 들어갈 만한 동굴 입구가 나타났다.' },
    { id: 'c9-enter', mode: 'cave', speaker: '세나', text: '조금만 더 버텨요. 안쪽까지 들어가야 해요.' },
    { id: 'c9-barrier', mode: 'cave', narration: true, text: '두 사람이 동굴 깊숙이 들어오자 세나는 입구를 향해 손을 뻗었다. 얇은 막이 바위 표면을 따라 퍼지며 내부의 기척과 모습을 완전히 가렸다.' },
    { id: 'c9-barrier-check', mode: 'cave', speaker: '세나', text: '이제 밖에서는 안이 보이지 않을 거예요.' },
    { id: 'c9-lay-down', mode: 'cave', narration: true, text: '세나는 자신의 겉옷을 바닥에 펴고 주인공을 조심스럽게 눕혔다. 손을 떼자 상처 주변으로 피가 다시 번졌다.' },
    { id: 'c9-heal-attempt', mode: 'cave', narration: true, text: '세나는 상처 위에 손을 얹고 정신 에너지를 집중했다. 흐트러졌던 정신 에너지는 안정되기 시작했지만 벌어진 상처는 그대로였다.' },
    { id: 'c9-sena-confused', mode: 'cave', speaker: '세나', text: '정신 에너지는 돌아오는데…… 왜 상처가 닫히지 않죠?' },
    { id: 'c9-second-attempt', mode: 'cave', narration: true, text: '세나는 다시 치료를 시도했다. 그러나 피의 흐름도, 찢어진 살도 달라지지 않았다.' },
    { id: 'c9-sena-realize', mode: 'cave', speaker: '세나', text: '이건 정신의 상처가 아니에요.' },
    { id: 'c9-mc-pain', mode: 'cave', speaker: '주인공', text: '윽…….' },
    { id: 'c9-close-distance', mode: 'cave', narration: true, text: '주인공의 몸이 통증으로 굳자 세나는 곧바로 가까이 몸을 숙였다. 좁은 동굴 안에서 두 사람의 숨소리가 겹쳤다.' },
    { id: 'c9-sena-calm-him', mode: 'cave', speaker: '세나', text: '움직이지 마세요. 출혈부터 막아야 해요.' },
    { id: 'c9-tear-clothes', mode: 'cave', narration: true, text: '세나는 망설일 틈도 없이 자신의 옷자락을 길게 찢었다. 왜 그래야 하는지 생각하기 전에 손이 먼저 움직였다.' },
    { id: 'c9-pressure-start', mode: 'cave', narration: true, text: '접은 천을 상처 위에 대고 양손으로 강하게 눌렀다. 압박이 시작되자 주인공의 몸이 크게 떨렸다.' },
    { id: 'c9-mc-groan', mode: 'cave', speaker: '주인공', text: '크윽……!' },
    { id: 'c9-sena-apology', mode: 'cave', speaker: '세나', text: '아픈 거 알아요. 그래도 지금은 누르고 있어야 해요.' },
    { id: 'c9-heat-breath', mode: 'cave', narration: true, text: '세나는 거의 주인공의 몸 위로 기울어진 채 압박을 유지했다. 손바닥 아래로 전해지는 열과 불규칙한 숨이 점점 거칠어졌다.' },
    { id: 'c9-sena-tension', mode: 'cave', narration: true, text: '세나의 이마에도 땀이 맺혔다. 다급할수록 손에 힘을 일정하게 유지하려 애썼다.' },
    { id: 'c9-choice', mode: 'cave', speaker: '주인공', text: '의식이 흐려지는 와중에도 세나가 떨고 있다는 것은 알 수 있었다.', choices: [
      { id: 'c9-thanks', label: '고맙다고 말한다.', reply: '세나 씨…… 고맙습니다.', affection: { sena: 2 }, trust: { sena: 2 } },
      { id: 'c9-reassure', label: '괜찮다고 안심시킨다.', reply: '저는 괜찮습니다. 너무 무리하지 마세요.', affection: { sena: 1 }, trust: { sena: 3 }, traits: { considerate: 1 } },
      { id: 'c9-training', label: '훈련소 일을 묻는다.', reply: '훈련소에서도…… 세나 씨였습니까?', affection: { sena: 2 }, trust: { sena: 1 } }
    ] },
    { id: 'c9-sena-training-answer', mode: 'cave', speaker: '세나', text: '네. 그때도 제가 치료했어요. 그러니까 이번에도 버텨요.' },
    { id: 'c9-pressure-long', mode: 'cave', narration: true, text: '시간이 지나면서 천에 번지는 피가 조금씩 줄었다. 세나는 압박을 풀지 않은 채 주인공의 호흡과 안색을 계속 살폈다.' },
    { id: 'c9-sena-question-self', mode: 'cave', narration: true, text: '그제야 세나는 자신의 손을 내려다보았다. 상처를 누르고 천을 감는 움직임이 너무도 자연스러웠다.' },
    { id: 'c9-sena-memory', mode: 'cave', speaker: '세나', text: '이런 치료법을…… 나는 어디서 배운 거지?' },
    { id: 'c9-forgotten', mode: 'cave', narration: true, text: '떠오르는 기억은 없었다. 오래전 잊힌 무언가가 몸의 감각으로만 남아 있는 듯했다.' },
    { id: 'c9-bandage', mode: 'cave', narration: true, text: '세나는 찢은 천으로 상처를 단단히 감았다. 출혈은 멎었지만 주인공의 몸은 곧 뜨겁게 달아오르기 시작했다.' },
    { id: 'c9-fever', mode: 'cave', speaker: '세나', text: '열이 너무 높아요.' },
    { id: 'c9-cold-cloth', mode: 'cave', narration: true, text: '세나는 남은 천에 정신 에너지를 흘려 차갑게 만든 뒤 주인공의 이마와 목덜미를 닦았다.' },
    { id: 'c9-mc-fade', mode: 'cave', narration: true, text: '차가운 감각이 닿을 때마다 잠깐씩 정신이 돌아왔지만 오래 버티지는 못했다.' },
    { id: 'c9-sena-stay', mode: 'cave', speaker: '세나', text: '괜찮아요. 여기 있을게요. 그냥 눈 감고 쉬어요.' },
    { id: 'c9-night-start', mode: 'black', narration: true, text: '동굴 밖이 어두워진 뒤에도 세나는 잠들지 않았다.' },
    { id: 'c9-night-care', mode: 'cave', narration: true, text: '결계를 유지하면서 천을 식히고, 호흡을 확인하고, 풀린 붕대를 다시 조였다. 주인공이 통증에 신음할 때마다 가까이 몸을 숙여 상태를 살폈다.' },
    { id: 'c9-night-sena', mode: 'cave', narration: true, text: '몇 번이나 고개가 떨어졌지만 세나는 그때마다 다시 눈을 떴다. 동굴 안에는 주인공의 거친 숨과 세나의 낮은 목소리만 이어졌다.' },
    { id: 'c9-dawn', mode: 'cave', narration: true, text: '긴 밤이 지나고 동굴 입구 쪽이 희미하게 밝아졌다.' },
    { id: 'c9-wake', mode: 'cave', narration: true, text: '주인공은 무거운 눈꺼풀을 천천히 들어 올렸다. 옆구리의 통증은 남아 있었지만 밤새 이어지던 열은 가라앉아 있었다.' },
    { id: 'c9-look-side', mode: 'cave', narration: true, text: '고개를 돌리자 바로 옆에 세나가 있었다.' },
    { id: 'c9-sena-asleep', mode: 'cave', narration: true, text: '세나는 벽에 기대앉은 채 지쳐 잠들어 있었다. 한 손은 결계를 유지하던 자세 그대로였고, 다른 손에는 밤새 사용한 천이 쥐어져 있었다.' },
    { id: 'c9-wound-check', mode: 'cave', narration: true, text: '주인공은 자신의 상처를 내려다보았다. 찢어진 천이 단단히 감겨 있었고 피는 멈춰 있었다.' },
    { id: 'c9-final-thanks', mode: 'cave', speaker: '주인공', text: '……고맙습니다.' },
    { id: 'c9-rest-wait', mode: 'cave', narration: true, text: '세나는 듣지 못한 채 깊이 잠들어 있었다. 주인공은 그녀를 깨우지 않고 조용히 벽에 기대앉았다.' },
    { id: 'c9-clear', mode: 'black', center: 'CHAPTER 9 CLEAR' },
    { id: 'c9-end', mode: 'black', ending: true, center: '동굴에서의 긴 밤이 끝났다.' }
  ]
};