export const chapter010 = {
  id: 10,
  title: '두 번째 구조',
  scenes: [
    { id: 'c10-title', mode: 'black', center: 'CHAPTER 10\n\n두 번째 구조' },
    { id: 'c10-sena-wake', mode: 'cave', narration: true, text: '잠시 뒤 세나가 천천히 눈을 떴다. 자세를 바로잡으려던 순간 온몸의 피로가 몰려온 듯 작게 숨을 내쉬었다.' },
    { id: 'c10-sena-check', mode: 'cave', speaker: '세나', text: '일어나셨네요. 열은…… 다행히 내렸어요.' },
    { id: 'c10-mc-thanks', mode: 'cave', speaker: '주인공', text: '밤새 돌봐주신 겁니까?' },
    { id: 'c10-sena-dismiss', mode: 'cave', speaker: '세나', text: '지금은 감사 인사보다 움직일 수 있는지부터 확인해요.' },
    { id: 'c10-breath', mode: 'cave', narration: true, text: '두 사람은 한동안 말없이 상태를 정리했다. 주인공은 벽을 짚고 천천히 일어섰고, 세나는 결계를 거두기 전 동굴 밖의 기척을 살폈다.' },
    { id: 'c10-time-check', mode: 'cave', narration: true, text: '동굴 밖으로 들어오는 빛은 이미 아침의 색이 아니었다. 해가 높이 떠 있었다.' },
    { id: 'c10-sena-time', mode: 'cave', speaker: '세나', text: '호송팀과 만나기로 한 시간은 이미 지났어요.' },
    { id: 'c10-mc-mission', mode: 'cave', speaker: '주인공', text: '그럼 의뢰는…….' },
    { id: 'c10-sena-fail', mode: 'cave', speaker: '세나', text: '실패예요. 지금 중간 지점으로 가도 호송팀은 기다리지 않을 거예요.' },
    { id: 'c10-sena-priority', mode: 'cave', speaker: '세나', text: '남은 건 무사히 중앙도시로 돌아가는 일이에요.' },
    { id: 'c10-leave-cave', mode: 'forest-exit', narration: true, text: '세나는 결계를 거두고 먼저 동굴 밖으로 나갔다. 주변을 확인한 뒤 주인공에게 손을 내밀었다.' },
    { id: 'c10-return-start', mode: 'forest-exit', narration: true, text: '두 사람은 가능한 한 빠르게 중앙도시 방향으로 걸었다. 주인공은 옆구리를 누른 채 세나의 속도에 맞췄다.' },
    { id: 'c10-sena-tired', mode: 'forest-exit', narration: true, text: '세나의 걸음도 평소 같지 않았다. 밤새 결계를 유지하고 치료에 정신 에너지를 사용한 탓에 호흡이 자주 흐트러졌다.' },
    { id: 'c10-mc-concern', mode: 'forest-exit', speaker: '주인공', text: '세나 씨도 조금 쉬어야 하는 것 아닙니까?' },
    { id: 'c10-sena-no-rest', mode: 'forest-exit', speaker: '세나', text: '도시 외곽까지만 가요. 지금은 오래 머무는 쪽이 더 위험해요.' },
    { id: 'c10-chase-sound', mode: 'danger', narration: true, text: '그때 뒤쪽 숲에서 나뭇가지가 연달아 부러지는 소리가 들렸다.' },
    { id: 'c10-sena-stop', mode: 'danger', speaker: '세나', text: '멈춰요.' },
    { id: 'c10-nightmares-return', mode: 'danger', narration: true, text: '간밤에 사냥감을 놓친 악몽 무리들이 냄새와 기척을 따라 다시 나타났다. 수풀 사이로 검은 형체들이 하나둘 모습을 드러냈다.' },
    { id: 'c10-sena-cast', mode: 'battle', narration: true, text: '세나가 손을 들었지만 만들어진 장벽은 얇게 흔들리다 금세 사라졌다.' },
    { id: 'c10-sena-limit', mode: 'battle', speaker: '세나', text: '미안해요. 정신 에너지가 거의 남지 않았어요.' },
    { id: 'c10-mc-front', mode: 'battle', speaker: '주인공', text: '이번에는 제가 앞을 막겠습니다.' },
    { id: 'c10-fight-start', mode: 'battle', narration: true, text: '주인공은 짧은 검을 구현하고 가장 가까운 악몽에게 달려들었다. 상처는 여전히 아팠지만 물러설 곳은 없었다.' },
    { id: 'c10-mc-effort', mode: 'battle', narration: true, text: '한 마리를 밀어내고 곧바로 다음 공격을 받아냈다. 검은 버텼지만 주인공의 움직임은 점점 느려졌다.' },
    { id: 'c10-sena-support', mode: 'battle', narration: true, text: '세나는 남은 힘을 아껴 시야를 가리고 공격의 방향을 흐트러뜨렸다. 그러나 직접 상처를 회복시켜 줄 여력은 없었다.' },
    { id: 'c10-choice-fight', mode: 'battle', speaker: '주인공', text: '악몽들이 포위망을 좁혀 왔다.', choices: [
      { id: 'c10-protect-sena', label: '세나에게 접근하는 악몽을 먼저 막는다.', reply: '세나 씨 뒤로 물러나세요. 여기부터는 제가 막겠습니다.', trust: { sena: 2 }, traits: { considerate: 1 } },
      { id: 'c10-break-line', label: '한쪽을 돌파해 퇴로를 만든다.', reply: '한쪽을 뚫겠습니다. 길이 열리면 바로 움직이세요.', trust: { sena: 1 }, traits: { brave: 2 } },
      { id: 'c10-hold-ground', label: '자리를 지키며 기회를 기다린다.', reply: '흩어지면 더 위험합니다. 서로 보이는 곳에 있어요.', trust: { sena: 2 }, traits: { cautious: 1 } }
    ] },
    { id: 'c10-overpower', mode: 'battle', narration: true, text: '주인공은 끝까지 검을 휘둘렀지만 수가 줄지 않았다. 상처가 다시 욱신거리며 무릎이 꺾였다.' },
    { id: 'c10-sena-call-name', mode: 'battle', speaker: '세나', text: '{{playerName}} 씨!' },
    { id: 'c10-nightmare-leap', mode: 'battle', narration: true, text: '악몽 한 마리가 쓰러진 주인공을 향해 몸을 날렸다.' },
    { id: 'c10-arrow', mode: 'black', center: '빛의 화살이 어둠을 가르며 날아들었다.' },
    { id: 'c10-haru-arrive', mode: 'battle', narration: true, text: '화살은 악몽의 몸을 꿰뚫고 그대로 뒤편의 나무에 박혔다. 익숙한 목소리가 숲길 너머에서 들려왔다.' },
    { id: 'c10-haru-line', mode: 'battle', speaker: '하루', text: '이번이 두 번째네요.' },
    { id: 'c10-mc-haru', mode: 'battle', speaker: '주인공', text: '하루 씨…….' },
    { id: 'c10-haru-scold', mode: 'battle', speaker: '하루', text: '이야기는 나중에 해요. 아직 끝나지 않았습니다.' },
    { id: 'c10-fight-together', mode: 'battle', narration: true, text: '하루가 연달아 화살을 만들어 악몽들의 움직임을 끊었다. 주인공은 그 틈을 놓치지 않고 다시 검을 들었다.' },
    { id: 'c10-combination', mode: 'battle', narration: true, text: '하루가 빈틈을 만들면 주인공이 가까운 악몽을 베었다. 세나는 남은 힘으로 두 사람의 사각을 알렸다.' },
    { id: 'c10-last-kill', mode: 'battle', narration: true, text: '마지막 악몽이 주인공에게 달려들었다. 하루의 화살이 다리를 묶었고, 주인공의 검이 중심을 갈랐다.' },
    { id: 'c10-battle-end', mode: 'black', center: '악몽 무리 전멸' },
    { id: 'c10-after-battle', mode: 'forest-exit', narration: true, text: '숲이 조용해진 뒤에야 주인공은 검을 거두었다. 다리에 힘이 풀렸지만 하루가 곁에서 팔을 붙잡았다.' },
    { id: 'c10-haru-check', mode: 'forest-exit', speaker: '하루', text: '두 분 모두 상태가 좋지 않네요. 바로 돌아가죠.' },
    { id: 'c10-sena-thanks-haru', mode: 'forest-exit', speaker: '세나', text: '도와줘서 고마워요. 조금만 늦었으면 위험했을 거예요.' },
    { id: 'c10-haru-reason', mode: 'forest-exit', speaker: '하루', text: '호송팀이 두 분을 만나지 못했다고 길드에 알렸어요. 그래서 확인하러 왔습니다.' },
    { id: 'c10-return-city', mode: 'city', narration: true, text: '세 사람은 서로의 상태를 살피며 중앙도시로 돌아왔다. 이미 해가 기울기 시작한 뒤였다.' },
    { id: 'c10-guild-enter', mode: 'guild', narration: true, text: '길드 안은 평소보다 조용했다. 안내원은 세 사람의 모습을 확인하자 곧바로 길드장에게 보고했다.' },
    { id: 'c10-report', mode: 'guild', speaker: '세나', text: '중간 지점에 도착하지 못했습니다. 이동 중 악몽 무리와 충돌했고, 의뢰 시간도 넘겼어요.' },
    { id: 'c10-guildmaster-result', mode: 'guild', speaker: '길드장', text: '확인했다. 이번 정식 의뢰는 실패로 처리하겠다.' },
    { id: 'c10-mc-apology', mode: 'guild', speaker: '주인공', text: '죄송합니다. 제가 판단을 잘못했습니다.' },
    { id: 'c10-sena-share', mode: 'guild', speaker: '세나', text: '혼자만의 책임은 아니에요. 현장 판단과 복귀 모두 제가 함께 결정했습니다.' },
    { id: 'c10-guildmaster-close', mode: 'guild', speaker: '길드장', text: '책임 정리는 보고서를 받은 뒤에 한다. 지금은 둘 다 치료부터 받아라.' },
    { id: 'c10-mission-failed', mode: 'status', center: '정식 의뢰 결과\n\n물자 인계 지원\n실패' },
    { id: 'c10-final', mode: 'guild', narration: true, text: '첫 정식 의뢰는 실패로 끝났다. 하지만 두 사람은 살아서 돌아왔고, 하루는 말없이 그들의 곁을 지켰다.' },
    { id: 'c10-clear', mode: 'black', center: 'CHAPTER 10 CLEAR' },
    { id: 'c10-end', mode: 'black', ending: true, center: '첫 정식 의뢰가 실패로 기록되었다.' }
  ]
};