export const chapter001 = {
  id: 1,
  title: '낯선 세계',
  scenes: [
    { id: 'c1-title', mode: 'black', center: 'CHAPTER 1\n\n낯선 세계' },
    { id: 'c1-heartbeat', mode: 'black', center: '쿵……\n\n쿵……' },
    { id: 'c1-wake-sense', mode: 'black', narration: true, text: '차가운 공기가 뺨을 스쳤다. 축축한 흙냄새와 나뭇잎이 흔들리는 소리가 어둠 속으로 천천히 스며들었다.' },
    { id: 'c1-wake-1', mode: 'black', speaker: '주인공', text: '……여긴 어디지?' },
    { id: 'c1-forest-open', mode: 'forest', narration: true, text: '무거운 눈꺼풀을 들어 올리자 푸른 안개가 깔린 숲이 보였다. 손바닥 아래로 젖은 흙의 감촉이 선명하게 전해졌다.' },
    { id: 'c1-wake-2', mode: 'forest', narration: true, text: '몸을 일으키며 기억을 더듬었다. 하지만 이름도, 과거도, 이곳에 온 이유도 떠오르지 않았다.' },
    { id: 'c1-memory-pain', mode: 'forest', narration: true, text: '억지로 생각하려 할수록 머릿속이 하얗게 비었다. 대신 지금의 자신을 확인해야 한다는 낯선 감각만 또렷해졌다.' },
    { id: 'c1-status-call', mode: 'forest', speaker: '주인공', text: '내 상태를…… 확인할 수 있나?' },
    { id: 'c1-status-open', mode: 'status', center: '스테이터스\n\n이름  알 수 없음\n레벨  1\n힘  1   민첩  1\n체력  1   정신력  1\n\n스킬  없음\n구현 무기  없음' },
    { id: 'c1-status-reaction', mode: 'forest', speaker: '주인공', text: '……스테이터스?' },
    { id: 'c1-status-close', mode: 'forest', narration: true, text: '의문이 떠오르자 반투명한 창은 조용히 사라졌다. 처음 보는 현상인데도 여는 법과 닫는 법만큼은 몸이 기억하고 있었다.' },
    { id: 'c1-status-unease', mode: 'forest', narration: true, text: '이름은 알 수 없음. 무기도, 스킬도 없다. 알게 된 것은 지금의 자신이 아무것도 가진 게 없다는 사실뿐이었다.' },
    { id: 'c1-rustle', mode: 'danger', center: '바스락……' },
    { id: 'c1-turn', mode: 'danger', narration: true, text: '생각을 정리할 틈도 없이 등 뒤의 수풀이 흔들렸다. 천천히 몸을 돌리자 나무 사이의 어둠이 살아 있는 것처럼 꿈틀거렸다.' },
    { id: 'c1-nightmare-appear', mode: 'danger', narration: true, text: '검은 생명체가 모습을 드러냈다. 짐승과 비슷한 몸이었지만 눈도 입도 제자리에 있지 않았고, 뒤틀린 팔다리가 땅을 긁고 있었다.' },
    { id: 'c1-choice-first-danger', mode: 'danger', speaker: '주인공', text: '무기도 없다. 도망칠 길도 확실하지 않다. 지금 할 수 있는 건…….', choices: [
      { id: 'c1-danger-run', label: '주변 지형을 살피며 물러난다.', reply: '정면으로 맞서면 위험하다. 빠져나갈 길부터 찾아야 해.', traits: { cautious: 2 } },
      { id: 'c1-danger-guard', label: '두 팔을 들어 공격에 대비한다.', reply: '도망칠 틈이 없다면, 어떻게든 막아야 한다.', traits: { brave: 1 } },
      { id: 'c1-danger-stone', label: '발밑의 돌을 집어 든다.', reply: '무기가 없다면 있는 것부터 써야 해. 지금은 이거라도 충분하다.', traits: { cautious: 1, brave: 1 } }
    ] },
    { id: 'c1-first-hit', mode: 'battle', narration: true, text: '악몽이 땅을 박차고 달려들었다. 몸을 비트는 순간 날카로운 발톱이 옷자락을 찢고 지나갔다.' },
    { id: 'c1-counter', mode: 'battle', narration: true, text: '숨을 고를 틈도 없었다. 그대로 몸을 낮춰 악몽의 옆구리에 주먹을 내리쳤다.' },
    { id: 'c1-impact', mode: 'battle', center: '퍽—!' },
    { id: 'c1-strange-power', mode: 'battle', narration: true, text: '맨손으로 때렸을 뿐인데 검은 몸체가 크게 흔들렸다. 손등은 찢어졌지만, 악몽의 형체도 타격을 받은 자리부터 일그러졌다.' },
    { id: 'c1-realize', mode: 'battle', speaker: '주인공', text: '통한다……!' },
    { id: 'c1-finish', mode: 'battle', narration: true, text: '다시 달려드는 머리를 팔로 막고 몇 번이고 주먹을 내질렀다. 마지막 타격이 박히자 악몽은 검은 안개를 흩뿌리며 무너졌다.' },
    { id: 'c1-after-breath', mode: 'after-battle', narration: true, text: '한동안 그 자리에 선 채 거친 숨만 몰아쉬었다. 심장이 미친 듯이 뛰었고, 뒤늦게 손등의 통증이 밀려왔다.' },
    { id: 'c1-after', mode: 'after-battle', narration: true, text: '피가 흐르는 손 아래에는 붉고 검은 결정 하나가 남아 있었다. 정체를 알 수 없었지만 악몽이 사라진 자리에 남은 유일한 흔적이었다.' },
    { id: 'c1-crystal-reach', mode: 'after-battle', narration: true, text: '결정을 집어 들려 손을 뻗은 순간, 멀리서 다급한 목소리가 들려왔다.' },
    { id: 'c1-voice', mode: 'forest', speaker: '???', text: '거기 계세요?!' },
    { id: 'c1-haru-enter', mode: 'forest', narration: true, text: '활을 든 여자가 나무 사이에서 뛰어나왔다. 주변을 빠르게 살핀 그녀의 시선이 쓰러진 악몽의 흔적과 피 묻은 손에서 멈췄다.' },
    { id: 'c1-haru-shock', mode: 'forest', speaker: '???', text: '설마…… 무기도 없이 혼자 잡으신 거예요?' },
    { id: 'c1-choice-haru-first', mode: 'forest', speaker: '주인공', text: '처음 보는 사람이다. 경계해야 하지만, 지금은 혼자 남는 것보다 대화하는 편이 낫다.', choices: [
      { id: 'c1-haru-honest', label: '상황을 솔직하게 말한다.', reply: '저도 모르겠습니다. 눈을 뜨자마자 저게 나타났습니다.', trust: { haru: 1 } },
      { id: 'c1-haru-location', label: '여기가 어디인지 먼저 묻는다.', reply: '죄송하지만…… 여기가 어디인지 알려주실 수 있습니까?', traits: { cautious: 1 } },
      { id: 'c1-haru-help', label: '다친 손을 보여주며 도움을 청한다.', reply: '괜찮다면 치료할 방법부터 알려주시겠습니까?', affection: { haru: 1 }, traits: { considerate: 1 } }
    ] },
    { id: 'c1-haru-approach', mode: 'forest', narration: true, text: '여자는 잠시 경계하는 듯했지만, 다친 손을 확인하자 활을 내리고 천천히 가까이 다가왔다.' },
    { id: 'c1-haru-intro', mode: 'forest', speaker: '하루', text: '저는 하루예요. 우선 상처부터 볼게요.' },
    { id: 'c1-bandage', mode: 'forest', narration: true, text: '하루는 작은 가방에서 붕대를 꺼내 익숙한 손놀림으로 상처를 감쌌다. 따끔한 통증이 느껴지자 방금 전 일이 현실이었다는 감각이 선명해졌다.' },
    { id: 'c1-memory-check', mode: 'forest', speaker: '하루', text: '이름은요? 왜 혼자 몽환 숲에 계셨던 거예요?' },
    { id: 'c1-memory-answer', mode: 'forest', speaker: '주인공', text: '모르겠습니다. 제 이름도, 제가 누구인지도 기억나지 않습니다.' },
    { id: 'c1-haru-concern', mode: 'forest', narration: true, text: '붕대를 묶던 하루의 손이 잠시 멈췄다. 경계심이 스쳤지만, 이내 주변의 어두워진 숲을 돌아보고는 짧게 숨을 내쉬었다.' },
    { id: 'c1-haru-city', mode: 'forest', speaker: '하루', text: '여기서 계속 이야기하기에는 위험해요. 중앙도시로 가요. 길드라면 신원을 확인할 방법이 있을 거예요.' },
    { id: 'c1-choice-follow', mode: 'forest-exit', speaker: '하루', text: '걸을 수 있으세요?', choices: [
      { id: 'c1-follow-trust', label: '하루를 믿고 따라간다.', reply: '네. 지금은 하루 씨를 믿겠습니다.', affection: { haru: 1 }, trust: { haru: 2 }, flags: ['haru_first_trust'] },
      { id: 'c1-follow-question', label: '악몽이 무엇인지 묻는다.', reply: '따라가겠습니다. 다만 방금 그 생명체가 무엇인지 알려주세요.', trust: { haru: 1 }, traits: { cautious: 1 } },
      { id: 'c1-follow-thanks', label: '도움을 받아들인다.', reply: '도와주셔서 감사합니다. 폐를 끼치지 않겠습니다.', affection: { haru: 2 }, traits: { considerate: 1 } }
    ] },
    { id: 'c1-walk-start', mode: 'forest-exit', narration: true, text: '하루가 앞장서고 나는 몇 걸음 뒤에서 그녀를 따라갔다. 숲은 여전히 낯설었지만, 적어도 어디로 가야 하는지는 생겼다.' },
    { id: 'c1-world-explain', mode: 'forest-exit', speaker: '하루', text: '방금 싸운 건 악몽이에요. 사람의 정신을 먹고 자라는 존재죠. 자세한 이야기는 안전한 곳에 도착한 뒤에 해요.' },
    { id: 'c1-forest-road', mode: 'forest-exit', narration: true, text: '숲길을 걷는 동안 하루는 몇 번이나 뒤를 돌아 상태를 확인했다. 나도 모르게 붕대 감긴 손을 쥐었다 펴며 방금 들은 말을 되새겼다.' },
    { id: 'c1-city-view', mode: 'city-gate', narration: true, text: '한참 뒤 푸른 안개가 걷히고, 숲 너머로 거대한 성벽과 빽빽한 건물들이 모습을 드러냈다. 처음 보는 도시인데도 어딘가 익숙한 기분이 들었다.' },
    { id: 'c1-haru-arrive', mode: 'city-gate', speaker: '하루', text: '저기가 중앙도시예요. 이제 조금은 안심하셔도 돼요.' },
    { id: 'c1-city-enter', mode: 'city-gate', narration: true, text: '성문을 지나자 숲의 적막 대신 사람들의 목소리와 수레바퀴 소리가 밀려왔다. 낯선 세계에서 처음 마주한, 사람이 살아가는 풍경이었다.' },
    { id: 'c1-guild-front', mode: 'guild-front', narration: true, text: '하루를 따라 도시 중심부에 도착하자 검과 날개 문장이 걸린 거대한 건물이 보였다. 무기를 든 사람들이 끊임없이 드나들고 있었다.' },
    { id: 'c1-final', mode: 'guild-front', speaker: '하루', text: '여기가 길드예요. 들어가서 당신에 관한 기록부터 찾아봐요.' },
    { id: 'c1-final-thought', mode: 'guild-front', narration: true, text: '아무것도 기억나지 않는 나를 증명할 기록이 정말 남아 있을까. 대답을 찾기 위해 하루의 뒤를 따라 길드의 문 앞으로 걸음을 옮겼다.' },
    { id: 'c1-clear', mode: 'black', center: 'CHAPTER 1 CLEAR' },
    { id: 'c1-end', mode: 'black', ending: true, center: '낯선 세계에서 살아남았다.' }
  ]
};