window.CHAPTER_3=[
  {opening:true,chapter:3,title:'낯선 동침자'},
  {type:'sleep',text:'……아침인가.'},
  {type:'lodging',text:'희미한 아침빛이 작은 창문 사이로 스며들고 있었다.\n나는 무거운 눈꺼풀을 천천히 들어 올렸다.'},
  {type:'lodging',text:'몸을 일으키려던 순간, 바로 옆에서 작고 규칙적인 숨소리가 들렸다.'},
  {type:'black',text:'……응?'},
  {type:'lodging',text:'나는 움직임을 멈춘 채 천천히 고개를 돌렸다.'},
  {type:'momo-service'},
  {type:'black',text:'……뭐야.\n\n누구야, 이 여자?!'},
  {type:'momo-awake',speaker:'???',text:'……잘 잤어?'},
  {type:'lodging',speaker:state=>state.playerName,text:'자, 잠깐만요.\n누구세요? 그리고 왜 제 옆에서 자고 있는 겁니까?'},
  {type:'lodging',text:'나는 황급히 침대 끝으로 물러났다.\n잠이 단숨에 달아났다.'},
  {type:'lodging',speaker:'???',text:'응? 여기 빈방 아니었어?'},
  {type:'lodging',speaker:state=>state.playerName,text:'제가 자고 있었는데 어떻게 빈방입니까!'},
  {type:'lodging',text:'소녀는 그제야 방 안을 천천히 둘러보았다.\n그러고는 아무렇지도 않게 고개를 끄덕였다.'},
  {type:'lodging',speaker:'???',text:'그렇네. 안 비었었네.'},
  {type:'black',text:'……이걸 이제 알았다고?'},
  {type:'lodging',speaker:'???',text:'어젯밤 임무가 늦게 끝났거든.\n너무 피곤해서 빈방인 줄 알고 그냥 들어와 잤어.'},
  {type:'lodging',speaker:'???',text:'아, 나는 모모야.\n너는?'},
  {type:'lodging',speaker:state=>state.playerName,dynamic:state=>'……'+state.playerName+'입니다.'},
  {type:'lodging',speaker:'모모',text:'응. 잘 부탁해.'},
  {type:'black',text:'잘 부탁할 상황은 아닌 것 같은데…….'},
  {type:'lodging',text:'나는 더 따져 묻고 싶었지만, 어젯밤 세운 계획이 떠올랐다.\n우선 길드로 가서 내가 할 수 있는 일을 찾아야 했다.'},
  {type:'lodging',speaker:state=>state.playerName,text:'저는 길드에 가봐야 합니다.'},
  {type:'lodging',speaker:'모모',text:'길드? 나도 갈래.'},
  {type:'lodging',speaker:state=>state.playerName,text:'……왜요?'},
  {type:'lodging',speaker:'모모',text:'나도 길드 소속이니까.\n그리고 혼자 가는 것보다 같이 가는 게 좋잖아.'},
  {type:'lodging',text:'모모는 이미 따라나설 준비를 마친 얼굴이었다.\n거절할 틈조차 주지 않을 생각인 듯했다.'},
  {type:'black',text:'……아침부터 정신이 하나도 없군.'},
  {type:'lodgingExit',text:'길드로 가려면 숙소에서 나가야 한다.'},
  {type:'mainLobby',speaker:'모모',text:'길드로 가는 거지?\n나도 같이 갈게.',destination:'guild'},
  {type:'city',text:'길드가 가까워지자 건물 안쪽에서 큰 목소리가 새어 나왔다.'},
  {type:'city',speaker:'???',text:'아무리 사정이 딱해도 그렇지!\n길드 숙소를 마음대로 내주면 어쩌자는 거야!'},
  {type:'city',text:'문이 닫혀 있었는데도 목소리는 거리까지 또렷하게 들렸다.\n모모와 나는 잠시 서로를 바라봤다.'},
  {type:'guild',text:'문을 열고 들어가자 접수대 앞에 거구의 남성과 안내원이 서 있었다.\n남성은 두꺼운 팔을 꼬아 낀 채 안내원을 내려다보고 있었다.'},
  {type:'guild',speaker:'안내원',text:'길드장님, 하지만 어제 그분은 정말 갈 곳도 없었고…….'},
  {type:'guild',speaker:'길드장',text:'그래서 무상으로 재워줬다고?\n여기가 자선 시설인 줄 알아?'},
  {type:'guild',text:'그제야 나는 두 사람이 누구에 대해 이야기하고 있는지 알아차렸다.'},
  {type:'guild',speaker:state=>state.playerName,text:'잠시만요.\n어제 숙소를 이용한 사람은 접니다.'},
  {type:'guild',text:'두 사람의 시선이 동시에 내게 향했다.\n길드장은 나를 위아래로 천천히 훑어봤다.'},
  {type:'guild',speaker:state=>state.playerName,text:'신세를 진 값은 제가 치르겠습니다.\n제가 할 수 있는 일이 있다면 시켜주십시오.'},
  {type:'guild',speaker:'길드장',text:'할 수 있는 일이라…….'},
  {type:'guild',text:'길드장은 잠시 생각하더니 귀찮다는 듯 머리를 긁었다.'},
  {type:'guild',speaker:'길드장',text:'마침 아무도 맡으려 하지 않는 귀찮은 일이 하나 있지.\n그거라도 해.'},
  {type:'guild',speaker:state=>state.playerName,text:'알겠습니다.'},
  {type:'guild',text:'내가 대답하자 안내원이 조심스럽게 손을 들었다.'},
  {type:'guild',speaker:'안내원',text:'잠시만요, 길드장님.\n아직 바로 임무를 맡기실 수는 없어요.'},
  {type:'guild',speaker:'길드장',text:'왜?'},
  {type:'guild',speaker:'안내원',text:'이분은 아직 헌터로 등록되어 있지 않으니까요.\n길드의 정식 임무는 등록된 헌터만 수락할 수 있어요.'},
  {type:'guild',speaker:state=>state.playerName,text:'헌터 등록이 필요합니까?'},
  {type:'guild',speaker:'안내원',text:'네. 처음 등록하시는 분은 모두 F등급부터 시작해요.'},
  {type:'guild',text:'길드장은 잠시 나와 안내원을 번갈아 바라봤다.'},
  {type:'guild',speaker:'길드장',text:'그럼 등록부터 시켜.'},
  {type:'guild',text:'그 말을 남기고 길드장은 접수대에서 한 걸음 물러났다.\n안내원은 작은 한숨을 내쉰 뒤 내게 서류를 내밀었다.'},
  {type:'guild',speaker:'안내원',text:'이름과 기본 정보만 확인할게요.\n길드 규칙에 동의하시면 등록은 금방 끝납니다.'},
  {type:'guild',text:'나는 안내원이 짚어주는 항목을 하나씩 확인했다.\n적을 수 없는 부분은 비워둔 채, 마지막으로 이름을 남겼다.'},
  {type:'guild',text:'안내원이 서류를 장치 위에 올려놓자 희미한 빛이 번졌다.\n잠시 뒤, 작은 패 하나가 장치 아래에서 밀려 나왔다.'},
  {type:'guild',speaker:'안내원',text:'등록이 완료됐습니다.\n이제부터 정식 F등급 헌터예요.'},
  {type:'black',text:'F등급 헌터…….\n\n이 세계에서 처음으로 내게 생긴 신분이었다.'},
  {type:'guild',text:'안내원은 헌터 패와 함께 얇은 임무서를 내게 건넸다.'},
  {type:'guild',speaker:'안내원',text:'임무 내용은 이 안에 적혀 있어요.\n확인한 뒤 출발하시면 됩니다.'},
  {type:'guildExit',text:'헌터 패와 임무서를 챙겼다.\n이제 길드 밖으로 나가 내용을 확인하면 된다.'},
  {type:'lobbyPause',speaker:'모모',text:'밖에서 의뢰서부터 확인해보자.'},
  {type:'black',text:'나는 길드 앞에서 임무서를 펼쳤다.'},
  {type:'black',text:'의뢰명 — 외곽 성벽 보수\n\n악몽의 습격으로 파손된 외벽 일부를 정비한다.\n위험도는 낮으며, 보수 자재는 현장에서 지급된다.'},
  {type:'black',text:'전투 임무는 아니었다.\n숙박비를 갚기 위한 첫 일로는 충분해 보였다.'},
  {type:'relationshipChoice',speaker:'모모',screenType:'city',affinityKey:'momoAffinity',text:'모모가 내 손에 들린 임무서를 힐끗 바라봤다.\n\n“나도 같이 가도 돼?”',choices:[
    {text:'물론이죠. 같이 가요.',affinity:3,response:'정말? 좋아!\n\n모모의 얼굴이 금세 밝아졌다.'},
    {text:'괜찮습니다. 함께 가시죠.',affinity:0,response:'응. 그럼 같이 가자.\n\n모모는 만족한 듯 고개를 끄덕였다.'},
    {text:'따라오셔도 상관은 없습니다.',affinity:-2,response:'……응. 그래도 같이 갈게.\n\n모모는 잠깐 입술을 내밀었다가 내 옆으로 다가왔다.'}
  ]},
  {type:'relationshipResponse',speaker:'모모',screenType:'city',fallback:'그럼 같이 가자.'},
  {type:'mainLobby',speaker:'모모',text:'외곽은 이쪽이야.\n새로 열린 타일을 누르면 돼.',destination:'exterior',missionGoal:'외곽으로 이동하세요.',missionProgress:60},
  {type:'city',text:'외곽으로 향하는 길은 처음에는 제법 붐볐다.\n상인들의 목소리와 사람들의 웃음소리가 거리 곳곳에서 뒤섞였다.'},
  {type:'city',text:'하지만 걸음을 옮길수록 가게의 수가 줄고, 오가는 사람도 눈에 띄게 적어졌다.\n시끌벅적하던 소리는 어느새 멀어지고 있었다.'},
  {type:'city',speaker:'모모',text:'이쪽은 처음이지?'},
  {type:'city',speaker:state=>state.playerName,text:'네. 생각보다 많이 조용하군요.'},
  {type:'city',speaker:'모모',text:'응. 중심가에서 조금만 벗어나도 금방 이래.\n나는 이런 길도 좋아해. 사람 많은 곳도 좋고, 조용한 곳도 좋고.'},
  {type:'city',text:'모모는 내 옆을 걷다가 몇 걸음 앞서 나갔고, 다시 뒤돌아 나를 기다렸다.\n가만히 있는 것보다는 누군가와 함께 움직이는 걸 좋아하는 사람처럼 보였다.'},
  {type:'city',speaker:'모모',text:'아, 맞다. 너는 오늘이 첫 임무지?'},
  {type:'city',speaker:state=>state.playerName,text:'그렇습니다. 헌터가 된 것도 오늘이고요.'},
  {type:'city',speaker:'모모',text:'그럼 내가 선배네?'},
  {type:'city',text:'모모는 어깨를 살짝 펴며 괜히 뿌듯한 표정을 지었다.'},
  {type:'city',speaker:'모모',text:'걱정하지 마. 이런 일은 나도 많이 해봤어.\n길드에서 사람이 필요하면 자주 불러주거든.'},
  {type:'black',text:'……사람이 필요할 때마다 불려 다닌다는 뜻인가.'},
  {type:'outskirts',text:'길 끝에 다다르자 넓은 성벽이 모습을 드러냈다.\n도시의 소음은 거의 들리지 않았고, 바람이 풀잎을 스치는 소리만 희미하게 남아 있었다.'},
  {type:'outskirts',text:'성벽 한쪽은 크게 무너진 것은 아니었지만, 표면 곳곳이 깨지고 갈라져 있었다.\n근처에는 보수용 자재와 도구가 가지런히 놓여 있었다.'},
  {type:'outskirts',speaker:'모모',text:'여기다. 생각보다 심하진 않네.'},
  {type:'outskirts',speaker:state=>state.playerName,text:'그럼 바로 시작하죠.'},
  {type:'black',text:'우리는 곧바로 작업을 시작했다.'},
  {type:'outskirts',text:'깨진 부분을 걷어내고, 자재를 나르고, 갈라진 틈을 하나씩 메웠다.\n모모는 힘이 센 편은 아니었지만 쉬지 않고 부지런히 움직였다.'},
  {type:'outskirts',speaker:'모모',text:'이거 생각보다 무거운데…….\n그래도 둘이 하니까 금방 끝나겠다.'},
  {type:'black',text:'시간이 흘렀다.\n\n해가 머리 위를 지나 조금씩 기울기 시작할 무렵—'},
  {type:'outskirts',text:'마지막 틈까지 메우고 나서야 우리는 손에 묻은 먼지를 털어냈다.\n반나절이면 충분했다.'},
  {type:'outskirts',speaker:'모모',text:'끝났다!\n생각보다 빨리 했지?'},
  {type:'outskirts',speaker:state=>state.playerName,text:'네. 임무 완료군요.'},
  {type:'missionComplete',title:'외곽 성벽 보수',reward:5000},
  {type:'outskirts',text:'해는 어느새 성벽 너머로 기울고 있었다.\n길게 늘어진 두 사람의 그림자가 바람에 흔들리는 풀밭 위로 뻗어 있었다.'},
  {type:'outskirts',speaker:'모모',text:'그럼 돌아갈까?\n배고프다.'},
  {type:'outskirts',text:'모모는 기지개를 켜며 먼저 몸을 돌렸다.\n나도 도구를 내려놓고 뒤를 따르려던 순간이었다.'},
  {type:'black',text:'……사각.'},
  {type:'outskirts',text:'마른 풀을 밟는 듯한 소리가 들렸다.\n바람과는 다른, 분명한 움직임이었다.'},
  {type:'outskirts',speaker:state=>state.playerName,text:'……잠깐.'},
  {type:'outskirts',text:'모모가 멈춰 섰다.\n조금 전까지 밝던 표정이 굳어 있었다.'},
  {type:'outskirts',speaker:'모모',text:'……뭐야?'},
  {type:'black',text:'사각.\n\n사각.'},
  {type:'outskirts',text:'이번에는 더 가까웠다.\n성벽 바깥쪽, 길게 자란 풀숲 사이에서 검은 무언가가 천천히 몸을 일으켰다.'},
  {type:'outskirts',speaker:'모모',text:'……악몽.'},
  {type:'outskirts',text:'모모의 목소리가 작게 떨렸다.\n나는 본능적으로 몸을 낮추며 눈앞의 존재를 바라봤다.'},
  {type:'black',text:'임무는 끝났다.\n\n하지만 아직 돌아갈 수는 없었다.'}
];