window.CHAPTER_3=[
  {opening:true,chapter:3,title:'낯선 동침자'},
  {type:'sleep',text:'……아침인가.'},
  {type:'lodging',text:'희미한 아침빛이 작은 창문 사이로 스며들고 있었다.\n나는 무거운 눈꺼풀을 천천히 들어 올렸다.'},
  {type:'lodging',text:'몸을 일으키려던 순간, 이불이 생각보다 묵직하게 느껴졌다.'},
  {type:'black',text:'……응?'},
  {type:'lodging',text:'무심코 이불을 살짝 들춰보니, 처음 보는 소녀가 바로 옆에서 깊이 잠들어 있었다.'},
  {type:'momo-service'},
  {type:'black',text:'……뭐야.\n\n누구지, 이 여자?'},
  {type:'lodging',text:'소녀는 내가 깨어난 것도 모른 채 작고 규칙적인 숨소리를 내고 있었다.\n너무 깊이 잠든 탓인지 미동조차 없었다.'},
  {type:'black',text:'깨워서 따져 묻고 싶지만…… 지금은 길드에 가는 게 먼저다.'},
  {type:'lodging',text:'나는 소녀가 깨지 않도록 조심스럽게 침대에서 빠져나와 옷을 챙겨 입었다.'},
  {type:'lodging',text:'어젯밤 세운 계획이 떠올랐다.\n우선 길드로 가서 내가 할 수 있는 일을 찾아야 했다.'},
  {type:'lodgingExit',text:'낯선 소녀를 방에 남겨둔 채 조용히 숙소를 나섰다.'},
  {type:'mainLobby',text:'길드에 가서 할 수 있는 일을 찾아보자.',destination:'guild'},
  {type:'city',text:'길드가 가까워지자 건물 안쪽에서 큰 목소리가 새어 나왔다.'},
  {type:'city',speaker:'???',text:'신원도 확인되지 않은 외지인을 길드 숙소에 들였다고?'},
  {type:'city',text:'문이 닫혀 있었는데도 목소리는 거리까지 또렷하게 들렸다.\n아무래도 내 이야기를 하는 것 같았다.'},
  {type:'guild',text:'문을 열고 들어가자 접수대 앞에 거구의 남성과 안내원이 서 있었다.\n남성은 두꺼운 팔을 꼬아 낀 채 안내원을 바라보고 있었다.'},
  {type:'guild',speaker:'안내원',text:'길드장님, 하지만 어제 그분은 정말 갈 곳도 없었고…….'},
  {type:'guild',speaker:'길드장',text:'사정이 딱한 것과 신원을 확인하는 건 별개의 문제다.\n무슨 일이 생기면 네가 책임질 수 있나?'},
  {type:'guild',text:'그제야 나는 두 사람이 누구에 대해 이야기하고 있는지 확신했다.'},
  {type:'guild',speaker:state=>state.playerName,text:'잠시만요.\n어제 숙소를 이용한 사람은 접니다.'},
  {type:'guild',text:'두 사람의 시선이 동시에 내게 향했다.\n길드장은 말없이 나를 위아래로 훑어봤다.'},
  {type:'guild',speaker:state=>state.playerName,text:'도움만 받을 수는 없습니다.\n잡일이라도 좋으니 제가 할 수 있는 일을 시켜주십시오.'},
  {type:'guild',speaker:'길드장',text:'말은 잘하는군.'},
  {type:'guild',text:'길드장은 잠시 나를 바라보다가 짧게 턱을 쓸었다.'},
  {type:'guild',speaker:'길드장',text:'그럼 잔심부름이라도 하던가.'},
  {type:'guild',speaker:state=>state.playerName,text:'알겠습니다.'},
  {type:'guild',text:'내가 대답하자 안내원이 조심스럽게 손을 들었다.'},
  {type:'guild',speaker:'안내원',text:'잠시만요, 길드장님.\n그래도 외곽으로 나가려면 헌터 등록부터 해야 해요.'},
  {type:'guild',speaker:'길드장',text:'그럼 등록부터 시켜.'},
  {type:'guild',speaker:state=>state.playerName,text:'헌터 등록이 필요합니까?'},
  {type:'guild',speaker:'안내원',text:'네. 처음 등록하시는 분은 모두 F등급부터 시작해요.\n절차는 오래 걸리지 않아요.'},
  {type:'guild',text:'안내원은 작은 한숨을 내쉰 뒤 내게 서류를 내밀었다.'},
  {type:'guild',speaker:'안내원',text:'이름과 기본 정보만 확인할게요.\n길드 규칙에 동의하시면 등록은 금방 끝납니다.'},
  {type:'guild',text:'나는 안내원이 짚어주는 항목을 하나씩 확인했다.\n적을 수 없는 부분은 비워둔 채, 마지막으로 이름을 남겼다.'},
  {type:'guild',text:'안내원이 서류를 장치 위에 올려놓자 희미한 빛이 번졌다.\n잠시 뒤, 작은 패 하나가 장치 아래에서 밀려 나왔다.'},
  {type:'guild',speaker:'안내원',text:'등록이 완료됐습니다.\n이제부터 정식 F등급 헌터예요.'},
  {type:'black',text:'F등급 헌터…….\n\n이 세계에서 처음으로 내게 생긴 신분이었다.'},
  {type:'guild',speaker:'길드장',text:'모모.'},
  {type:'guild',speaker:'???',text:'네?'},
  {type:'guild',text:'길드장 뒤편에서 모습을 드러낸 소녀를 보는 순간, 나는 잠시 말을 잃었다.\n아침에 같은 침대에서 자고 있던 바로 그 소녀였다.'},
  {type:'black',text:'……왜 저 여자가 여기 있지?'},
  {type:'guild',speaker:'길드장',text:'외곽 성벽 쪽에 보수할 곳이 있다.\n이 녀석 데리고 가서 일 좀 도와.'},
  {type:'guild',speaker:'모모',text:'저기요, 저도 가야 해요?'},
  {type:'guild',speaker:'길드장',text:'사람이 필요하다. 가.'},
  {type:'guild',speaker:'모모',text:'……네. 가라면 가야죠.'},
  {type:'guild',text:'모모는 내 얼굴을 처음 보는 사람처럼 잠시 바라봤다.\n아침에 같은 침대에서 자고 있었다는 사실은 전혀 모르는 눈치였다.'},
  {type:'guild',speaker:'안내원',text:'두 분이 하실 일은 외곽 성벽의 파손 부위를 정리하고 보수하는 거예요.\n자재와 도구는 현장에 준비되어 있습니다.'},
  {type:'guildExit',text:'헌터 패를 챙겼다.\n이제 모모와 함께 외곽으로 향하면 된다.'},
  {type:'lobbyPause',speaker:'모모',text:'저기요. 밖으로 나가서 어디로 가는지부터 확인해요.'},
  {type:'black',text:'나는 길드 앞에서 안내원이 건넨 작업 지시서를 펼쳤다.'},
  {type:'black',text:'작업명 — 외곽 성벽 보수\n\n악몽의 습격으로 파손된 외벽 일부를 정비한다.\n위험도는 낮으며, 보수 자재는 현장에서 지급된다.'},
  {type:'black',text:'정식 의뢰라기보다는 길드의 잔심부름에 가까웠다.\n신세를 갚기 위한 첫 일로는 충분해 보였다.'},
  {type:'relationshipChoice',speaker:'모모',screenType:'city',affinityKey:'momoAffinity',text:'모모가 내 손에 들린 작업 지시서를 힐끗 바라봤다.\n\n“저기요. 그래도 같이 가는 건 괜찮죠?”',choices:[
    {text:'물론이죠. 같이 가요.',affinity:3,response:'정말? 다행이다!\n\n모모의 얼굴이 금세 밝아졌다.'},
    {text:'괜찮습니다. 함께 가시죠.',affinity:0,response:'응. 그럼 같이 가자.\n\n모모는 만족한 듯 고개를 끄덕였다.'},
    {text:'길드장님의 지시니까요.',affinity:-2,response:'……그렇긴 하지.\n\n모모는 잠깐 입술을 내밀었다가 내 옆으로 다가왔다.'}
  ]},
  {type:'relationshipResponse',speaker:'모모',screenType:'city',fallback:'그럼 같이 가자.'},
  {type:'mainLobby',speaker:'모모',text:'외곽은 이쪽이야.\n새로 열린 타일을 누르면 돼.',destination:'exterior',missionGoal:'외곽으로 이동하세요.',missionProgress:60},
  {type:'city',text:'외곽으로 향하는 길은 처음에는 제법 붐볐다.\n상인들의 목소리와 사람들의 웃음소리가 거리 곳곳에서 뒤섞였다.'},
  {type:'city',text:'하지만 걸음을 옮길수록 가게의 수가 줄고, 오가는 사람도 눈에 띄게 적어졌다.\n시끌벅적하던 소리는 어느새 멀어지고 있었다.'},
  {type:'city',speaker:'모모',text:'이쪽은 처음이지?'},
  {type:'city',speaker:state=>state.playerName,text:'네. 생각보다 많이 조용하군요.'},
  {type:'city',speaker:'모모',text:'응. 중심가에서 조금만 벗어나도 금방 이래.\n나는 이런 길도 좋아해. 사람 많은 곳도 좋고, 조용한 곳도 좋고.'},
  {type:'city',text:'모모는 내 옆을 걷다가 몇 걸음 앞서 나갔고, 다시 뒤돌아 나를 기다렸다.\n가만히 있는 것보다는 누군가와 함께 움직이는 걸 좋아하는 사람처럼 보였다.'},
  {type:'city',speaker:'모모',text:'아, 맞다. 너는 오늘이 첫 임무지?'},
  {type:'city',speaker:state=>state.playerName,text:'그렇습니다. 헌터가 된 것도 오늘이고요.'},
  {type:'city',speaker:'모모',text:'그럼 내가 선배네?'},
  {type:'city',text:'모모는 어깨를 살짝 펴며 괜히 뿌듯한 표정을 지었다.'},
  {type:'city',speaker:'모모',text:'걱정하지 마. 이런 일은 나도 많이 해봤어.\n길드에서 사람이 필요하면 자주 불러주거든.'},
  {type:'black',text:'……사람이 필요할 때마다 불려 다닌다는 뜻인가.'},
  {type:'outskirts',text:'길 끝에 다다르자 넓은 성벽이 모습을 드러냈다.\n도시의 소음은 거의 들리지 않았고, 바람이 풀잎을 스치는 소리만 희미하게 남아 있었다.'},
  {type:'outskirts',text:'성벽 한쪽은 크게 무너진 것은 아니었지만, 표면 곳곳이 깨지고 갈라져 있었다.\n근처에는 보수용 자재와 도구가 가지런히 놓여 있었다.'},
  {type:'outskirts',speaker:'모모',text:'여기다. 생각보다 심하진 않네.'},
  {type:'outskirts',speaker:state=>state.playerName,text:'그럼 바로 시작하죠.'},
  {type:'black',text:'우리는 곧바로 작업을 시작했다.'},
  {type:'outskirts',text:'깨진 부분을 걷어내고, 자재를 나르고, 갈라진 틈을 하나씩 메웠다.\n모모는 힘이 센 편은 아니었지만 쉬지 않고 부지런히 움직였다.'},
  {type:'outskirts',speaker:'모모',text:'이거 생각보다 무거운데…….\n그래도 둘이 하니까 금방 끝나겠다.'},
  {type:'black',text:'시간이 흘렀다.\n\n해가 머리 위를 지나 조금씩 기울기 시작할 무렵—'},
  {type:'outskirts',text:'마지막 틈까지 메우고 나서야 우리는 손에 묻은 먼지를 털어냈다.\n반나절이면 충분했다.'},
  {type:'outskirts',speaker:'모모',text:'끝났다!\n생각보다 빨리 했지?'},
  {type:'outskirts',speaker:state=>state.playerName,text:'네. 임무 완료군요.'},
  {type:'missionComplete',title:'외곽 성벽 보수',reward:5000},
  {type:'outskirts',text:'해는 어느새 성벽 너머로 기울고 있었다.\n길게 늘어진 두 사람의 그림자가 바람에 흔들리는 풀밭 위로 뻗어 있었다.'},
  {type:'outskirts',speaker:'모모',text:'그럼 돌아갈까?\n배고프다.'},
  {type:'outskirts',text:'모모는 기지개를 켜며 먼저 몸을 돌렸다.\n나도 도구를 내려놓고 뒤를 따르려던 순간이었다.'},
  {type:'black',text:'……사각.'},
  {type:'outskirts',text:'마른 풀을 밟는 듯한 소리가 들렸다.\n바람과는 다른, 분명한 움직임이었다.'},
  {type:'outskirts',speaker:state=>state.playerName,text:'……잠깐.'},
  {type:'outskirts',text:'모모가 멈춰 섰다.\n조금 전까지 밝던 표정이 굳어 있었다.'},
  {type:'outskirts',speaker:'모모',text:'……뭐야?'},
  {type:'black',text:'사각.\n\n사각.'},
  {type:'outskirts',text:'이번에는 더 가까웠다.\n성벽 바깥쪽, 길게 자란 풀숲 사이에서 검은 무언가가 천천히 몸을 일으켰다.'},
  {type:'outskirts',speaker:'모모',text:'……악몽.'},
  {type:'outskirts',text:'모모의 목소리가 작게 떨렸다.\n나는 본능적으로 몸을 낮추며 눈앞의 존재를 바라봤다.'},
  {type:'black',text:'임무는 끝났다.\n\n하지만 아직 돌아갈 수는 없었다.'}
];