window.CHAPTER_4=[
  {opening:true,chapter:4,title:'첫 번째 성장'},
  {type:'guild',text:'외곽에서 돌아온 우리는 곧장 길드로 향했다.\n하루는 길드 안으로 들어서자마자 곧바로 길드장을 향해 걸어갔다.'},
  {type:'guild',speaker:'하루',text:'길드장님.'},{type:'guild',speaker:'길드장',text:'어, 왔냐.'},{type:'guild',speaker:'하루',text:'F등급 헌터 둘을 외곽으로 보내셨어요?'},{type:'guild',speaker:'길드장',text:'뭐, 잘 돌아왔잖아.'},{type:'guild',speaker:'하루',text:'제가 조금만 늦었으면 못 돌아왔을 수도 있어요.'},{type:'guild',speaker:'길드장',text:'그래서 네가 데려왔잖아.'},{type:'guild',speaker:'하루',text:'그게 무슨 말이에요?'},{type:'guild',text:'길드장이 턱짓으로 나를 가리켰다.'},{type:'guild',speaker:'길드장',text:'저 녀석 말이야.\n처음 이 도시에 데려온 건 너잖아.'},{type:'guild',speaker:'하루',text:'헌터로 등록시킨 건 길드장님이잖아요.'},{type:'guild',speaker:'길드장',text:'그건 잔심부름 좀 시키려고 그런 거고.'},{type:'guild',speaker:'하루',text:'그런 사람을 외곽으로 보내요?'},{type:'guild',text:'잠시 말이 막힌 길드장이 슬쩍 시선을 피했다.'},{type:'guild',speaker:'길드장',text:'……아무튼.'},{type:'guild',speaker:'하루',text:'아무튼이요?'},{type:'guild',speaker:'길드장',text:'네가 데려왔으니 네가 책임져.'},{type:'guild',speaker:'하루',text:'잠깐만요. 그게 무슨 논리예요?'},{type:'guild',speaker:'길드장',text:'난 바쁘다.'},{type:'guild',speaker:'하루',text:'길드장님.'},{type:'guild',speaker:'길드장',text:'둘 다 잘 부탁한다.'},{type:'guild',speaker:'하루',text:'길드장님!'},{type:'guild',text:'길드장은 더 붙잡히기 전에 슬쩍 자리를 피해버렸다.\n하루는 멀어지는 길드장의 뒷모습을 어이없다는 듯 바라봤다.'},{type:'guild',text:'그리고 천천히 뒤를 돌아봤다.\n온몸이 지쳐 있는 나와, 그 옆에서 고개를 푹 숙이고 있는 모모가 서 있었다.'},{type:'guild',speaker:'하루',text:'……하아.'},{type:'guild',speaker:'하루',text:'그래서, 두 분은 어떻게 하고 싶으세요?'},{type:'guild',speaker:'모모',text:'난…….'},{type:'guild',text:'모모는 입을 열었지만, 그다음 말은 쉽게 나오지 않았다.'},{type:'guild',speaker:state=>state.playerName,text:'강해지고 싶어.'},{type:'guild',text:'하루의 시선이 내게 향했다.'},{type:'guild',speaker:state=>state.playerName,text:'오늘처럼 아무것도 못 한 채 끝내고 싶지는 않아.'},{type:'guild',text:'잠시 침묵이 흘렀다.'},{type:'guild',speaker:'모모',text:'……나도.'},{type:'guild',text:'모모는 여전히 고개를 숙이고 있었다.'},{type:'guild',speaker:'하루',text:'정말 괜찮겠어요?'},{type:'guild',text:'모모는 바로 대답하지 못했다.\n하지만 이번에는 도망치지 않고, 아주 작게 고개를 끄덕였다.'},{type:'guild',speaker:'하루',text:'알겠어요.'},{type:'guild',speaker:'하루',text:'오늘은 푹 쉬세요.\n내일 아침, 훈련장으로 오세요.'},{type:'guild',text:'하루는 나와 모모를 번갈아 바라봤다.'},{type:'guild',speaker:'하루',text:'제가 직접 훈련시키겠습니다.'},
  {type:'black',text:'그렇게 길고 긴 하루가 끝났다.\n\n이 세계에서 살아남으려면, 오늘보다 강해져야 한다.\n다시는 아무것도 하지 못한 채 누군가를 기다리고 싶지 않았다.'},{type:'black',text:'다음 날 — 훈련장'},
  {type:'mainLobby',speaker:'하루',text:'훈련 센터는 헌터 지구 안쪽에 있어요.\n헌터 지구로 이동하세요.',destination:'village',missionTitle:'CHAPTER 4 · 첫 번째 성장',missionGoal:'헌터 지구의 훈련 센터로 이동하세요.',missionProgress:10},
  {type:'city',text:'헌터 지구에는 훈련 센터와 장비 정비소를 비롯해 헌터들이 이용하는 여러 시설이 모여 있었다.\n나는 하루와 모모를 따라 안쪽으로 들어갔다.'},{type:'hunterDistrict'},{type:'trainingMap',unlocked:1},
  {type:'city',speaker:'하루',text:'먼저 가장 기본적인 공격부터 확인할게요.\n복잡하게 생각하지 말고, 제 움직임을 보고 들어오세요.'},{type:'city',speaker:state=>state.playerName,text:'하루 씨를 상대로요?'},{type:'city',speaker:'하루',text:'훈련이니까 괜찮아요.\n제가 멈추라고 할 때까지 계속하세요.'},{type:'black',text:'1-1 — 기초 공격 훈련'},{type:'trainingBattle'},{type:'speedUnlock'},{type:'city',speaker:'하루',text:'처음치고는 나쁘지 않았어요.\n이제 전투 흐름을 조금 더 빠르게 확인할 수 있을 거예요.'},
  {type:'trainingMap',unlocked:2},{type:'city',speaker:'하루',text:'다음은 모모 씨 차례예요.'},{type:'city',speaker:'모모',text:'……나?'},{type:'city',speaker:'하루',text:'네. 아까 외곽에서 사용했던 능력은 쓰지 말고 싸워보세요.'},{type:'city',speaker:'모모',text:'그걸 안 쓰고……?'},{type:'city',speaker:'하루',text:'계속 숨는 것만으로는 강해질 수 없어요.\n이번에는 피하지 말고, 저를 보고 움직여보세요.'},{type:'city',text:'모모는 잠시 아무 말도 하지 않았다.\n겁먹은 표정은 여전했지만, 이번에는 도망치지 않고 천천히 앞으로 나섰다.'},{type:'black',text:'1-2 — 모모의 차례'},{type:'trainingBattleMomo'},{type:'city',text:'훈련이 끝나자 모모는 거친 숨을 몰아쉬며 자리에 주저앉았다.'},{type:'city',speaker:'하루',text:'잘했어요. 이기고 지는 건 중요하지 않아요.\n도망치지 않고 끝까지 서 있었잖아요.'},{type:'city',speaker:'모모',text:'……응.'},
  {type:'trainingMap',unlocked:3},{type:'city',speaker:'하루',text:'그런데 한 가지 이상한 게 있어요.'},{type:'city',speaker:state=>state.playerName,text:'뭐가?'},{type:'city',speaker:'하루',text:'왜 계속 맨손으로 싸우세요?'},{type:'city',speaker:state=>state.playerName,text:'……무기가 없으니까.'},{type:'city',speaker:'하루',text:'없다고요?'},{type:'city',text:'하루가 잠시 나를 바라보다가, 무언가를 깨달은 듯 눈을 가늘게 떴다.'},{type:'city',speaker:'하루',text:'설마 무기를 구현하는 방법도 모르는 거예요?'},{type:'city',speaker:state=>state.playerName,text:'구현?'},{type:'city',speaker:'하루',text:'눈을 감고 집중해 보세요.\n가장 자연스럽게 손에 잡히는 형태를 떠올리는 거예요.'},{type:'city',text:'나는 눈을 감고 손을 앞으로 뻗었다.\n처음에는 아무 일도 일어나지 않았다.'},{type:'city',speaker:'하루',text:'억지로 만들려고 하지 마세요.\n손에 쥐고 싶다고 느껴지는 걸 그대로 떠올려요.'},{type:'city',text:'다시 집중했다.\n손끝에서 희미한 빛이 모이기 시작했다.'},{type:'city',text:'빛은 몇 번이나 흔들리고 흩어졌다.\n그러다 마침내 손안에서 하나의 형태를 이루었다.'},{type:'black',text:'한 자루의 검.\n\n길지도, 짧지도 않은 한손검이 내 손에 쥐어져 있었다.\n하지만 검신의 표면은 희미하게 흔들리고 있었다.\n마치 아직 완전히 형태를 정하지 못한 것처럼.'},{type:'city',speaker:'모모',text:'……검이다.'},{type:'city',speaker:'하루',text:'처음부터 이 정도로 형태를 잡았다고요……?'},{type:'city',text:'하루는 잠시 검을 바라보다가 곧 표정을 가다듬었다.'},{type:'city',speaker:'하루',text:'아직 불안정해요.\n하지만 분명 당신의 무기예요.'},{type:'black',text:'1-3 — 무기 발현'},{type:'weaponUnlock',weapon:'불완전한 한손검'},
  {type:'trainingMap',unlocked:4},{type:'city',speaker:'하루',text:'이제 그 검을 실제로 움직여볼 차례예요.'},{type:'city',speaker:state=>state.playerName,text:'아직 손안에서 계속 흔들리는데.'},{type:'city',speaker:'하루',text:'그래서 휘둘러봐야 해요.\n무기는 생각만으로 완성되지 않아요. 몸이 형태를 기억해야 합니다.'},{type:'city',text:'나는 불안정하게 흔들리는 검을 다시 쥐었다.\n이번에는 놓치지 않겠다는 듯 손에 힘을 주었다.'},{type:'black',text:'1-4 — 한손검 훈련'},{type:'swordTrainingBattle'},{type:'weaponUpgrade'},{type:'city',speaker:'하루',text:'좋아요. 이제 검이 당신의 움직임을 따라오기 시작했어요.'},{type:'city',speaker:state=>state.playerName,text:'아까보다 훨씬 선명해졌어.'},{type:'city',speaker:'하루',text:'아직 완성은 아니지만, 적어도 전투 중에 사라지지는 않을 거예요.'},
  {type:'trainingMap',unlocked:5},{type:'city',speaker:'하루',text:'모모 씨. 한 번 더 해볼까요?'},{type:'city',speaker:'모모',text:'……또?'},{type:'city',speaker:'하루',text:'이번에는 능력을 막지 않을게요.\n대신 숨기 위해서가 아니라, 공격을 피하고 다시 움직이기 위해 사용하세요.'},{type:'city',speaker:'모모',text:'내가……그렇게 할 수 있을까?'},{type:'city',speaker:state=>state.playerName,text:'아까도 끝까지 버텼잖아.'},{type:'city',text:'모모가 나를 바라봤다.\n잠시 망설이던 눈빛이 아주 조금 가라앉았다.'},{type:'city',speaker:'모모',text:'……해볼게.'},{type:'black',text:'1-5 — 모모의 재도전'},{type:'momoRetryBattle'},{type:'autoUnlock'},{type:'city',speaker:'하루',text:'이번에는 달랐어요.\n사라진 뒤에도 다시 돌아와 상대를 보고 움직였으니까요.'},{type:'city',speaker:'모모',text:'……조금은, 덜 무서웠어.'}
];
