window.CHAPTER_3=[
  {opening:true,chapter:3,title:'낯선 동침자'},
  {type:'sleep',text:'……아침인가.'},
  {type:'lodging',text:'희미한 아침빛이 작은 창문 사이로 스며들고 있었다.\n나는 무거운 눈꺼풀을 천천히 들어 올렸다.'},
  {type:'lodging',text:'몸을 일으키려던 순간, 바로 옆에서 작고 규칙적인 숨소리가 들렸다.'},
  {type:'black',text:'……응?'},
  {type:'lodging',text:'나는 움직임을 멈춘 채 천천히 고개를 돌렸다.'},
  {type:'momo-service'},
  {type:'black',text:'……뭐야.\n\n누구야, 이 여자?!'},
  {type:'momo-awake',speaker:'???',text:'……잘 잤어?'},
  {type:'lodging',speaker:state=>state.playerName,text:'자, 잠깐만요.\n누구세요? 그리고 왜 제 옆에서 자고 있는 겁니까?'},
  {type:'lodging',text:'나는 황급히 침대 끝으로 물러났다.\n잠이 단숨에 달아났다.'},
  {type:'lodging',speaker:'???',text:'응? 여기 빈방 아니었어?'},
  {type:'lodging',speaker:state=>state.playerName,text:'제가 자고 있었는데 어떻게 빈방입니까!'},
  {type:'lodging',text:'소녀는 그제야 방 안을 천천히 둘러보았다.\n그러고는 아무렇지도 않게 고개를 끄덕였다.'},
  {type:'lodging',speaker:'???',text:'그렇네. 안 비었었네.'},
  {type:'black',text:'……이걸 이제 알았다고?'},
  {type:'lodging',speaker:'???',text:'어젯밤 임무가 늦게 끝났거든.\n너무 피곤해서 빈방인 줄 알고 그냥 들어와 잤어.'},
  {type:'lodging',speaker:'???',text:'아, 나는 모모야.\n너는?'},
  {type:'lodging',speaker:state=>state.playerName,text:'……'+state.playerName+'입니다.'},
  {type:'lodging',speaker:'모모',text:'응. 잘 부탁해.'},
  {type:'black',text:'잘 부탁할 상황은 아닌 것 같은데…….'},
  {type:'lodging',text:'나는 더 따져 묻고 싶었지만, 어젯밤 세운 계획이 떠올랐다.\n우선 길드로 가서 내가 할 수 있는 일을 찾아야 했다.'},
  {type:'lodging',speaker:state=>state.playerName,text:'저는 길드에 가봐야 합니다.'},
  {type:'lodging',speaker:'모모',text:'길드? 나도 갈래.'},
  {type:'lodging',speaker:state=>state.playerName,text:'……왜요?'},
  {type:'lodging',speaker:'모모',text:'나도 길드 소속이니까.\n그리고 혼자 가는 것보다 같이 가는 게 좋잖아.'},
  {type:'lodging',text:'모모는 이미 따라나설 준비를 마친 얼굴이었다.\n거절할 틈조차 주지 않을 생각인 듯했다.'},
  {type:'black',text:'……아침부터 정신이 하나도 없군.'},
  {type:'lodging-front',text:'나는 숙소 문을 열고 밖으로 나섰다.\n모모는 당연하다는 듯 바로 뒤를 따라왔다.'},
  {type:'lodging-front',text:'그렇게 나는 정체를 알 수 없는 소녀와 함께 길드로 향했다.'}
];
