window.CHAPTER_4=[
  {opening:true,chapter:4,title:'첫 번째 성장'},
  {type:'guild',text:'외곽에서 돌아온 우리는 곧장 길드로 향했다.\n하루는 길드 안으로 들어서자마자 곧바로 길드장을 향해 걸어갔다.'},
  {type:'guild',speaker:'하루',text:'길드장님.'},
  {type:'guild',speaker:'길드장',text:'어, 왔냐.'},
  {type:'guild',speaker:'하루',text:'F등급 헌터 둘을 외곽으로 보내셨어요?'},
  {type:'guild',speaker:'길드장',text:'뭐, 잘 돌아왔잖아.'},
  {type:'guild',speaker:'하루',text:'제가 조금만 늦었으면 못 돌아왔을 수도 있어요.'},
  {type:'guild',speaker:'길드장',text:'그래서 네가 데려왔잖아.'},
  {type:'guild',speaker:'하루',text:'그게 무슨 말이에요?'},
  {type:'guild',text:'길드장이 턱짓으로 나를 가리켰다.'},
  {type:'guild',speaker:'길드장',text:'저 녀석 말이야.\n처음 이 도시에 데려온 건 너잖아.'},
  {type:'guild',speaker:'하루',text:'헌터로 등록시킨 건 길드장님이잖아요.'},
  {type:'guild',speaker:'길드장',text:'그건 잔심부름 좀 시키려고 그런 거고.'},
  {type:'guild',speaker:'하루',text:'그런 사람을 외곽으로 보내요?'},
  {type:'guild',text:'잠시 말이 막힌 길드장이 슬쩍 시선을 피했다.'},
  {type:'guild',speaker:'길드장',text:'……아무튼.'},
  {type:'guild',speaker:'하루',text:'아무튼이요?'},
  {type:'guild',speaker:'길드장',text:'네가 데려왔으니 네가 책임져.'},
  {type:'guild',speaker:'하루',text:'잠깐만요. 그게 무슨 논리예요?'},
  {type:'guild',speaker:'길드장',text:'난 바쁘다.'},
  {type:'guild',speaker:'하루',text:'길드장님.'},
  {type:'guild',speaker:'길드장',text:'둘 다 잘 부탁한다.'},
  {type:'guild',speaker:'하루',text:'길드장님!'},
  {type:'guild',text:'길드장은 더 붙잡히기 전에 슬쩍 자리를 피해버렸다.\n하루는 멀어지는 길드장의 뒷모습을 어이없다는 듯 바라봤다.'},
  {type:'guild',text:'그리고 천천히 뒤를 돌아봤다.\n온몸이 지쳐 있는 나와, 그 옆에서 고개를 푹 숙이고 있는 모모가 서 있었다.'},
  {type:'guild',speaker:'하루',text:'……하아.'},
  {type:'guild',speaker:'하루',text:'그래서, 두 분은 어떻게 하고 싶으세요?'},
  {type:'guild',speaker:'모모',text:'난…….'},
  {type:'guild',text:'모모는 입을 열었지만, 그다음 말은 쉽게 나오지 않았다.'},
  {type:'guild',speaker:state=>state.playerName,text:'강해지고 싶어.'},
  {type:'guild',text:'하루의 시선이 내게 향했다.'},
  {type:'guild',speaker:state=>state.playerName,text:'오늘처럼 아무것도 못 한 채 끝내고 싶지는 않아.'},
  {type:'guild',text:'잠시 침묵이 흘렀다.'},
  {type:'guild',speaker:'모모',text:'……나도.'},
  {type:'guild',text:'모모는 여전히 고개를 숙이고 있었다.'},
  {type:'guild',speaker:'하루',text:'정말 괜찮겠어요?'},
  {type:'guild',text:'모모는 바로 대답하지 못했다.\n하지만 이번에는 도망치지 않고, 아주 작게 고개를 끄덕였다.'},
  {type:'guild',speaker:'하루',text:'알겠어요.'},
  {type:'guild',speaker:'하루',text:'오늘은 푹 쉬세요.\n내일 아침, 훈련장으로 오세요.'},
  {type:'guild',text:'하루는 나와 모모를 번갈아 바라봤다.'},
  {type:'guild',speaker:'하루',text:'제가 직접 훈련시키겠습니다.'},
  {type:'black',text:'그렇게 길고 긴 하루가 끝났다.\n\n이 세계에서 살아남으려면, 오늘보다 강해져야 한다.\n다시는 아무것도 하지 못한 채 누군가를 기다리고 싶지 않았다.'},
  {type:'black',text:'다음 날 — 훈련장'},
  {type:'mainLobby',speaker:'하루',text:'훈련 센터는 헌터 지구 안쪽에 있어요.\n헌터 지구로 이동하세요.',destination:'village',missionTitle:'CHAPTER 4 · 첫 번째 성장',missionGoal:'헌터 지구의 훈련 센터로 이동하세요.',missionProgress:10},
  {type:'city',text:'헌터 지구에는 훈련 센터와 장비 정비소를 비롯해 헌터들이 이용하는 여러 시설이 모여 있었다.\n나는 하루와 모모를 따라 안쪽으로 들어갔다.'},
  {type:'hunterDistrict'},
  {type:'trainingMap'},
  {type:'city',speaker:'하루',text:'먼저 가장 기본적인 공격부터 확인할게요.\n복잡하게 생각하지 말고, 제 움직임을 보고 들어오세요.'},
  {type:'city',speaker:state=>state.playerName,text:'하루 씨를 상대로요?'},
  {type:'city',speaker:'하루',text:'훈련이니까 괜찮아요.\n제가 멈추라고 할 때까지 계속하세요.'},
  {type:'black',text:'1-1 — 기초 공격 훈련'},
  {type:'trainingBattle'},
  {type:'speedUnlock'},
  {type:'city',speaker:'하루',text:'처음치고는 나쁘지 않았어요.\n이제 전투 흐름을 조금 더 빠르게 확인할 수 있을 거예요.'}
];
