window.CHAPTER_2=[
{type:'chapter2'},
{type:'city',text:'중앙도시 안쪽으로 들어서자 숲과는 전혀 다른 풍경이 펼쳐졌다.\n넓게 뻗은 거리와 그 사이를 가득 메운 건물들이 시야 끝까지 이어져 있었다.'},
{type:'city',text:'빛이 흐르는 표지판 아래로 사람들이 끊임없이 오갔다.\n가게 문이 열릴 때마다 말소리와 음식 냄새가 거리로 흘러나왔다.'},
{type:'city',text:'처음 보는 곳인데도 도시는 멈추지 않았다.\n누군가는 목적지를 향해 서둘렀고, 누군가는 길가에 서서 동료를 기다리고 있었다.'},
{type:'mainLobby',speaker:'하루',text:'우선 길드부터 가봐요.\n이곳 사람이라면 뭔가 기록이 남아 있을지도 몰라요.\n저도 임무 완료 보고를 해야 하니까, 어차피 가야 하거든요.'},
{type:'city',text:'하루를 따라 도시 중심부를 향해 걸었다.\n조금 전에는 보이지 않던 것들이 하나둘 눈에 들어오기 시작했다.'},
{type:'city',text:'허리에 검을 찬 남자. 등에 거대한 창을 멘 여자.\n처음 보는 형태의 무기를 손질하며 길가에 앉아 있는 사람들까지.'},
{type:'city',text:'그들 대부분은 혼자가 아니었다.\n두 명, 세 명, 때로는 네 명씩 무리를 이루어 같은 방향으로 움직이고 있었다.'},
{type:'city',text:'한쪽에서는 지도를 펼쳐 경로를 확인했고, 다른 쪽에서는 서로의 장비를 점검했다.\n출발을 앞둔 파티와 임무를 마치고 돌아온 파티가 거리 위에서 엇갈렸다.'},
{type:'city',speaker:s=>s.playerName,text:'저 사람들은……?'},
{type:'city',speaker:'하루',text:'임무를 나가는 사람들이에요.\n악몽은 혼자 상대하기 어려우니까 대부분 파티를 꾸려서 움직여요.'},
{type:'city',text:'조금 더 걷자 온몸에 상처를 입은 채 동료의 부축을 받으며 돌아오는 사람들도 보였다.'},
{type:'city',text:'웃으며 이야기하는 사람들 사이로, 누군가의 이름이 적힌 작은 꽃다발을 들고 조용히 걷는 사람도 지나갔다.'},
{type:'city',text:'나는 그 모습을 잠시 바라봤다.\n하루는 설명하지 않았고, 나도 묻지 않았다.'},
{type:'city',text:'도시의 중심으로 가까워질수록 사람들의 흐름은 한 건물을 향해 모여들었다.\n수많은 사람이 끊임없이 드나드는 거대한 건물이었다.'},
{type:'city',text:'건물 정면에는 단 하나의 글자가 크게 새겨져 있었다.\n\nGUILD'},
{type:'city',speaker:'하루',text:'여기가 길드예요.'},
{type:'guild',text:'문이 열렸다.\n순간, 도시의 소음과는 전혀 다른 활기가 밀려왔다.'},
{type:'guild',text:'넓은 홀. 벽을 가득 채운 수많은 임무 게시판.\n접수대 앞에 줄을 선 사람들.'},
{type:'guild',text:'테이블 위에 지도를 펼쳐놓고 작전을 논의하는 파티.\n새로운 동료를 찾으며 서로의 장비와 등급을 확인하는 사람들.'},
{type:'guild',text:'임무를 마치고 돌아온 이들은 접수대에 증표와 보고서를 제출하고 있었다.'},
{type:'guild',text:'이 건물은 단순히 사람들이 모이는 장소가 아니었다.\n이 도시의 모든 것이 이곳을 중심으로 움직이고 있었다.'},
{type:'guild',speaker:'하루',text:'뭐 하세요?\n이쪽이에요.'},
{type:'guild',text:'나는 다시 하루를 따라 걸었다.\n내가 누구인지 알고 싶다면— 아마 이곳에서부터 시작해야 한다.'},
{type:'guild',text:'하루를 따라 접수대로 향했다.\n여러 명의 직원이 쉴 새 없이 사람들을 응대하고 있었다.'},
{type:'guild',text:'임무서를 제출하는 사람. 새로운 의뢰를 확인하는 사람.\n동료의 이름을 대며 무언가를 묻는 사람까지.'},
{type:'guild',speaker:'안내원',text:'하루 님?'},{type:'guild',speaker:'하루',text:'아, 안녕하세요.'},{type:'guild',speaker:'안내원',text:'무사히 돌아오셨네요. 임무는요?'},{type:'guild',speaker:'하루',text:'끝났어요. 완료 보고하러 왔어요.'},
{type:'guild',text:'하루는 품에서 작은 패를 꺼내 건넸다.\n안내원이 그것을 접수대 위 장치에 올려놓자 희미한 빛이 퍼졌다.'},
{type:'guildMission',text:'GUILD RECORD\n\n임무 완료 확인\n악몽 토벌 완료\n\n기록 승인 ✓'},
{type:'guild',text:'악몽.\n분명 처음 듣는 말이어야 했다.\n그런데 그 단어를 보는 순간 머릿속 어딘가가 희미하게 흔들렸다.'},
{type:'guild',text:'잡힐 듯하면서도 잡히지 않는 감각.\n나는 무심코 미간을 찌푸렸다.'},
{type:'guild',speaker:'안내원',text:'그런데…… 이분은?'},
{type:'guild',speaker:'하루',text:'저도 잘 몰라요.\n임무에서 돌아오는 길에 만났어요.\n이름 말고는 아무것도 기억하지 못해요.'},
{type:'guild',speaker:'안내원',text:'기억상실인가요?'},{type:'guild',speaker:s=>s.playerName,text:'아마도요.'},{type:'guild',speaker:'안내원',text:'이름은 기억하시고요?'},
{type:'guild',dynamic:s=>`${s.playerName}.\n\n내가 이름을 말하자 안내원은 곧바로 앞에 놓인 장치를 조작하기 시작했다.`},
{type:'guild',speaker:'안내원',text:'잠시만 기다려주세요.'},{type:'guild',text:'화면 위로 수많은 정보가 빠르게 지나갔다.\n그리고 잠시 후, 안내원의 손이 멈췄다.'},
{type:'guild',speaker:'안내원',text:'……어라?'},{type:'guild',speaker:'하루',text:'왜요?'},{type:'noRecord',text:'SEARCH COMPLETE\n\nNO RECORD\n\n등록된 정보가 없습니다.'},
{type:'guild',speaker:s=>s.playerName,text:'없는 건가요?'},{type:'guild',speaker:'안내원',text:'네. 적어도 길드 기록에는요.'},{type:'guild',speaker:'하루',text:'그럴 수도 있어요?'},
{type:'guild',speaker:'안내원',text:'이름을 바꿨거나 등록 정보에 오류가 생겼을 가능성은 있어요. 하지만……\n정말 아무것도 기억나지 않으세요?'},
{type:'guild',speaker:s=>s.playerName,text:'네.'},{type:'guild',speaker:'안내원',text:'그럼 지금 머물 곳은 있으세요?'},{type:'guild',speaker:'안내원',text:'돈은요?'},{type:'guild',speaker:'안내원',text:'소지품이나 신분을 증명할 만한 것은요?'},
{type:'guild',text:'나는 천천히 고개를 저었다.\n안내원은 난처한 표정으로 하루를 바라봤다. 하루도 나를 바라봤다.'},
{type:'black',text:'나는 기억만 없는 게 아니었다.\n\n집도 없다.\n돈도 없다.\n신분도 없다.\n\n말 그대로—\n\n아무것도 없었다.'},
{type:'guild',speaker:'안내원',text:'……오늘 하루 정도라면 임시 숙소를 이용하실 수 있어요.'},
{type:'guild',speaker:s=>s.playerName,text:'임시 숙소요?'},
{type:'guild',speaker:'안내원',text:'임무를 마치고 늦게 돌아온 헌터나, 부상 때문에 바로 귀가하기 어려운 분들을 위한 곳이에요.\n오래 머물 수는 없지만 오늘 밤까지는 괜찮아요.'},
{type:'guild',text:'안내원은 말을 마친 뒤 하루를 바라봤다.'},
{type:'guild',speaker:'안내원',text:'하루 님. 숙소 위치까지 안내해 주실 수 있을까요?'},
{type:'guild',text:'하루는 잠시 나를 바라봤다.\n곤란하다는 기색보다는, 이대로 혼자 두기는 조금 마음에 걸린다는 표정에 가까웠다.'},
{type:'guild',speaker:'하루',text:'……네. 그 정도라면 괜찮아요.'},
{type:'guild',speaker:'하루',text:'길도 복잡하니까 제가 데려다드릴게요.'}
];