window.CHAPTER_1=[
{type:'chapter',opening:true,chapter:1,title:'낯선 숲'},
{type:'black',text:'……여기는 어디지?'},{type:'black',text:'아니.\n그보다 먼저—'},{type:'black',text:'나는 누구지?'},{type:'name'},
{type:'black',dynamic:s=>`그래.\n내 이름은 ${s.playerName}.`},{type:'black',text:'그것만은 기억난다.\n그런데 왜 여기 있는지는…… 모르겠다.'},
{type:'forest',text:'눈을 뜨자 가장 먼저 빛이 보였다.\n푸른빛이 높은 나뭇잎 사이를 비집고 내려와 숲바닥에 조각조각 흩어져 있었다.'},
{type:'forest',text:'천천히 몸을 일으켰다.\n축축한 흙냄새. 서늘한 바람. 이름 모를 꽃들이 발목 높이에서 흔들렸다.'},
{type:'forest',text:'나무는 하늘을 가릴 만큼 높았다.\n잎 끝에는 작은 빛들이 맺혀 있었고, 바람이 불 때마다 허공으로 흩어졌다.'},
{type:'forest',text:'아름답다.\n그런데 너무 조용했다.'},{type:'forest',text:'새소리도 없고, 벌레 우는 소리도 없다.\n내 발이 풀잎을 밟는 소리만 따라왔다.'},
{type:'forest',text:'가만히 있을 수는 없었다.\n일단 이 숲을 벗어나기로 했다.'},{type:'forest',text:'얼마나 걸었을까.\n앞쪽 덤불에서 바스락거리는 소리가 났다.'},
{type:'danger',text:'걸음을 멈췄다.\n검은 무언가가 나무 뒤에서 천천히 몸을 드러냈다.'},{type:'danger',text:'짐승처럼 네 발로 서 있었지만, 짐승이라고 하기엔 이상했다.\n몸의 윤곽은 연기처럼 계속 흔들리고 있었다.'},
{type:'danger',text:'급히 주변을 둘러봤다.\n돌멩이 몇 개와 젖은 나뭇가지뿐. 손에 쥘 만한 건 아무것도 없었다.'},{type:'black',text:'……도망쳐야 한다.'},
{type:'danger',text:'뒤돌아 달렸다.\n나뭇가지가 얼굴을 스쳤고, 바로 뒤에서 거친 숨소리가 따라붙었다.'},{type:'danger',text:'점점 가까워진다.\n뒤를 돌아볼 여유도 없었다.'},
{type:'forest',text:'그 순간, 누군가 내 손목을 거칠게 잡아당겼다.'},{type:'forest',text:'몸이 옆으로 휘청였다.\n검은 발톱이 방금까지 내가 있던 자리를 찢고 지나갔다.'},
{type:'forest',speaker:'???',text:'가만히 계세요.'},{type:'forest',text:'처음 보는 소녀였다.\n나를 등 뒤로 밀어낸 그녀가 한 손을 들어 올렸다.'},
{type:'forest',text:'푸른빛이 손끝에 모이더니 활의 형태를 만들었다.\n시위를 당기자 빛으로 된 화살이 조용히 나타났다.'},
{type:'battle'},
{type:'reward',exp:35},
{type:'black',text:'위험해.'},{type:'danger',text:'검은 생명체가 마지막 힘을 짜내듯 소녀에게 달려들었다.\n생각할 틈도 없이 몸이 먼저 움직였다.'},
{type:'danger',text:'주먹을 꽉 쥐고 놈의 옆구리를 있는 힘껏 내질렀다.\n주먹이 닿은 순간, 검은 몸이 안쪽부터 갈라지며 무너져 내렸다.'},
{type:'forest',text:'순간, 숲이 조용해졌다.\n나는 천천히 주먹을 내려다봤다.'},{type:'forest',text:'소녀도 쓰러진 생명체와 나를 번갈아 바라보고 있었다.\n아무 말도 하지 못한 채.'},
{type:'forest',speaker:'???',text:'……방금, 뭘 하신 거예요?'},{type:'forest',speaker:s=>s.playerName,text:'저도…… 모르겠습니다.'},
{type:'forest',speaker:'???',text:'맨손으로 잡으셨잖아요.'},{type:'forest',speaker:s=>s.playerName,text:'그냥 달려들길래…… 저도 모르게.'},
{type:'forest',text:'검은 안개가 흩어진 자리에 작은 결정 하나가 떨어졌다.\n검붉은빛이 결정 안쪽에서 희미하게 일렁였다.'},
{type:'forest',speaker:'???',text:'악몽의 정수네요.'},{type:'forest',speaker:s=>s.playerName,text:'악몽……이요?'},
{type:'forest',speaker:'???',text:'아까 그 괴물 말이에요.\n그런데 정말 아무것도 모르세요?'},{type:'forest',speaker:s=>s.playerName,text:'네. 이름 말고는 기억나는 게 없습니다.'},
{type:'forest',speaker:'???',text:'……그렇군요.'},{type:'forest',speaker:'하루',text:'저는 하루예요.\n임무를 마치고 돌아가던 중이었어요.'},
{type:'forest',speaker:'하루',text:'일단 같이 가요.\n이 숲에 혼자 계시는 건 위험해요.'},{type:'forest',speaker:s=>s.playerName,text:'도와주셔서 감사합니다.\n부탁드리겠습니다.'},
{type:'black',text:'그렇게 나는 하루를 따라 숲을 나섰다.'},{type:'forest',text:'얼마쯤 걸었을까.\n빽빽하던 나무 사이로 조금씩 하늘이 보이기 시작했다.'},
{type:'forest',text:'숲의 끝을 지나자 바람의 냄새가 달라졌다.\n그리고 멀리, 거대한 도시의 외벽이 모습을 드러냈다.'},
{type:'city',text:'높은 외벽 너머로 수많은 건물과 불빛이 보였다.\n도시 바깥쪽에서는 무기를 든 헌터들이 외곽을 순찰하고 있었다.'},
{type:'gate',text:'입구에 가까워지자 경계 중이던 두 헌터가 우리 쪽을 돌아봤다.\n그중 한 명이 하루를 알아보고 먼저 손을 들었다.'},
{type:'gate',speaker:'헌터 1',text:'하루 씨. 오늘은 좀 늦으셨네요.'},{type:'gate',speaker:'하루',text:'네. 돌아오는 길에 일이 좀 있었어요.'},
{type:'gate',speaker:'헌터 2',text:'옆에 계신 분 때문에요?'},{type:'gate',speaker:'하루',text:'네. 자세한 건 들어가서 얘기할게요.'},
{type:'gate',speaker:'헌터 1',text:'알겠습니다. 고생하셨어요.'},{type:'gate',speaker:'하루',text:'두 분도 수고하세요.'},
{type:'city',text:'하루와 함께 입구를 지나 도시 안으로 들어섰다.\n숲과는 전혀 다른 소리와 빛이 한꺼번에 밀려왔다.'},
{type:'chapter',clear:true,chapter:1},{type:'levelup'}
];