export const chapter013 = {
  id: 13,
  title: '남은 흔적',
  scenes: [
    { id: 'c13-title', mode: 'black', center: 'CHAPTER 13\n\n남은 흔적' },
    { id: 'c13-next-morning', mode: 'room', narration: true, text: '다음 날 아침, 세나는 약속한 대로 주인공의 상처를 확인하러 숙소를 찾았다.' },
    { id: 'c13-check-alone', mode: 'room', narration: true, text: '하루와 모모도 함께였다. 전날 헤어진 뒤 다시 만났지만 네 사람 사이에는 전보다 자연스러운 공기가 남아 있었다.' },
    { id: 'c13-knock', mode: 'room', speaker: '세나', text: '잠깐만 볼게요. 많이 아프지는 않죠?' },
    { id: 'c13-sena-greet', mode: 'room', speaker: '주인공', text: '네. 움직일 때 조금 당기는 정도예요.' },
    { id: 'c13-mc-fine', mode: 'room', narration: true, text: '세나는 붕대를 천천히 풀고 상처 주변을 가볍게 눌러 보았다.' },
    { id: 'c13-sena-sit', mode: 'room', speaker: '세나', text: '상처는 거의 다 아물었네요.' },
    { id: 'c13-bandage-open', mode: 'room', narration: true, text: '안도한 듯 말하던 세나의 손이 잠시 멈췄다.' },
    { id: 'c13-sena-silence', mode: 'room', speaker: '세나', text: '……이상하네요.' },
    { id: 'c13-mc-question', mode: 'room', speaker: '주인공', text: '문제가 있는 건가요?' },
    { id: 'c13-sena-look-close', mode: 'room', speaker: '세나', text: '문제라기보다는 회복된 방식이 조금 달라요.' },
    { id: 'c13-no-response', mode: 'room', narration: true, text: '세나는 손끝에 옅은 빛을 모아 상처 가까이에 대 보았다. 빛은 피부 위에서 잠시 머물다 사라졌다.' },
    { id: 'c13-sena-line', mode: 'room', speaker: '세나', text: '보통은 정신에너지로 회복한 흔적이 남는데, 이 상처는 시간이 지나면서 자연스럽게 아문 것 같아요.' },
    { id: 'c13-mc-what', mode: 'room', speaker: '주인공', text: '그런 경우는 드문가요?' },
    { id: 'c13-sena-explain', mode: 'room', speaker: '세나', text: '저는 처음 봐요. 그래도 지금 상태는 괜찮아요. 상처도 잘 붙었고 열도 없어요.' },
    { id: 'c13-mc-days', mode: 'room', speaker: '하루', text: '회복된 결과는 같은데 과정만 달랐다는 거네요.' },
    { id: 'c13-sena-nod', mode: 'room', speaker: '세나', text: '네. 당장 걱정할 정도는 아니에요.' },
    { id: 'c13-sena-normal', mode: 'room', speaker: '모모', text: '처음 보는 경우네요. 아프지 않다면 다행이지만요.' },
    { id: 'c13-mc-body', mode: 'room', speaker: '주인공', text: '저도 별다른 이상은 느끼지 못했어요.' },
    { id: 'c13-sena-uncertain', mode: 'room', narration: true, text: '세나는 새 붕대를 얇게 감고 매듭을 정리했다. 이전처럼 조심스러운 손길이었지만 표정은 한결 편안했다.' },
    { id: 'c13-door-open', mode: 'room', speaker: '세나', text: '이제 치료는 여기까지 해도 되겠어요. 며칠만 무리하지 마세요.' },
    { id: 'c13-haru-enter', mode: 'room', speaker: '주인공', text: '그동안 고마웠어요.' },
    { id: 'c13-momo-worry', mode: 'room', speaker: '세나', text: '다치지 않는 게 가장 좋지만, 또 다치면 바로 찾아와요.' },
    { id: 'c13-sena-call-in', mode: 'room', speaker: '하루', text: '그 말은 훈련을 쉬라는 뜻이기도 해요.' },
    { id: 'c13-haru-see', mode: 'room', speaker: '주인공', text: '알겠어요. 오늘은 가볍게 할게요.' },
    { id: 'c13-haru-question', mode: 'room', speaker: '모모', text: '오늘도 하는 건가요……?' },
    { id: 'c13-sena-confirm', mode: 'room', narration: true, text: '잠시 정적이 흐른 뒤 하루가 작게 한숨을 쉬었다. 세나는 웃었고, 모모도 뒤늦게 따라 웃었다.' },
    { id: 'c13-momo-ask', mode: 'room', speaker: '하루', text: '가볍게라는 말, 이번에는 믿어 볼게요.' },
    { id: 'c13-haru-deny', mode: 'room', speaker: '주인공', text: '네. 약속할게요.' },
    { id: 'c13-sena-add', mode: 'room', narration: true, text: '상처에 대한 이야기는 그렇게 마무리됐다. 세나는 치료 도구를 가방에 넣었고, 모모는 풀어 둔 천을 정리했다.' },
    { id: 'c13-momo-fear', mode: 'room', narration: true, text: '그때 복도에서 빠른 발소리가 들리더니 문 앞에 길드 직원이 모습을 드러냈다.' },
    { id: 'c13-mc-calm', mode: 'room', speaker: '길드 직원', text: '여기 계셨군요. 찾고 있었습니다.' },
    { id: 'c13-sena-firm', mode: 'room', speaker: '하루', text: '무슨 일인가요?' },
    { id: 'c13-haru-decide', mode: 'room', speaker: '길드 직원', text: '길드장님께서 네 분 모두를 부르셨습니다.' },
    { id: 'c13-mc-hesitate', mode: 'room', speaker: '세나', text: '네 명 전부요?' },
    { id: 'c13-choice', mode: 'room', speaker: '주인공', text: '직원은 곧바로 고개를 끄덕였다.', choices: [
      { id: 'c13-report-now', label: '바로 길드로 향한다.', reply: '알겠어요. 바로 가겠습니다.', trust: { haru: 1, sena: 1, momo: 1 }, traits: { cautious: 1 } },
      { id: 'c13-ask-sena', label: '세 사람과 함께 움직인다.', reply: '그럼 같이 가죠. 준비되는 대로 출발해요.', affection: { haru: 1, sena: 1, momo: 1 }, trust: { sena: 1 } },
      { id: 'c13-reassure-team', label: '호출 이유를 묻는다.', reply: '혹시 무슨 일인지 들으셨나요?', trust: { haru: 1, sena: 1, momo: 1 }, traits: { cautious: 1 } }
    ] },
    { id: 'c13-bandage-new', mode: 'room', speaker: '길드 직원', text: '자세한 내용은 길드장님께서 직접 설명하실 겁니다.' },
    { id: 'c13-momo-help', mode: 'room', narration: true, text: '네 사람은 더 묻지 않고 자리에서 일어났다. 세나는 가방을 챙겼고, 하루는 먼저 문을 열었다.' },
    { id: 'c13-mc-thanks', mode: 'city', narration: true, text: '숙소를 나서자 아침의 거리가 밝게 펼쳐졌다. 전날 함께 걸었던 길이었지만 오늘은 목적지가 분명했다.' },
    { id: 'c13-leave-room', mode: 'city', speaker: '모모', text: '갑자기 네 명을 다 부르신 이유가 뭘까요?' },
    { id: 'c13-city-normal', mode: 'city', speaker: '하루', text: '가 보면 알겠죠. 급한 일이라면 직원이 더 서둘렀을 거예요.' },
    { id: 'c13-haru-slow', mode: 'city', speaker: '세나', text: '일단 너무 걱정하지 말고 가요.' },
    { id: 'c13-mc-notice', mode: 'city', speaker: '주인공', text: '네. 이번에는 네 명이 같이 들을 이야기인 것 같네요.' },
    { id: 'c13-haru-answer', mode: 'guild', narration: true, text: '길드에 도착하자 직원은 기다리고 있었다. 그는 곧바로 길드장실 앞까지 네 사람을 안내했다.' },
    { id: 'c13-sena-answer2', mode: 'guild', speaker: '길드 직원', text: '들어가시면 됩니다. 길드장님이 기다리고 계십니다.' },
    { id: 'c13-momo-answer', mode: 'guildmaster', narration: true, text: '문이 열리고 네 사람이 차례로 안으로 들어갔다. 책상 위에는 낯선 지역이 표시된 지도가 펼쳐져 있었다.' },
    { id: 'c13-guild-arrive', mode: 'guildmaster', speaker: '길드장', text: '왔군. 네 사람에게 맡길 일이 있다.' },
    { id: 'c13-reception', mode: 'guildmaster', narration: true, text: '길드장의 손끝이 지도 위의 한 지점을 짚었다.' },
    { id: 'c13-sena-report', mode: 'black', center: 'CHAPTER 13 CLEAR' },
    { id: 'c13-reception-serious', mode: 'black', ending: true, center: '새로운 사건이 네 사람을 기다리고 있었다.' }
  ]
};