export const chapter014 = {
  id: 14,
  title: '첫 번째 네 사람',
  scenes: [
    { id: 'c14-title', mode: 'black', center: 'CHAPTER 14\n\n첫 번째 네 사람' },
    { id: 'c14-office-silence', mode: 'guildmaster', narration: true, text: '길드장은 네 사람이 자리에 앉는 것을 기다린 뒤 지도 위의 표시를 손끝으로 두드렸다.' },
    { id: 'c14-guildmaster-question', mode: 'guildmaster', speaker: '길드장', text: '동부 호송로 외곽에서 이상한 보고가 연달아 들어왔다.' },
    { id: 'c14-sena-confirm', mode: 'guildmaster', speaker: '하루', text: '어떤 보고인가요?' },
    { id: 'c14-haru-add', mode: 'guildmaster', speaker: '길드장', text: '악몽이 나타났다는 보고와, 아무것도 없었다는 보고가 같은 시간대에 겹친다.' },
    { id: 'c14-guildmaster-mc', mode: 'guildmaster', speaker: '주인공', text: '같은 장소를 본 사람들이 서로 다른 말을 했다는 건가요?' },
    { id: 'c14-mc-answer', mode: 'guildmaster', speaker: '길드장', text: '그래. 흔적은 남아 있는데 목격한 모습이 전부 다르다.' },
    { id: 'c14-guildmaster-think', mode: 'guildmaster', narration: true, text: '길드장은 지도 옆에 놓인 보고서 몇 장을 펼쳤다. 발자국의 크기와 방향, 들었다는 소리까지 서로 맞지 않았다.' },
    { id: 'c14-guildmaster-record', mode: 'guildmaster', speaker: '세나', text: '착각이나 공포 때문에 다르게 본 건 아닐까요?' },
    { id: 'c14-mc-field', mode: 'guildmaster', speaker: '길드장', text: '그 가능성도 있다. 하지만 조사대 두 팀이 같은 구역에서 연락을 끊었다.' },
    { id: 'c14-guildmaster-yes', mode: 'guildmaster', speaker: '모모', text: '두 팀 모두요?' },
    { id: 'c14-map-open', mode: 'guildmaster', speaker: '길드장', text: '한 팀은 무사히 돌아왔지만 안에서 본 일을 제대로 설명하지 못했다. 다른 한 팀은 아직 복귀하지 않았다.' },
    { id: 'c14-guildmaster-marks', mode: 'guildmaster', narration: true, text: '방 안의 공기가 조금 무거워졌다. 모모는 보고서를 바라보다가 가방 끈을 고쳐 잡았다.' },
    { id: 'c14-sena-risk', mode: 'guildmaster', speaker: '하루', text: '목표는 실종된 조사대 확인인가요?' },
    { id: 'c14-guildmaster-agree', mode: 'guildmaster', speaker: '길드장', text: '우선은 현상 확인이다. 실종자를 발견하면 구조한다. 하지만 무리해서 안쪽으로 들어가지는 마라.' },
    { id: 'c14-four-look', mode: 'guildmaster', narration: true, text: '길드장의 시선이 네 사람을 차례로 훑었다.' },
    { id: 'c14-party-order', mode: 'guildmaster', speaker: '길드장', text: '이번 조사는 네 사람이 맡는다.' },
    { id: 'c14-momo-surprise', mode: 'guildmaster', speaker: '모모', text: '저도 함께 가는 건가요?' },
    { id: 'c14-guildmaster-momo', mode: 'guildmaster', speaker: '길드장', text: '시야가 믿을 수 없다면 먼저 움직임을 숨기고 확인할 사람이 필요하다. 네 은신이 적합하다.' },
    { id: 'c14-momo-straight', mode: 'guildmaster', narration: true, text: '모모는 잠시 놀란 표정을 지었지만 곧 허리를 바로 세웠다.' },
    { id: 'c14-momo-accept', mode: 'guildmaster', speaker: '모모', text: '알겠어요. 제가 먼저 확인할게요.' },
    { id: 'c14-haru-correct', mode: 'guildmaster', speaker: '하루', text: '혼자 깊이 들어가지는 마세요. 보이는 거리 안에서 움직여요.' },
    { id: 'c14-momo-nod', mode: 'guildmaster', speaker: '모모', text: '네. 바로 신호할게요.' },
    { id: 'c14-guildmaster-roles', mode: 'guildmaster', speaker: '길드장', text: '하루는 원거리 경계와 판단 보조. 세나는 치료와 결계. 모모는 정찰. {{playerName}}은 근접 대응을 맡아라.' },
    { id: 'c14-mc-role', mode: 'guildmaster', speaker: '주인공', text: '네 사람이 한 파티로 움직이는 건 처음이네요.' },
    { id: 'c14-guildmaster-warning', mode: 'guildmaster', speaker: '길드장', text: '그래서 더 단순하게 움직여라. 확인, 공유, 철수. 이상한 일이 생기면 혼자 판단하지 마라.' },
    { id: 'c14-sena-condition', mode: 'guildmaster', speaker: '세나', text: '누구든 상태가 달라지면 바로 말하는 걸로 해요.' },
    { id: 'c14-haru-condition', mode: 'guildmaster', speaker: '하루', text: '보이는 것보다 서로의 말을 먼저 믿는 편이 좋겠네요.' },
    { id: 'c14-choice', mode: 'guildmaster', speaker: '주인공', text: '세 사람은 이미 각자의 역할을 받아들이고 있었다.', choices: [
      { id: 'c14-trust-party', label: '세 사람을 믿고 의뢰를 받는다.', reply: '알겠어요. 세 분을 믿고 함께 가겠습니다.', affection: { haru: 1, sena: 1, momo: 1 }, trust: { haru: 2, sena: 2, momo: 2 } },
      { id: 'c14-promise-return', label: '네 명 모두 돌아오겠다고 말한다.', reply: '이번에는 네 명 모두 무사히 돌아와요.', affection: { haru: 1, sena: 1, momo: 2 }, traits: { brave: 1, considerate: 1 } },
      { id: 'c14-accept-role', label: '상황을 바로 공유하겠다고 약속한다.', reply: '이상한 점이 생기면 바로 말할게요. 혼자 판단하지 않겠습니다.', trust: { haru: 1, sena: 3, momo: 1 }, traits: { cautious: 1 } }
    ] },
    { id: 'c14-guildmaster-approval', mode: 'guildmaster', speaker: '길드장', text: '좋다. 출발은 오늘 오후다. 그전까지 장비와 보급을 갖춰라.' },
    { id: 'c14-mission-status', mode: 'status', center: '미확인 현상 조사\n\n조사 지역: 동부 호송로 외곽\n구성 인원: 4명\n목표: 현상 확인 및 실종자 수색' },
    { id: 'c14-leave-office', mode: 'guild', narration: true, text: '네 사람은 의뢰서를 들고 길드장실을 나왔다. 문이 닫히자 모모가 참았던 숨을 천천히 내쉬었다.' },
    { id: 'c14-momo-nervous', mode: 'guild', speaker: '모모', text: '정식 파티는 처음이에요. 제가 잘할 수 있을까요?' },
    { id: 'c14-sena-calm', mode: 'guild', speaker: '세나', text: '혼자 하는 일이 아니잖아요. 모르는 건 바로 말하면 돼요.' },
    { id: 'c14-haru-plan', mode: 'guild', speaker: '하루', text: '먼저 신호부터 정하죠. 현장에서 길게 이야기할 수 없을 수도 있으니까요.' },
    { id: 'c14-table', mode: 'guild', narration: true, text: '네 사람은 홀 구석의 빈 탁자에 지도를 펼쳤다. 하루가 이동 경로를 짚고 세나는 중간에 결계를 펼칠 장소를 골랐다.' },
    { id: 'c14-momo-route', mode: 'guild', speaker: '모모', text: '이 수풀 쪽은 몸을 숨기기 좋아요. 제가 먼저 보고 돌아오면 큰길에서 기다려 주세요.' },
    { id: 'c14-haru-praise', mode: 'guild', speaker: '하루', text: '좋아요. 대신 신호가 두 번 끊기면 바로 돌아오는 걸로 해요.' },
    { id: 'c14-momo-relief', mode: 'guild', narration: true, text: '모모의 의견이 곧바로 계획에 들어가자 굳어 있던 표정이 조금 풀렸다.' },
    { id: 'c14-sena-mc-rule', mode: 'guild', speaker: '세나', text: '{{playerName}} 씨는 앞에서 버티려고만 하지 말아요. 뒤로 물러나는 것도 역할이에요.' },
    { id: 'c14-mc-rule', mode: 'guild', speaker: '주인공', text: '알겠어요. 이번에는 먼저 말할게요.' },
    { id: 'c14-haru-add-rule', mode: 'guild', speaker: '하루', text: '저희도 같아요. 한 사람만 지키는 규칙이면 의미가 없으니까요.' },
    { id: 'c14-agree', mode: 'guild', narration: true, text: '세나와 모모가 고개를 끄덕였다. 네 사람 사이에 처음으로 같은 움직임과 같은 기준이 생겼다.' },
    { id: 'c14-prep-montage', mode: 'city', narration: true, text: '준비는 자연스럽게 나뉘었다. 하루는 지도와 에너지 결정을 확인했고, 세나는 치료 도구와 결계 매개체를 챙겼다.' },
    { id: 'c14-momo-supplies', mode: 'market', narration: true, text: '모모는 시장에서 식량과 물을 구했다. 전날 함께 걸었던 골목을 이번에는 망설이지 않고 앞장서 지나갔다.' },
    { id: 'c14-mc-gear', mode: 'shop', narration: true, text: '주인공은 장비점에서 임시 검의 손잡이를 다시 조정했다. 옆에서는 하루가 균형을 확인하며 몇 가지를 조언했다.' },
    { id: 'c14-meet-gate', mode: 'city-gate', narration: true, text: '오후가 되자 네 사람은 중앙도시 동문 앞에 다시 모였다. 외벽 너머로 길게 이어진 길은 조용했다.' },
    { id: 'c14-momo-food', mode: 'city-gate', speaker: '모모', text: '식량은 이틀분 준비했어요. 물도 조금 넉넉하게 챙겼고요.' },
    { id: 'c14-sena-check', mode: 'city-gate', speaker: '세나', text: '치료 도구도 준비됐어요. 결계는 오래 유지할 수 있게 나눠 뒀어요.' },
    { id: 'c14-haru-ready', mode: 'city-gate', speaker: '하루', text: '경로도 확인했어요. 바로 안쪽으로 가지 않고 바깥 흔적부터 볼게요.' },
    { id: 'c14-mc-ready', mode: 'city-gate', speaker: '주인공', text: '저도 준비됐어요.' },
    { id: 'c14-four-line', mode: 'city-gate', narration: true, text: '네 사람은 잠시 서로를 바라보았다. 어제까지 함께 거리를 걷던 네 사람이 오늘은 하나의 의뢰를 위해 같은 문 앞에 서 있었다.' },
    { id: 'c14-haru-lead', mode: 'city-gate', speaker: '하루', text: '출발하죠. 모모 씨가 앞을 확인하고, 나머지는 서로 보이는 거리를 유지해요.' },
    { id: 'c14-momo-first', mode: 'city-gate', speaker: '모모', text: '네. 너무 멀리 가지 않을게요.' },
    { id: 'c14-sena-smile', mode: 'city-gate', speaker: '세나', text: '그리고 네 명이 같이 돌아오는 거예요.' },
    { id: 'c14-mc-final', mode: 'city-gate', speaker: '주인공', text: '네. 함께 돌아와요.' },
    { id: 'c14-depart', mode: 'forest-exit', narration: true, text: '도시의 문이 열리고 모모가 먼저 길 위로 나섰다. 하루와 주인공이 뒤를 따르고, 세나는 마지막에서 모두의 상태를 살피며 걸음을 옮겼다.' },
    { id: 'c14-party-formed', mode: 'status', center: '정식 4인 파티 결성\n\n{{playerName}} · 하루 · 세나 · 모모' },
    { id: 'c14-road', mode: 'black', narration: true, text: '네 사람의 첫 번째 공동 의뢰가 시작되었다.' },
    { id: 'c14-clear', mode: 'black', center: 'CHAPTER 14 CLEAR' },
    { id: 'c14-end', mode: 'black', ending: true, center: '네 사람은 처음으로 하나의 파티가 되어 중앙도시를 떠났다.' }
  ]
};