export const chapter011 = {
  id: 11,
  title: '쉬어 가는 날',
  scenes: [
    { id: 'c11-title', mode: 'black', center: 'CHAPTER 11\n\n쉬어 가는 날' },
    { id: 'c11-days-later', mode: 'training', narration: true, text: '의뢰가 끝난 뒤 며칠이 지났다. 주인공은 평소와 다름없이 아침 훈련을 이어가고 있었다.' },
    { id: 'c11-repeat', mode: 'training', narration: true, text: '검을 구현해 자세를 잡고, 몇 번이고 같은 궤적을 그었다. 전보다 움직임은 안정됐지만 아직 만족할 수는 없었다.' },
    { id: 'c11-failure-memory', mode: 'training', narration: true, text: '다음에는 누군가가 자신을 지키게 만들고 싶지 않았다. 함께 움직이는 사람을 지킬 만큼 강해지는 것. 지금 훈련하는 이유는 그뿐이었다.' },
    { id: 'c11-swing', mode: 'training', speaker: '주인공', text: '한 번만 더.' },
    { id: 'c11-body-warning', mode: 'training', narration: true, text: '검을 다시 들어 올리려던 순간, 훈련소 입구에서 익숙한 목소리가 들렸다.' },
    { id: 'c11-haru-arrive', mode: 'training', speaker: '하루', text: '그 한 번이 벌써 몇 번째예요?' },
    { id: 'c11-haru-warning', mode: 'training', narration: true, text: '하루가 팔짱을 낀 채 서 있었다. 그 뒤로 세나와 모모도 함께 들어왔다.' },
    { id: 'c11-mc-surprise', mode: 'training', speaker: '주인공', text: '세 분이 같이 오셨네요. 무슨 일인가요?' },
    { id: 'c11-haru-look', mode: 'training', speaker: '하루', text: '별일은 아니고요. 오늘 하루만 훈련을 쉬게 하러 왔습니다.' },
    { id: 'c11-haru-answer', mode: 'training', speaker: '주인공', text: '제가 너무 오래 하고 있었나요?' },
    { id: 'c11-momo-peek', mode: 'training', speaker: '모모', text: '그 정도는 아닌데요. 그냥…… 가끔은 같이 쉬어도 좋을 것 같아서요.' },
    { id: 'c11-momo-line', mode: 'training', narration: true, text: '모모는 준비해 온 물병을 내밀었다. 주인공이 받아 들자 긴장이 조금 풀린 듯 어깨를 내렸다.' },
    { id: 'c11-mc-deny', mode: 'training', speaker: '주인공', text: '고마워요. 마침 오늘 훈련은 거의 끝났어요.' },
    { id: 'c11-sena-enter', mode: 'training', speaker: '세나', text: '잘됐네요. 그럼 이대로 끝내요.' },
    { id: 'c11-sena-arrive', mode: 'training', narration: true, text: '세나는 웃으며 주인공의 손과 자세를 가볍게 살폈다. 무리한 흔적이 없다는 것을 확인한 뒤에야 고개를 끄덕였다.' },
    { id: 'c11-mc-explain', mode: 'training', speaker: '주인공', text: '다음에는 제가 더 잘 지키고 싶어서요. 그래서 꾸준히 해 두려고 했어요.' },
    { id: 'c11-sena-close', mode: 'training', speaker: '세나', text: '그 마음은 알아요. 그래도 같이 시간을 보내는 것도 팀에 필요한 일이에요.' },
    { id: 'c11-sena-command', mode: 'training', speaker: '하루', text: '서로 어떻게 움직이는지만큼, 어떤 사람인지 아는 것도 중요하고요.' },
    { id: 'c11-mc-hesitate', mode: 'training', narration: true, text: '주인공은 손에 남아 있던 검을 바라보다가 천천히 거두었다.' },
    { id: 'c11-haru-support', mode: 'training', speaker: '주인공', text: '그렇다면 오늘은 쉬어도 괜찮겠네요.' },
    { id: 'c11-momo-small', mode: 'training', speaker: '모모', text: '정말요? 생각보다 빨리 받아들이셨네요.' },
    { id: 'c11-mc-look', mode: 'training', speaker: '주인공', text: '세 분이 여기까지 오셨는데 굳이 거절할 이유는 없으니까요.' },
    { id: 'c11-choice', mode: 'training', speaker: '주인공', text: '세 사람의 표정이 조금씩 밝아졌다.', choices: [
      { id: 'c11-give-up', label: '오늘 계획을 세 사람에게 맡긴다.', reply: '오늘은 세 분이 정한 대로 따라갈게요.', affection: { haru: 1, sena: 1, momo: 1 }, trust: { haru: 1, sena: 1, momo: 1 } },
      { id: 'c11-one-more', label: '어디로 갈지 먼저 묻는다.', reply: '그래서 오늘은 어디로 가는 건가요?', affection: { haru: 1, sena: 1 }, trust: { momo: 1 } },
      { id: 'c11-why-together', label: '함께 온 것이 반갑다고 말한다.', reply: '세 분이 같이 찾아와 주셔서 반갑네요.', affection: { haru: 1, sena: 1, momo: 2 }, trust: { haru: 1, sena: 1, momo: 1 } }
    ] },
    { id: 'c11-sena-response', mode: 'training', speaker: '세나', text: '오늘은 가볍게 쉬고, 내일 중앙도시를 같이 돌아봐요.' },
    { id: 'c11-mc-rest-question', mode: 'training', speaker: '주인공', text: '네 사람이 다 같이요?' },
    { id: 'c11-haru-decide', mode: 'training', speaker: '하루', text: '네. 생각해 보니 넷이 임무 밖에서 만난 적은 없더라고요.' },
    { id: 'c11-momo-nod', mode: 'training', speaker: '모모', text: '시장도 구경하고, 맛있는 것도 먹으면 좋을 것 같아요.' },
    { id: 'c11-sena-check-hand', mode: 'training', narration: true, text: '모모가 조심스럽게 말을 보태자 세나는 기다렸다는 듯 내일의 약속을 정리했다.' },
    { id: 'c11-sena-state', mode: 'training', speaker: '세나', text: '내일 아침 길드 앞에서 만나요. 늦잠은 괜찮지만 몰래 훈련하고 오는 건 안 돼요.' },
    { id: 'c11-water', mode: 'training', speaker: '주인공', text: '알겠어요. 약속할게요.' },
    { id: 'c11-momo-water', mode: 'training', narration: true, text: '네 사람은 나란히 훈련소를 나왔다. 햇빛이 아직 높았고, 거리는 평소와 같은 소리로 가득했다.' },
    { id: 'c11-thanks', mode: 'city', speaker: '하루', text: '오늘은 정말 숙소로 돌아가는 거죠?' },
    { id: 'c11-exit-training', mode: 'city', speaker: '주인공', text: '네. 내일 오래 걸어야 한다면서요.' },
    { id: 'c11-evening-city', mode: 'city', narration: true, text: '하루가 작게 웃었고, 모모도 안심한 듯 고개를 끄덕였다. 세나는 그 모습을 바라보다 앞장서 걸었다.' },
    { id: 'c11-mc-where', mode: 'city', speaker: '세나', text: '그럼 오늘은 여기서 헤어져요. 내일은 느긋하게 시작하죠.' },
    { id: 'c11-haru-no', mode: 'city', narration: true, text: '갈림길에서 네 사람은 걸음을 멈췄다. 짧은 약속 하나였지만, 다음 날을 기다리게 하기에는 충분했다.' },
    { id: 'c11-mc-deny2', mode: 'city', speaker: '주인공', text: '내일 뵐게요.' },
    { id: 'c11-three-look', mode: 'city', speaker: '모모', text: '네. 내일 봬요.' },
    { id: 'c11-mc-correct', mode: 'city', narration: true, text: '모모가 손을 흔들었고 하루와 세나도 각자의 길로 돌아섰다.' },
    { id: 'c11-momo-smile', mode: 'black', narration: true, text: '주인공은 숙소로 향하며 내일 무엇을 보게 될지 잠시 생각했다. 훈련이 아닌 하루를 기대하는 것은 처음이었다.' },
    { id: 'c11-sena-plan', mode: 'black', center: '내일 아침\n길드 앞에서' },
    { id: 'c11-mc-city', mode: 'black', narration: true, text: '네 사람이 처음으로 함께 시간을 보내기로 했다.' },
    { id: 'c11-haru-point', mode: 'black', center: 'CHAPTER 11 CLEAR' },
    { id: 'c11-momo-market', mode: 'black', ending: true, center: '평범한 하루가 새로운 약속으로 이어졌다.' }
  ]
};