export const chapter012 = {
  id: 12,
  title: '중앙도시의 하루',
  scenes: [
    { id: 'c12-title', mode: 'black', center: 'CHAPTER 12\n\n중앙도시의 하루' },
    { id: 'c12-morning', mode: 'city', narration: true, text: '다음 날 아침, 주인공이 길드 앞에 도착했을 때 세 사람은 이미 모여 있었다.' },
    { id: 'c12-momo-early', mode: 'city', narration: true, text: '모모는 작은 가방을 두 손으로 꼭 잡고 있었고, 하루는 길 건너 상점들을 바라보고 있었다. 세나는 네 사람의 얼굴을 차례로 확인했다.' },
    { id: 'c12-sena-greet', mode: 'city', speaker: '세나', text: '좋은 아침이에요. 몰래 훈련하고 온 얼굴은 아니네요.' },
    { id: 'c12-mc-answer', mode: 'city', speaker: '주인공', text: '오늘은 약속을 지켰습니다.' },
    { id: 'c12-haru-check', mode: 'city', speaker: '하루', text: '손에 새 상처도 없네요. 확인했습니다.' },
    { id: 'c12-mc-plan', mode: 'city', speaker: '주인공', text: '어디부터 갑니까?' },
    { id: 'c12-haru-shop', mode: 'city', speaker: '하루', text: '장비점부터요. 지금 쓰는 검은 임시 장비에 가깝잖아요.' },
    { id: 'c12-walk-shop', mode: 'city', narration: true, text: '네 사람은 큰길을 따라 상업 구역으로 향했다. 길드 주변보다 건물이 높고, 창문마다 각기 다른 색의 구현등이 걸려 있었다.' },
    { id: 'c12-mc-lights', mode: 'city', speaker: '주인공', text: '저 불빛은 밤새 유지되는 겁니까?' },
    { id: 'c12-haru-explain', mode: 'city', speaker: '하루', text: '도시 중심부에서 정신 에너지를 공급해요. 개인이 직접 유지하는 것보다 안정적입니다.' },
    { id: 'c12-momo-add', mode: 'city', speaker: '모모', text: '외곽으로 갈수록 공급이 약해져요. 그래서 밤에는 중심가 쪽이 훨씬 밝아요.' },
    { id: 'c12-sena-natural', mode: 'city', speaker: '세나', text: '도시도 사람처럼 에너지를 쓰는 셈이에요. 많이 쓰면 보충해야 하고, 무리하면 기능이 떨어지죠.' },
    { id: 'c12-shop-enter', mode: 'shop', narration: true, text: '장비점 안에는 검과 방패, 보호구가 종류별로 진열되어 있었다. 실물 재료로 만든 물건과 정신 에너지로 구현한 장비가 한 공간에 섞여 있었다.' },
    { id: 'c12-mc-material', mode: 'shop', speaker: '주인공', text: '구현할 수 있는데도 장비를 따로 만드는 이유가 있습니까?' },
    { id: 'c12-haru-gear', mode: 'shop', speaker: '하루', text: '구현 장비는 사용자의 집중력에 영향을 많이 받아요. 정신이 흔들리면 형태도 약해집니다.' },
    { id: 'c12-sena-gear', mode: 'shop', speaker: '세나', text: '반대로 실제 재료가 섞인 장비는 무겁지만 안정적이에요. 전투 방식에 따라 선택하는 거죠.' },
    { id: 'c12-momo-knife', mode: 'shop', narration: true, text: '모모는 작은 단검 하나를 들어 보았다가 가격표를 확인하고 조용히 제자리에 내려놓았다.' },
    { id: 'c12-mc-momo', mode: 'shop', speaker: '주인공', text: '마음에 듭니까?' },
    { id: 'c12-momo-deny', mode: 'shop', speaker: '모모', text: '아, 아니요. 그냥 가볍다고 생각해서요. 정말로 사려던 건 아니에요.' },
    { id: 'c12-haru-honest', mode: 'shop', speaker: '하루', text: '가격을 세 번 확인했으면서요?' },
    { id: 'c12-momo-fluster', mode: 'shop', speaker: '모모', text: '그건 혹시 잘못 본 건가 해서…….' },
    { id: 'c12-soft-moment', mode: 'shop', narration: true, text: '세나가 웃으며 모모에게 단검을 다시 건넸다. 손에 맞는지 확인하는 것까지는 돈이 들지 않는다고 말하자 모모는 조심스럽게 손잡이를 쥐었다.' },
    { id: 'c12-mc-sword', mode: 'shop', narration: true, text: '주인공도 여러 자루의 검을 들어 보았다. 하지만 손에 익은 감각과 맞는 것은 없었다.' },
    { id: 'c12-haru-advice', mode: 'shop', speaker: '하루', text: '서두르지 않아도 돼요. 오래 쓸 장비라면 손에 맞는 걸 찾는 게 먼저입니다.' },
    { id: 'c12-leave-shop', mode: 'market', narration: true, text: '장비점을 나온 뒤에는 시장 골목으로 들어섰다. 천막 아래에는 식재료와 생활용품, 작은 에너지 결정까지 빼곡하게 놓여 있었다.' },
    { id: 'c12-market-sound', mode: 'market', narration: true, text: '사람들의 목소리와 물건을 흥정하는 소리가 골목을 가득 채웠다. 모모는 자연스럽게 세나의 가까운 쪽으로 붙었다.' },
    { id: 'c12-mc-market', mode: 'market', speaker: '주인공', text: '이곳의 물건도 전부 구현된 겁니까?' },
    { id: 'c12-sena-food', mode: 'market', speaker: '세나', text: '아니요. 먹는 것과 오래 남겨야 하는 물건은 대부분 직접 길러서 만들어요.' },
    { id: 'c12-haru-rule', mode: 'market', speaker: '하루', text: '정신 에너지로 음식 모양을 만드는 건 가능하지만 배를 채우지는 못해요. 모양과 감각만 흉내 내는 정도입니다.' },
    { id: 'c12-mc-world', mode: 'market', speaker: '주인공', text: '정신세계인데도 실제로 먹고 자야 하는군요.' },
    { id: 'c12-sena-answer', mode: 'market', speaker: '세나', text: '여기서 태어나고 살아가는 사람들에게는 이쪽이 현실이에요. 몸이 다르다고 생활까지 사라지는 건 아니니까요.' },
    { id: 'c12-haru-pause', mode: 'market', narration: true, text: '하루는 잠시 걸음을 늦췄다. 지나가는 사람들과 시장의 풍경을 바라본 뒤 조용히 말을 이었다.' },
    { id: 'c12-haru-home', mode: 'market', speaker: '하루', text: '저는 다른 세상을 본 적이 없어요. 중앙도시도, 길드도, 이 거리도 전부 제가 살아온 곳입니다.' },
    { id: 'c12-mc-understand', mode: 'market', narration: true, text: '주인공은 대답 대신 하루와 같은 방향을 바라보았다. 기억이 없는 자신에게도 이 도시는 점점 낯선 장소만은 아니게 되어 가고 있었다.' },
    { id: 'c12-snack', mode: 'market', narration: true, text: '모모가 작은 구운 과자를 네 개 샀다. 하나씩 나눠 준 뒤 자신의 몫을 가장 마지막에 꺼냈다.' },
    { id: 'c12-momo-share', mode: 'market', speaker: '모모', text: '이건 여기 시장에서만 파는 거래요. 많이 달지는 않아서 괜찮을 거예요.' },
    { id: 'c12-choice', mode: 'market', speaker: '주인공', text: '따뜻한 과자에서 고소한 냄새가 났다.', choices: [
      { id: 'c12-thank-momo', label: '모모에게 먼저 고맙다고 말한다.', reply: '잘 먹겠습니다. 모모 씨가 골라 주셨으니 믿어보겠습니다.', affection: { momo: 2 }, trust: { momo: 1 } },
      { id: 'c12-share-half', label: '가장 큰 조각을 나눠 준다.', reply: '이건 조금 큰 것 같습니다. 같이 나눠 먹죠.', affection: { haru: 1, sena: 1, momo: 1 }, traits: { considerate: 1 } },
      { id: 'c12-ask-favorite', label: '세 사람의 단골 음식을 묻는다.', reply: '세 분은 이곳에 오면 보통 무엇을 드십니까?', trust: { haru: 1, sena: 1, momo: 1 } }
    ] },
    { id: 'c12-lunch-move', mode: 'restaurant', narration: true, text: '시장을 한 바퀴 돌고 나자 점심때가 가까워졌다. 세나는 골목 끝의 작은 식당으로 모두를 이끌었다.' },
    { id: 'c12-seat', mode: 'restaurant', narration: true, text: '네 사람은 창가의 긴 탁자에 마주 앉았다. 처음에는 자리가 넓게 느껴졌지만 음식이 놓이자 금세 빈틈이 사라졌다.' },
    { id: 'c12-momo-order', mode: 'restaurant', speaker: '모모', text: '이렇게 많이 시켜도 괜찮을까요?' },
    { id: 'c12-sena-order', mode: 'restaurant', speaker: '세나', text: '훈련만 하던 사람 한 명을 제대로 먹이려면 이 정도는 필요해요.' },
    { id: 'c12-mc-protest', mode: 'restaurant', speaker: '주인공', text: '제가 전부 먹는 것처럼 들립니다.' },
    { id: 'c12-haru-dry', mode: 'restaurant', speaker: '하루', text: '절반 정도는 맞을 것 같네요.' },
    { id: 'c12-eat', mode: 'restaurant', narration: true, text: '말은 그렇게 했지만 음식은 네 사람이 비슷한 속도로 줄여 갔다. 모모는 처음보다 편해진 얼굴로 그릇을 건넸고, 하루는 말없이 비어 있는 접시를 안쪽으로 모았다.' },
    { id: 'c12-mission-talk', mode: 'restaurant', speaker: '주인공', text: '의뢰에 실패하면 보통 이렇게 쉬기도 합니까?' },
    { id: 'c12-sena-mission', mode: 'restaurant', speaker: '세나', text: '사람마다 달라요. 바로 다음 의뢰를 받는 사람도 있고, 한동안 현장을 피하는 사람도 있어요.' },
    { id: 'c12-haru-fail', mode: 'restaurant', speaker: '하루', text: '실패 기록은 지워지지 않지만, 한 번의 기록이 그 사람 전부가 되는 건 아닙니다.' },
    { id: 'c12-momo-soft', mode: 'restaurant', speaker: '모모', text: '살아서 돌아오면 다음이 있으니까요. 저는 그게 더 중요하다고 생각해요.' },
    { id: 'c12-mc-receive', mode: 'restaurant', narration: true, text: '주인공은 세 사람의 말을 바로 받아치지 못했다. 대신 앞에 놓인 물잔을 천천히 비웠다.' },
    { id: 'c12-cafe-move', mode: 'cafe', narration: true, text: '식사를 마친 뒤에는 큰길 위쪽의 카페로 이동했다. 창문 너머로 중앙광장과 멀리 도시 외벽까지 보이는 곳이었다.' },
    { id: 'c12-cafe-order', mode: 'cafe', narration: true, text: '세나는 따뜻한 차를, 하루는 향이 옅은 음료를 골랐다. 모모는 메뉴를 오래 바라보다가 세나와 같은 것을 주문했다.' },
    { id: 'c12-mc-ask-city', mode: 'cafe', speaker: '주인공', text: '중앙도시 밖에도 이런 도시가 많습니까?' },
    { id: 'c12-haru-cities', mode: 'cafe', speaker: '하루', text: '크고 작은 도시가 여러 곳 있어요. 서로 물자를 주고받고, 길드는 이동로와 외곽을 관리합니다.' },
    { id: 'c12-sena-boundary', mode: 'cafe', speaker: '세나', text: '도시 밖은 아직 악몽의 영역이 더 넓어요. 사람들이 안전하게 살 수 있는 곳은 생각보다 많지 않아요.' },
    { id: 'c12-momo-walls', mode: 'cafe', speaker: '모모', text: '그래서 외벽과 결계가 중요해요. 결계가 약해지는 날에는 외곽 사람들이 중심부로 들어오기도 하고요.' },
    { id: 'c12-mc-hunters', mode: 'cafe', speaker: '주인공', text: '헌터가 필요한 이유도 그 때문이군요.' },
    { id: 'c12-haru-yes', mode: 'cafe', speaker: '하루', text: '네. 악몽을 사냥하는 일도 하지만, 도시와 도시 사이의 길을 이어 두는 것도 헌터의 역할입니다.' },
    { id: 'c12-silence-view', mode: 'cafe', narration: true, text: '대화가 잠시 끊겼다. 네 사람은 창밖을 내려다보았다. 광장을 오가는 사람들과 수레, 멀리 빛나는 외벽의 결계가 한눈에 들어왔다.' },
    { id: 'c12-mc-home', mode: 'cafe', speaker: '주인공', text: '저도 언젠가는 이곳을 제 도시라고 생각하게 될까요?' },
    { id: 'c12-haru-answer2', mode: 'cafe', speaker: '하루', text: '이미 조금은 그렇게 생각하고 있는 것 아닌가요?' },
    { id: 'c12-mc-noanswer', mode: 'cafe', narration: true, text: '주인공은 부정하지 않았다. 모모는 잔을 감싼 손에 힘을 풀었고, 세나는 아무 말 없이 미소만 지었다.' },
    { id: 'c12-evening-return', mode: 'city', narration: true, text: '카페를 나왔을 때는 하늘빛이 서서히 어두워지고 있었다. 낮 동안 붐비던 시장 골목도 하나둘 문을 닫기 시작했다.' },
    { id: 'c12-walk-home', mode: 'city', narration: true, text: '네 사람은 숙소 방향으로 천천히 걸었다. 아침보다 말수는 줄었지만 어색한 침묵은 아니었다.' },
    { id: 'c12-momo-tired', mode: 'city', speaker: '모모', text: '오늘 생각보다 많이 걸었네요. 그래도…… 재미있었어요.' },
    { id: 'c12-sena-agree', mode: 'city', speaker: '세나', text: '다음에는 외곽 광장 쪽도 가요. 오늘은 시간이 모자랐네요.' },
    { id: 'c12-haru-mc', mode: 'city', speaker: '하루', text: '{{playerName}} 씨만 다시 훈련소로 도망가지 않는다면요.' },
    { id: 'c12-mc-promise', mode: 'city', speaker: '주인공', text: '적어도 오늘은 가지 않겠습니다.' },
    { id: 'c12-part', mode: 'city', narration: true, text: '숙소 앞에서 세 사람과 헤어진 뒤에도 주인공은 한동안 자리에 서 있었다. 하루 동안 들었던 목소리와 웃음이 조용해진 거리 위에 남아 있는 듯했다.' },
    { id: 'c12-clear', mode: 'black', center: 'CHAPTER 12 CLEAR' },
    { id: 'c12-end', mode: 'black', ending: true, center: '중앙도시에서의 하루가 네 사람의 첫 추억이 되었다.' }
  ]
};