export const chapter014 = {
  id: 14,
  title: '첫 번째 네 사람',
  scenes: [
    { id: 'c14-title', mode: 'black', center: 'CHAPTER 14\n\n첫 번째 네 사람' },
    { id: 'c14-office-silence', mode: 'guildmaster', narration: true, text: '세나의 보고가 끝난 뒤 길드장실에는 잠시 침묵이 흘렀다. 길드장은 지난 의뢰의 보고서와 주인공의 상태 기록을 차례로 넘겼다.' },
    { id: 'c14-guildmaster-question', mode: 'guildmaster', speaker: '길드장', text: '처음 다쳤을 때부터 치료가 전혀 통하지 않았다는 거지?' },
    { id: 'c14-sena-confirm', mode: 'guildmaster', speaker: '세나', text: '네. 정신 에너지는 회복됐지만 상처 자체에는 반응이 없었어요.' },
    { id: 'c14-haru-add', mode: 'guildmaster', speaker: '하루', text: '악몽의 오염 반응도 없습니다. 제가 아는 상처와는 다릅니다.' },
    { id: 'c14-guildmaster-mc', mode: 'guildmaster', speaker: '길드장', text: '{{playerName}}, 통증은 어느 정도지?' },
    { id: 'c14-mc-answer', mode: 'guildmaster', speaker: '주인공', text: '움직일 수는 있습니다. 다만 깊게 숨을 쉬거나 몸을 비틀면 당깁니다.' },
    { id: 'c14-guildmaster-think', mode: 'guildmaster', narration: true, text: '길드장은 손가락으로 책상을 천천히 두드렸다. 모모는 숨소리마저 줄인 채 그 움직임을 바라보았다.' },
    { id: 'c14-guildmaster-record', mode: 'guildmaster', speaker: '길드장', text: '길드의 치료 기록에는 같은 사례가 없다. 그렇다면 현장에서 원인을 찾아야 한다.' },
    { id: 'c14-mc-field', mode: 'guildmaster', speaker: '주인공', text: '다쳤던 장소로 다시 가라는 말씀입니까?' },
    { id: 'c14-guildmaster-yes', mode: 'guildmaster', speaker: '길드장', text: '정확히는 그 일대의 이상 현상을 조사한다. 최근 같은 구역에서 악몽의 이동과 에너지 흐름이 모두 평소와 달랐다.' },
    { id: 'c14-map-open', mode: 'guildmaster', narration: true, text: '길드장은 책상 위에 지도를 펼쳤다. 지난번 두 사람이 지나간 숲길과 동굴 주변에 여러 개의 표시가 남아 있었다.' },
    { id: 'c14-guildmaster-marks', mode: 'guildmaster', speaker: '길드장', text: '악몽 무리가 일정한 영역을 벗어나 호송로까지 내려왔다. 그리고 이 상처가 생겼다. 둘을 별개로 보기에는 시점이 너무 가깝다.' },
    { id: 'c14-sena-risk', mode: 'guildmaster', speaker: '세나', text: '상처가 열린 상태로 다시 현장에 보내는 건 위험해요.' },
    { id: 'c14-guildmaster-agree', mode: 'guildmaster', speaker: '길드장', text: '그래서 단독으로 보내지 않는다.' },
    { id: 'c14-four-look', mode: 'guildmaster', narration: true, text: '길드장의 시선이 주인공에서 하루, 세나, 모모에게 차례로 이동했다.' },
    { id: 'c14-party-order', mode: 'guildmaster', speaker: '길드장', text: '이번 조사는 네 사람이 맡아라.' },
    { id: 'c14-momo-surprise', mode: 'guildmaster', speaker: '모모', text: '저, 저도 말인가요?' },
    { id: 'c14-guildmaster-momo', mode: 'guildmaster', speaker: '길드장', text: '은신과 정찰이 가능한 인원이 필요하다. 전투를 피해야 할 때 네 능력이 가장 적합하다.' },
    { id: 'c14-momo-straight', mode: 'guildmaster', narration: true, text: '모모는 놀란 얼굴로 가방 끈을 움켜쥐었다. 잠시 뒤 작게 숨을 들이쉬고 허리를 바로 세웠다.' },
    { id: 'c14-momo-accept', mode: 'guildmaster', speaker: '모모', text: '알겠습니다. 방해되지 않도록 하겠습니다.' },
    { id: 'c14-haru-correct', mode: 'guildmaster', speaker: '하루', text: '방해가 아니라 정찰 담당이에요. 맡은 일을 하면 됩니다.' },
    { id: 'c14-momo-nod', mode: 'guildmaster', speaker: '모모', text: '네. 정찰 담당으로 가겠습니다.' },
    { id: 'c14-guildmaster-roles', mode: 'guildmaster', speaker: '길드장', text: '하루는 원거리 경계와 지휘 보조. 세나는 치료와 결계. 모모는 정찰. {{playerName}}은 현장 반응 확인과 근접 대응을 맡는다.' },
    { id: 'c14-mc-role', mode: 'guildmaster', speaker: '주인공', text: '제 상처의 반응을 확인하기 위해서라도 제가 직접 가야 하는군요.' },
    { id: 'c14-guildmaster-warning', mode: 'guildmaster', speaker: '길드장', text: '맞다. 다만 이번 의뢰의 우선순위는 전투가 아니다. 이상 징후 확인, 표본 확보, 전원 생환. 이 세 가지다.' },
    { id: 'c14-sena-condition', mode: 'guildmaster', speaker: '세나', text: '상태가 나빠지면 제가 바로 철수시킬 거예요. 그 조건이라면 동의하겠습니다.' },
    { id: 'c14-haru-condition', mode: 'guildmaster', speaker: '하루', text: '저도 같습니다. 무리해서 싸울 이유는 없습니다.' },
    { id: 'c14-choice', mode: 'guildmaster', speaker: '주인공', text: '세 사람은 이미 각자의 역할을 받아들이고 있었다.', choices: [
      { id: 'c14-trust-party', label: '세 사람을 믿고 의뢰를 받는다.', reply: '알겠습니다. 세 분을 믿고 함께 가겠습니다.', affection: { haru: 1, sena: 1, momo: 1 }, trust: { haru: 2, sena: 2, momo: 2 } },
      { id: 'c14-promise-return', label: '전원 생환을 약속한다.', reply: '이번에는 반드시 네 명 모두 무사히 돌아오겠습니다.', affection: { haru: 1, sena: 1, momo: 2 }, traits: { brave: 1, considerate: 1 } },
      { id: 'c14-accept-role', label: '자신의 역할에 집중하겠다고 말한다.', reply: '제 상태를 숨기지 않고 바로 공유하겠습니다. 맡은 역할에 집중하겠습니다.', trust: { haru: 1, sena: 3, momo: 1 }, traits: { cautious: 1 } }
    ] },
    { id: 'c14-guildmaster-approval', mode: 'guildmaster', speaker: '길드장', text: '좋다. 출발은 오늘 오후다. 그전까지 장비와 보급을 갖춰라.' },
    { id: 'c14-mission-status', mode: 'status', center: '미확인 현상 조사\n\n조사 지역: 동부 호송로 외곽\n구성 인원: 4명\n목표: 이상 징후 확인 및 전원 생환' },
    { id: 'c14-leave-office', mode: 'guild', narration: true, text: '네 사람은 의뢰서를 받아 들고 길드장실을 나왔다. 문이 닫히자 모모가 참았던 숨을 길게 내쉬었다.' },
    { id: 'c14-momo-nervous', mode: 'guild', speaker: '모모', text: '정식 파티는 처음이에요. 그것도 네 명이나 같이 가는 건…….' },
    { id: 'c14-sena-calm', mode: 'guild', speaker: '세나', text: '그래서 더 괜찮아요. 혼자 판단할 필요가 없으니까요.' },
    { id: 'c14-haru-plan', mode: 'guild', speaker: '하루', text: '먼저 역할을 다시 맞추죠. 현장에서 서로 이름만 부르고 움직일 수 있을 정도로요.' },
    { id: 'c14-table', mode: 'guild', narration: true, text: '네 사람은 홀 구석의 빈 탁자에 지도를 펼쳤다. 하루가 이동 경로를 짚고, 세나는 중간 휴식 지점을 표시했다.' },
    { id: 'c14-momo-route', mode: 'guild', speaker: '모모', text: '여기 수풀 쪽으로 들어가면 큰길에서 모습이 잘 안 보여요. 먼저 가서 확인하고 돌아올 수 있어요.' },
    { id: 'c14-haru-praise', mode: 'guild', speaker: '하루', text: '좋아요. 다만 시야에서 너무 오래 사라지지는 마세요. 신호 간격을 정하죠.' },
    { id: 'c14-momo-relief', mode: 'guild', narration: true, text: '모모는 자신의 의견이 바로 계획에 반영되자 조금 놀란 표정을 지었다. 곧 지도 위에 손가락을 올리고 더 자세히 길을 설명했다.' },
    { id: 'c14-sena-mc-rule', mode: 'guild', speaker: '세나', text: '{{playerName}} 씨는 통증이 평소보다 강해지면 바로 말해요. 참았다가 쓰러지는 건 이번에는 금지예요.' },
    { id: 'c14-mc-rule', mode: 'guild', speaker: '주인공', text: '알겠습니다. 숨기지 않겠습니다.' },
    { id: 'c14-haru-add-rule', mode: 'guild', speaker: '하루', text: '저희도 각자 상태를 공유하죠. 누구 한 사람만 지켜지는 규칙이면 오래 못 갑니다.' },
    { id: 'c14-agree', mode: 'guild', narration: true, text: '세나와 모모가 고개를 끄덕였다. 간단한 약속이었지만 네 사람 사이에 처음으로 같은 기준이 생겼다.' },
    { id: 'c14-prep-montage', mode: 'city', narration: true, text: '그 뒤로 네 사람은 필요한 준비를 나눠 맡았다. 하루는 화살에 사용할 에너지 결정을 확인했고, 세나는 치료 도구와 결계 매개체를 챙겼다.' },
    { id: 'c14-momo-supplies', mode: 'market', narration: true, text: '모모는 시장에서 식량과 물을 구입했다. 전날 함께 걸었던 골목을 이번에는 망설이지 않고 앞장서 지나갔다.' },
    { id: 'c14-mc-gear', mode: 'shop', narration: true, text: '주인공은 장비점에서 상처를 압박해 줄 보호대를 골랐다. 완전히 맞는 검은 찾지 못했지만, 손에 익은 임시 검을 정비했다.' },
    { id: 'c14-meet-gate', mode: 'city-gate', narration: true, text: '오후가 되자 네 사람은 중앙도시 동문 앞에 다시 모였다. 외벽 너머로 이어지는 길은 지난 의뢰 때와 같은 방향이었다.' },
    { id: 'c14-momo-food', mode: 'city-gate', speaker: '모모', text: '식량은 네 명 기준으로 이틀분 챙겼어요. 혹시 길어질 수도 있으니까 조금 더 넣었고요.' },
    { id: 'c14-sena-check', mode: 'city-gate', speaker: '세나', text: '치료 도구도 준비됐어요. 결계는 두 번 정도 길게 유지할 수 있어요.' },
    { id: 'c14-haru-ready', mode: 'city-gate', speaker: '하루', text: '경로도 확인했습니다. 동굴까지 곧장 가지 않고 주변 흔적부터 볼게요.' },
    { id: 'c14-mc-ready', mode: 'city-gate', speaker: '주인공', text: '저도 준비됐습니다.' },
    { id: 'c14-four-line', mode: 'city-gate', narration: true, text: '네 사람은 잠시 서로를 바라보았다. 며칠 전까지는 각자의 이유로 같은 장소에 있었지만, 지금은 하나의 의뢰를 위해 같은 방향을 보고 있었다.' },
    { id: 'c14-haru-lead', mode: 'city-gate', speaker: '하루', text: '출발하죠. 모모 씨가 앞을 확인하고, 나머지는 간격을 유지해요.' },
    { id: 'c14-momo-first', mode: 'city-gate', speaker: '모모', text: '네. 너무 멀리 가지 않고 바로 신호할게요.' },
    { id: 'c14-sena-smile', mode: 'city-gate', speaker: '세나', text: '이번에는 네 명이 같이 돌아오는 거예요.' },
    { id: 'c14-mc-final', mode: 'city-gate', speaker: '주인공', text: '네. 함께 돌아오겠습니다.' },
    { id: 'c14-depart', mode: 'forest-exit', narration: true, text: '도시의 문이 열리고 모모가 먼저 길 위로 나섰다. 하루와 주인공이 그 뒤를 따르고, 세나가 마지막으로 모두의 상태를 살피며 걸음을 옮겼다.' },
    { id: 'c14-party-formed', mode: 'status', center: '정식 4인 파티 결성\n\n{{playerName}} · 하루 · 세나 · 모모' },
    { id: 'c14-road', mode: 'black', narration: true, text: '네 사람의 첫 번째 공동 의뢰가 시작되었다.' },
    { id: 'c14-clear', mode: 'black', center: 'CHAPTER 14 CLEAR' },
    { id: 'c14-end', mode: 'black', ending: true, center: '네 사람은 처음으로 하나의 파티가 되어 중앙도시를 떠났다.' }
  ]
};