export const chapter012 = {
  id: 12,
  title: '중앙도시의 하루',
  scenes: [
    { id: 'c12-title', mode: 'black', center: 'CHAPTER 12\n\n중앙도시의 하루' },
    { id: 'c12-morning', mode: 'city', narration: true, text: '다음 날 아침, 주인공이 길드 앞에 도착했을 때 세 사람은 이미 기다리고 있었다.' },
    { id: 'c12-momo-early', mode: 'city', narration: true, text: '모모는 작은 가방을 두 손으로 안고 있었고, 하루는 맞은편 상점들을 둘러보고 있었다. 세나는 주인공을 보자 가볍게 손을 들었다.' },
    { id: 'c12-sena-greet', mode: 'city', speaker: '세나', text: '좋은 아침이에요. 약속대로 훈련은 안 하고 왔네요.' },
    { id: 'c12-mc-answer', mode: 'city', speaker: '주인공', text: '네. 오늘은 제대로 쉬기로 했으니까요.' },
    { id: 'c12-haru-check', mode: 'city', speaker: '하루', text: '좋아요. 그럼 장비점부터 가죠.' },
    { id: 'c12-mc-plan', mode: 'city', speaker: '주인공', text: '처음부터 장비를 보러 가는 건가요?' },
    { id: 'c12-haru-shop', mode: 'city', speaker: '하루', text: '쉬는 날에도 구경은 할 수 있잖아요. 사는 건 나중 문제고요.' },
    { id: 'c12-walk-shop', mode: 'city', narration: true, text: '네 사람은 큰길을 따라 상업 구역으로 걸었다. 길드 주변보다 건물이 높았고, 창문마다 다른 빛의 구현등이 걸려 있었다.' },
    { id: 'c12-mc-lights', mode: 'city', speaker: '주인공', text: '저 불빛은 계속 켜 둘 수 있나요?' },
    { id: 'c12-haru-explain', mode: 'city', speaker: '하루', text: '도시 중심부에서 정신에너지를 공급해요. 가게마다 직접 유지하는 것보다 훨씬 안정적이에요.' },
    { id: 'c12-momo-add', mode: 'city', speaker: '모모', text: '대신 외곽으로 갈수록 빛이 조금 약해져요. 밤에는 차이가 더 잘 보여요.' },
    { id: 'c12-sena-natural', mode: 'city', speaker: '세나', text: '건물도 비슷해요. 뼈대는 실제 재료로 세우고, 부족한 부분을 구현해서 보완하는 곳이 많아요.' },
    { id: 'c12-shop-enter', mode: 'shop', narration: true, text: '장비점 안에는 검과 방패, 보호구가 벽면을 가득 채우고 있었다. 실제 재료로 만든 장비와 구현을 돕는 장비가 자연스럽게 섞여 있었다.' },
    { id: 'c12-mc-material', mode: 'shop', speaker: '주인공', text: '구현무기가 있는데도 이런 장비를 따로 쓰는 이유가 있나요?' },
    { id: 'c12-haru-gear', mode: 'shop', speaker: '하루', text: '구현무기는 집중력이 흔들리면 바로 약해져요. 오래 싸울수록 차이가 커지고요.' },
    { id: 'c12-sena-gear', mode: 'shop', speaker: '세나', text: '실제 장비는 무겁지만 형태가 무너지지 않죠. 둘을 같이 쓰는 사람도 많아요.' },
    { id: 'c12-momo-knife', mode: 'shop', narration: true, text: '모모는 작은 단검 하나를 들어 보았다. 손에 몇 번 쥐어 본 뒤 가격표를 보고 조용히 내려놓았다.' },
    { id: 'c12-mc-momo', mode: 'shop', speaker: '주인공', text: '마음에 들었어요?' },
    { id: 'c12-momo-deny', mode: 'shop', speaker: '모모', text: '아, 그냥 가벼워 보여서요. 사려던 건 아니에요.' },
    { id: 'c12-haru-honest', mode: 'shop', speaker: '하루', text: '가격표를 세 번이나 봤는데요?' },
    { id: 'c12-momo-fluster', mode: 'shop', speaker: '모모', text: '혹시 제가 잘못 본 건가 해서…….' },
    { id: 'c12-soft-moment', mode: 'shop', narration: true, text: '세나가 웃으며 단검을 다시 건넸다. 손에 맞는지 보는 것까지는 공짜라고 하자 모모는 조심스럽게 손잡이를 쥐었다.' },
    { id: 'c12-mc-sword', mode: 'shop', narration: true, text: '주인공도 몇 자루의 검을 들어 보았다. 모양은 좋았지만 손에 익은 감각과 정확히 맞는 것은 없었다.' },
    { id: 'c12-haru-advice', mode: 'shop', speaker: '하루', text: '급하게 고를 필요 없어요. 오래 쓸 거라면 맞는 걸 찾을 때까지 보는 편이 나아요.' },
    { id: 'c12-leave-shop', mode: 'market', narration: true, text: '장비점을 나온 뒤에는 시장 골목으로 들어섰다. 천막 아래로 식재료와 생활용품, 작은 에너지 결정까지 빼곡하게 놓여 있었다.' },
    { id: 'c12-market-sound', mode: 'market', narration: true, text: '흥정하는 목소리와 음식 냄새가 골목을 가득 채웠다. 사람이 몰리자 모모는 자연스럽게 세나 가까이 붙었다.' },
    { id: 'c12-mc-market', mode: 'market', speaker: '주인공', text: '여기 있는 물건도 대부분 구현한 건가요?' },
    { id: 'c12-sena-food', mode: 'market', speaker: '세나', text: '먹는 건 아니에요. 식재료는 직접 기르고, 오래 쓸 물건도 실제 재료로 만드는 편이에요.' },
    { id: 'c12-haru-rule', mode: 'market', speaker: '하루', text: '정신에너지로 모양과 향을 흉내 낼 수는 있어도 배가 차지는 않거든요.' },
    { id: 'c12-mc-world', mode: 'market', speaker: '주인공', text: '그러면 생활 자체는 제가 알던 것과 크게 다르지 않네요.' },
    { id: 'c12-sena-answer', mode: 'market', speaker: '세나', text: '사람 사는 곳은 다 비슷해요. 먹고, 자고, 일하고, 쉬고요.' },
    { id: 'c12-haru-pause', mode: 'market', narration: true, text: '하루는 지나가는 사람들과 가게들을 잠시 바라보다가 앞쪽의 붐비는 골목을 가리켰다.' },
    { id: 'c12-haru-home', mode: 'market', speaker: '하루', text: '중앙도시는 특히 사람이 많아요. 여러 도시에서 물자가 모이고, 새로 자리 잡는 사람도 계속 오니까요.' },
    { id: 'c12-mc-understand', mode: 'market', speaker: '주인공', text: '그래서 거리마다 분위기가 다른 거군요.' },
    { id: 'c12-snack', mode: 'market', narration: true, text: '모모가 작은 구운 과자를 네 개 샀다. 하나씩 나눠 주고 나서야 자신의 몫을 꺼냈다.' },
    { id: 'c12-momo-share', mode: 'market', speaker: '모모', text: '이건 이 시장에서만 판대요. 많이 달지 않아서 괜찮을 거예요.' },
    { id: 'c12-choice', mode: 'market', speaker: '주인공', text: '따뜻한 과자에서 고소한 냄새가 났다.', choices: [
      { id: 'c12-thank-momo', label: '모모에게 고맙다고 말한다.', reply: '잘 먹을게요. 모모 씨가 골랐으니 기대되네요.', affection: { momo: 2 }, trust: { momo: 1 } },
      { id: 'c12-share-half', label: '가장 큰 조각을 나눈다.', reply: '이건 조금 크네요. 같이 나눠 먹어요.', affection: { haru: 1, sena: 1, momo: 1 }, traits: { considerate: 1 } },
      { id: 'c12-ask-favorite', label: '세 사람이 좋아하는 음식을 묻는다.', reply: '세 분은 이 시장에 오면 보통 뭘 드세요?', trust: { haru: 1, sena: 1, momo: 1 } }
    ] },
    { id: 'c12-lunch-move', mode: 'restaurant', narration: true, text: '시장을 천천히 돌고 나니 어느새 점심때가 됐다. 세나는 골목 끝의 작은 식당으로 모두를 이끌었다.' },
    { id: 'c12-seat', mode: 'restaurant', narration: true, text: '네 사람은 창가의 긴 탁자에 마주 앉았다. 음식이 하나둘 놓이자 넓어 보이던 자리가 금세 비좁아졌다.' },
    { id: 'c12-momo-order', mode: 'restaurant', speaker: '모모', text: '이렇게 많이 시켜도 괜찮을까요?' },
    { id: 'c12-sena-order', mode: 'restaurant', speaker: '세나', text: '네 명이 먹을 건데 이 정도는 괜찮아요.' },
    { id: 'c12-mc-protest', mode: 'restaurant', speaker: '주인공', text: '방금 제 쪽에 그릇이 두 개 더 놓인 것 같은데요.' },
    { id: 'c12-haru-dry', mode: 'restaurant', speaker: '하루', text: '훈련하는 만큼은 드셔야죠.' },
    { id: 'c12-eat', mode: 'restaurant', narration: true, text: '처음에는 조용히 먹기만 했지만 곧 서로의 접시를 밀어 주고 남은 음식을 나누기 시작했다. 어색함은 음식이 줄어드는 만큼 자연스럽게 사라졌다.' },
    { id: 'c12-mission-talk', mode: 'restaurant', speaker: '주인공', text: '이렇게 넷이 앉아 있으니 임무 때와는 많이 다르네요.' },
    { id: 'c12-sena-mission', mode: 'restaurant', speaker: '세나', text: '당연하죠. 오늘은 누구도 다치지 않고, 시간 제한도 없으니까요.' },
    { id: 'c12-haru-fail', mode: 'restaurant', speaker: '하루', text: '가끔은 이런 날이 있어야 다음에도 같이 움직일 수 있어요.' },
    { id: 'c12-momo-soft', mode: 'restaurant', speaker: '모모', text: '저는…… 네 명이 같이 있으니까 생각보다 덜 긴장돼요.' },
    { id: 'c12-mc-receive', mode: 'restaurant', speaker: '주인공', text: '저도 그래요. 처음보다 훨씬 편하네요.' },
    { id: 'c12-cafe-move', mode: 'cafe', narration: true, text: '식사를 마친 뒤에는 큰길 위쪽의 카페로 자리를 옮겼다. 창문 너머로 중앙광장과 멀리 도시 외벽까지 한눈에 들어왔다.' },
    { id: 'c12-cafe-order', mode: 'cafe', narration: true, text: '세나는 따뜻한 차를, 하루는 향이 옅은 음료를 골랐다. 모모는 메뉴를 오래 보다가 세나와 같은 것을 주문했다.' },
    { id: 'c12-mc-ask-city', mode: 'cafe', speaker: '주인공', text: '중앙도시 밖에도 이런 도시가 많나요?' },
    { id: 'c12-haru-cities', mode: 'cafe', speaker: '하루', text: '크고 작은 도시가 여러 곳 있어요. 서로 물자를 주고받고, 길드는 그 사이의 길을 관리해요.' },
    { id: 'c12-sena-boundary', mode: 'cafe', speaker: '세나', text: '도시 밖은 악몽이 돌아다니는 구역이 더 넓어요. 안전한 길을 유지하는 것도 쉬운 일은 아니고요.' },
    { id: 'c12-momo-walls', mode: 'cafe', speaker: '모모', text: '그래서 외벽과 결계가 중요해요. 결계가 약해지는 날에는 바깥쪽 사람들이 안으로 들어오기도 해요.' },
    { id: 'c12-mc-hunters', mode: 'cafe', speaker: '주인공', text: '헌터가 도시 사이의 길까지 지키는 이유를 알겠네요.' },
    { id: 'c12-haru-yes', mode: 'cafe', speaker: '하루', text: '네. 사냥만 하는 사람들이 아니에요. 사람들이 오갈 수 있게 길을 이어 두는 것도 일이죠.' },
    { id: 'c12-silence-view', mode: 'cafe', narration: true, text: '대화가 잠시 멈췄다. 광장을 오가는 사람들과 수레, 외벽을 따라 흐르는 결계의 빛이 창밖으로 보였다.' },
    { id: 'c12-mc-home', mode: 'cafe', speaker: '주인공', text: '이제는 이 도시가 전처럼 낯설지는 않아요.' },
    { id: 'c12-haru-answer2', mode: 'cafe', speaker: '하루', text: '오늘 제대로 돌아봤으니 조금은 그럴 만하죠.' },
    { id: 'c12-mc-noanswer', mode: 'cafe', narration: true, text: '모모가 잔을 내려놓으며 작게 웃었다. 세나는 그 모습을 보고 다음에는 어디를 갈지 벌써 이야기하기 시작했다.' },
    { id: 'c12-evening-return', mode: 'city', narration: true, text: '카페를 나왔을 때는 하늘빛이 천천히 어두워지고 있었다. 시장 골목도 하나둘 문을 닫기 시작했다.' },
    { id: 'c12-walk-home', mode: 'city', narration: true, text: '네 사람은 숙소 방향으로 느긋하게 걸었다. 말이 끊겨도 누구도 서둘러 다음 말을 찾지 않았다.' },
    { id: 'c12-momo-tired', mode: 'city', speaker: '모모', text: '오늘 생각보다 많이 걸었네요. 그래도 재미있었어요.' },
    { id: 'c12-sena-agree', mode: 'city', speaker: '세나', text: '다음에는 외곽 광장 쪽도 가요. 오늘 못 본 곳이 아직 많아요.' },
    { id: 'c12-haru-mc', mode: 'city', speaker: '하루', text: '{{playerName}} 씨가 쉬는 날에도 잘 따라온다면요.' },
    { id: 'c12-mc-promise', mode: 'city', speaker: '주인공', text: '오늘 정도라면 다음에도 괜찮아요.' },
    { id: 'c12-part', mode: 'city', narration: true, text: '숙소 앞에서 세 사람과 헤어진 뒤, 주인공은 잠시 뒤를 돌아보았다. 세 사람은 아직 같은 자리에서 다음 약속을 이야기하고 있었다.' },
    { id: 'c12-clear', mode: 'black', center: 'CHAPTER 12 CLEAR' },
    { id: 'c12-end', mode: 'black', ending: true, center: '중앙도시에서 보낸 하루가 네 사람의 첫 추억이 되었다.' }
  ]
};