export const chapter011 = {
  id: 11,
  title: '쉬어 가는 날',
  scenes: [
    { id: 'c11-title', mode: 'black', center: 'CHAPTER 11\n\n쉬어 가는 날' },
    { id: 'c11-days-later', mode: 'training', narration: true, text: '의뢰 실패가 기록된 뒤 며칠이 지났다. 주인공은 아침부터 해가 기울 때까지 훈련소에 머물렀다.' },
    { id: 'c11-repeat', mode: 'training', narration: true, text: '검을 구현하고, 베고, 거두는 동작을 끝없이 반복했다. 손바닥의 굳은살이 터질 때마다 천을 감고 다시 검을 들었다.' },
    { id: 'c11-failure-memory', mode: 'training', narration: true, text: '잠깐이라도 움직임을 멈추면 길드장 앞에서 들었던 말이 떠올랐다. 정식 의뢰 실패. 그 짧은 문장이 머릿속에서 좀처럼 사라지지 않았다.' },
    { id: 'c11-swing', mode: 'training', speaker: '주인공', text: '다시.' },
    { id: 'c11-body-warning', mode: 'training', narration: true, text: '검을 쥔 손에 힘을 주자 옆구리의 상처가 당겼다. 통증은 전보다 약해졌지만, 완전히 사라지지는 않았다.' },
    { id: 'c11-haru-arrive', mode: 'training', narration: true, text: '그때 훈련소 입구에서 빛이 짧게 번쩍였다. 날아든 화살이 주인공의 검끝 바로 앞 바닥에 꽂혔다.' },
    { id: 'c11-haru-warning', mode: 'training', speaker: '하루', text: '그 상태로 더 하면 자세만 망가져요.' },
    { id: 'c11-mc-surprise', mode: 'training', speaker: '주인공', text: '하루 씨? 여긴 어쩐 일입니까?' },
    { id: 'c11-haru-look', mode: 'training', narration: true, text: '하루는 대답하지 않고 바닥에 떨어진 천 조각과 여러 번 덧감긴 손을 차례로 보았다.' },
    { id: 'c11-haru-answer', mode: 'training', speaker: '하루', text: '찾으러 왔습니다. 며칠째 숙소에도 제대로 안 들어온다고 들었어요.' },
    { id: 'c11-momo-peek', mode: 'training', narration: true, text: '하루의 뒤에서 모모가 조심스럽게 얼굴을 내밀었다. 양손에는 작은 물병과 수건이 들려 있었다.' },
    { id: 'c11-momo-line', mode: 'training', speaker: '모모', text: '저, 정말 여기 계셨네요. 혹시 오늘도 아무것도 안 드셨어요?' },
    { id: 'c11-mc-deny', mode: 'training', speaker: '주인공', text: '아침에는 먹었습니다.' },
    { id: 'c11-sena-enter', mode: 'training', speaker: '세나', text: '그 아침이 어제 아침은 아니죠?' },
    { id: 'c11-sena-arrive', mode: 'training', narration: true, text: '세나가 뒤늦게 들어오며 한숨을 쉬었다. 평소처럼 부드러운 표정이었지만 시선은 주인공의 옆구리에 머물러 있었다.' },
    { id: 'c11-mc-explain', mode: 'training', speaker: '주인공', text: '몸은 괜찮습니다. 훈련을 쉬면 오히려 감각이 떨어질 것 같아서요.' },
    { id: 'c11-sena-close', mode: 'training', narration: true, text: '세나는 주인공 앞까지 다가와 손을 내밀었다.' },
    { id: 'c11-sena-command', mode: 'training', speaker: '세나', text: '검부터 거둬요.' },
    { id: 'c11-mc-hesitate', mode: 'training', narration: true, text: '주인공이 잠시 망설이자 하루가 바닥에 꽂힌 화살을 없앴다.' },
    { id: 'c11-haru-support', mode: 'training', speaker: '하루', text: '오늘은 세나 씨 말이 맞아요. 아니, 오늘만은 아니겠네요.' },
    { id: 'c11-momo-small', mode: 'training', speaker: '모모', text: '저도 그렇게 생각해요. 아주 조금이지만요.' },
    { id: 'c11-mc-look', mode: 'training', narration: true, text: '세 사람이 한쪽에 나란히 서 있었다. 누구도 먼저 돌아갈 생각은 없어 보였다.' },
    { id: 'c11-choice', mode: 'training', speaker: '주인공', text: '더 버티는 것은 어려울 것 같았다.', choices: [
      { id: 'c11-give-up', label: '순순히 검을 거둔다.', reply: '알겠습니다. 오늘은 여기까지 하겠습니다.', affection: { haru: 1, sena: 1, momo: 1 }, trust: { haru: 1, sena: 1, momo: 1 } },
      { id: 'c11-one-more', label: '마지막 한 번만 부탁한다.', reply: '마지막 한 번만 하고 끝내면 안 되겠습니까?', affection: { haru: 1, sena: 1 }, traits: { stubborn: 1 } },
      { id: 'c11-why-together', label: '세 사람이 함께 온 이유를 묻는다.', reply: '그런데 세 분이 다 같이 오신 겁니까?', affection: { momo: 1 }, trust: { haru: 1, sena: 1, momo: 1 } }
    ] },
    { id: 'c11-sena-response', mode: 'training', speaker: '세나', text: '협상은 없어요. 오늘은 쉬는 날이에요.' },
    { id: 'c11-mc-rest-question', mode: 'training', speaker: '주인공', text: '제가 정한 적은 없는 것 같습니다만.' },
    { id: 'c11-haru-decide', mode: 'training', speaker: '하루', text: '그래서 저희가 정했습니다.' },
    { id: 'c11-momo-nod', mode: 'training', narration: true, text: '모모는 자신이 한 말도 아닌데 빠르게 고개를 끄덕였다.' },
    { id: 'c11-sena-check-hand', mode: 'training', narration: true, text: '세나는 검이 사라진 것을 확인한 뒤 주인공의 손목을 잡았다. 맥을 짚고 손바닥의 상처까지 살핀 다음에야 표정이 조금 풀렸다.' },
    { id: 'c11-sena-state', mode: 'training', speaker: '세나', text: '열은 없네요. 그래도 이 손으로는 오늘 더 못 해요.' },
    { id: 'c11-water', mode: 'training', narration: true, text: '모모가 기다렸다는 듯 물병을 내밀었다. 주인공이 받아 들자 굳어 있던 어깨가 아주 조금 내려갔다.' },
    { id: 'c11-momo-water', mode: 'training', speaker: '모모', text: '미지근한 물이에요. 너무 차가우면 안 좋다고 세나 씨가 말씀하셔서요.' },
    { id: 'c11-thanks', mode: 'training', speaker: '주인공', text: '감사합니다.' },
    { id: 'c11-exit-training', mode: 'city', narration: true, text: '네 사람은 함께 훈련소를 나왔다. 늘 혼자 걷던 길이었지만 오늘은 발걸음이 자연스럽게 느려졌다.' },
    { id: 'c11-evening-city', mode: 'city', narration: true, text: '저녁을 앞둔 중앙도시는 아직 붐볐다. 상점들이 하나둘 등불을 밝히고 거리에는 일을 마친 사람들이 늘어나고 있었다.' },
    { id: 'c11-mc-where', mode: 'city', speaker: '주인공', text: '이제 숙소로 돌아가면 됩니까?' },
    { id: 'c11-haru-no', mode: 'city', speaker: '하루', text: '아니요. 숙소로 보내면 다시 몰래 훈련하러 나올 것 같아서요.' },
    { id: 'c11-mc-deny2', mode: 'city', speaker: '주인공', text: '그 정도까지 하지는 않습니다.' },
    { id: 'c11-three-look', mode: 'city', narration: true, text: '세 사람의 시선이 동시에 주인공에게 모였다.' },
    { id: 'c11-mc-correct', mode: 'city', speaker: '주인공', text: '……아마도요.' },
    { id: 'c11-momo-smile', mode: 'city', narration: true, text: '모모가 입을 가리고 작게 웃었다. 하루도 시선을 돌렸지만 입가가 조금 풀려 있었다.' },
    { id: 'c11-sena-plan', mode: 'city', speaker: '세나', text: '내일 하루 비워 둬요. 중앙도시를 천천히 돌아볼 거예요.' },
    { id: 'c11-mc-city', mode: 'city', speaker: '주인공', text: '중앙도시는 이미 여러 번 다녀봤습니다.' },
    { id: 'c11-haru-point', mode: 'city', speaker: '하루', text: '길드와 훈련소 사이만 오간 걸 돌아봤다고 하지는 않아요.' },
    { id: 'c11-momo-market', mode: 'city', speaker: '모모', text: '시장도 있고, 장비점도 있고…… 음식 파는 곳도 많아요. 사람이 많기는 하지만요.' },
    { id: 'c11-sena-final', mode: 'city', speaker: '세나', text: '정해졌네요. 내일 아침, 길드 앞에서 만나요.' },
    { id: 'c11-mc-accept', mode: 'city', narration: true, text: '주인공은 세 사람을 번갈아 보았다. 거절할 이유를 찾으려 했지만, 이상하게도 더는 떠오르지 않았다.' },
    { id: 'c11-mc-answer', mode: 'city', speaker: '주인공', text: '알겠습니다. 내일 뵙겠습니다.' },
    { id: 'c11-separate', mode: 'city', narration: true, text: '갈림길에서 네 사람은 각자의 숙소로 흩어졌다. 주인공은 몇 걸음 뒤 돌아보았고, 모모가 아직 손을 흔들고 있는 것을 발견했다.' },
    { id: 'c11-night', mode: 'black', narration: true, text: '그날 밤, 주인공은 오랜만에 훈련 계획을 세우지 않고 잠자리에 들었다.' },
    { id: 'c11-clear', mode: 'black', center: 'CHAPTER 11 CLEAR' },
    { id: 'c11-end', mode: 'black', ending: true, center: '네 사람이 처음으로 함께 시간을 보내기로 했다.' }
  ]
};