export const chapter013 = {
  id: 13,
  title: '아물지 않는 상처',
  scenes: [
    { id: 'c13-title', mode: 'black', center: 'CHAPTER 13\n\n아물지 않는 상처' },
    { id: 'c13-next-morning', mode: 'room', narration: true, text: '다음 날 아침, 주인공은 옆구리의 통증 때문에 평소보다 일찍 눈을 떴다.' },
    { id: 'c13-check-alone', mode: 'room', narration: true, text: '겉으로 보기에는 피도 멎었고 붓기도 줄어 있었다. 하지만 몸을 일으킬 때마다 상처 안쪽이 뒤늦게 찢어지는 듯 당겼다.' },
    { id: 'c13-knock', mode: 'room', narration: true, text: '문을 두드리는 소리가 났다. 대답하자 세나가 치료 도구가 든 가방을 들고 들어왔다.' },
    { id: 'c13-sena-greet', mode: 'room', speaker: '세나', text: '좋은 아침이에요. 어제 많이 걸었으니 상처를 다시 봐야 해요.' },
    { id: 'c13-mc-fine', mode: 'room', speaker: '주인공', text: '조금 당기는 것 외에는 괜찮습니다.' },
    { id: 'c13-sena-sit', mode: 'room', speaker: '세나', text: '괜찮은지는 제가 보고 판단할게요. 여기 앉아요.' },
    { id: 'c13-bandage-open', mode: 'room', narration: true, text: '세나는 낡은 붕대를 천천히 풀었다. 마지막 천이 떨어지자 손을 멈췄다.' },
    { id: 'c13-sena-silence', mode: 'room', narration: true, text: '평소라면 바로 상태를 설명했을 세나가 아무 말도 하지 않았다.' },
    { id: 'c13-mc-question', mode: 'room', speaker: '주인공', text: '문제가 있습니까?' },
    { id: 'c13-sena-look-close', mode: 'room', narration: true, text: '세나는 상처 가까이 몸을 숙였다. 손끝으로 주변 피부를 조심스럽게 눌러 보고, 다시 정신 에너지를 흘려보냈다.' },
    { id: 'c13-no-response', mode: 'room', narration: true, text: '희미한 빛이 상처를 감쌌지만 아무 변화도 일어나지 않았다.' },
    { id: 'c13-sena-line', mode: 'room', speaker: '세나', text: '이상해요.' },
    { id: 'c13-mc-what', mode: 'room', speaker: '주인공', text: '어떤 점이 말입니까?' },
    { id: 'c13-sena-explain', mode: 'room', speaker: '세나', text: '출혈은 멎었는데 상처가 붙지 않았어요. 처음 동굴에서 봤을 때와 거의 같은 깊이예요.' },
    { id: 'c13-mc-days', mode: 'room', speaker: '주인공', text: '며칠이나 지났는데도요?' },
    { id: 'c13-sena-nod', mode: 'room', narration: true, text: '세나는 대답 대신 천천히 고개를 끄덕였다.' },
    { id: 'c13-sena-normal', mode: 'room', speaker: '세나', text: '정신세계의 몸은 정신 에너지가 안정되면 상처도 같이 회복돼요. 느린 경우는 있어도 전혀 아물지 않는 경우는 본 적이 없어요.' },
    { id: 'c13-mc-body', mode: 'room', speaker: '주인공', text: '제가 기억을 잃은 것과 관련이 있을까요?' },
    { id: 'c13-sena-uncertain', mode: 'room', speaker: '세나', text: '모르겠어요. 지금은 함부로 이유를 정하면 안 돼요.' },
    { id: 'c13-door-open', mode: 'room', narration: true, text: '그때 문밖에서 발소리가 멈췄다. 잠시 뒤 하루와 모모가 열린 문 사이로 모습을 보였다.' },
    { id: 'c13-haru-enter', mode: 'room', speaker: '하루', text: '세나 씨가 오래 안 나오셔서 와 봤습니다. 무슨 일인가요?' },
    { id: 'c13-momo-worry', mode: 'room', speaker: '모모', text: '혹시 어제 너무 많이 걸어서 더 나빠진 건가요?' },
    { id: 'c13-sena-call-in', mode: 'room', speaker: '세나', text: '두 사람도 들어와요. 직접 보는 편이 좋겠어요.' },
    { id: 'c13-haru-see', mode: 'room', narration: true, text: '하루는 침상 가까이 다가와 드러난 상처를 보았다. 모모는 처음에는 시선을 피했지만 이내 조심스럽게 옆으로 다가왔다.' },
    { id: 'c13-haru-question', mode: 'room', speaker: '하루', text: '아직도 이 상태라고요?' },
    { id: 'c13-sena-confirm', mode: 'room', speaker: '세나', text: '네. 표면도 거의 붙지 않았어요. 치료 에너지도 안쪽으로 들어가지 않고 겉에서 흩어져요.' },
    { id: 'c13-momo-ask', mode: 'room', speaker: '모모', text: '악몽한테 입은 상처라서 그런 건 아닐까요?' },
    { id: 'c13-haru-deny', mode: 'room', speaker: '하루', text: '악몽에게 다친 사람은 많이 봤어요. 심한 오염이라면 상처 주변부터 검게 변해야 합니다.' },
    { id: 'c13-sena-add', mode: 'room', speaker: '세나', text: '그런 반응도 없어요. 정신 에너지는 정상이고, 열도 내렸고, 감각도 있어요. 상처만 따로 멈춰 있는 것 같아요.' },
    { id: 'c13-momo-fear', mode: 'room', narration: true, text: '모모는 무언가를 묻고 싶어 했지만 쉽게 입을 열지 못했다. 대신 주인공의 얼굴을 살피며 가방 끈을 만지작거렸다.' },
    { id: 'c13-mc-calm', mode: 'room', speaker: '주인공', text: '당장 위험한 상태는 아니지 않습니까?' },
    { id: 'c13-sena-firm', mode: 'room', speaker: '세나', text: '지금 당장은요. 하지만 이유를 모르는 상태로 두는 건 위험해요.' },
    { id: 'c13-haru-decide', mode: 'room', speaker: '하루', text: '길드장에게 보고하죠. 길드 기록에 비슷한 사례가 있을 수도 있습니다.' },
    { id: 'c13-mc-hesitate', mode: 'room', narration: true, text: '주인공은 다시 감길 붕대를 내려다보았다. 실패한 의뢰가 끝난 지 얼마 되지도 않았는데 또 문제를 만들고 싶지는 않았다.' },
    { id: 'c13-choice', mode: 'room', speaker: '주인공', text: '세 사람은 대답을 기다리고 있었다.', choices: [
      { id: 'c13-report-now', label: '바로 길드장에게 보고한다.', reply: '알겠습니다. 지금 바로 보고하겠습니다.', trust: { haru: 1, sena: 2, momo: 1 }, traits: { cautious: 1 } },
      { id: 'c13-ask-sena', label: '세나의 판단을 따른다.', reply: '세나 씨가 필요하다고 판단하셨다면 따르겠습니다.', affection: { sena: 1 }, trust: { sena: 2 } },
      { id: 'c13-reassure-team', label: '걱정하는 세 사람을 안심시킨다.', reply: '보고하겠습니다. 그러니 너무 걱정하지 않으셔도 됩니다.', affection: { haru: 1, sena: 1, momo: 2 }, traits: { considerate: 1 } }
    ] },
    { id: 'c13-bandage-new', mode: 'room', narration: true, text: '세나는 새 천으로 상처를 다시 감았다. 평소보다 손길이 느렸고, 매듭을 묶은 뒤에도 한 번 더 상태를 확인했다.' },
    { id: 'c13-momo-help', mode: 'room', speaker: '모모', text: '제가 가방 들게요. 천천히 걸어가요.' },
    { id: 'c13-mc-thanks', mode: 'room', speaker: '주인공', text: '걸을 수 있습니다. 그래도 감사합니다.' },
    { id: 'c13-leave-room', mode: 'city', narration: true, text: '네 사람은 함께 숙소를 나섰다. 어제 같은 길을 걸었지만 분위기는 전혀 달랐다.' },
    { id: 'c13-city-normal', mode: 'city', narration: true, text: '거리의 상점은 평소처럼 문을 열고 사람들이 오갔다. 주인공은 그 익숙한 풍경 속에서 자신만 다른 곳에 놓인 듯한 기분을 느꼈다.' },
    { id: 'c13-haru-slow', mode: 'city', narration: true, text: '하루는 평소보다 반 걸음 앞에서 걸으며 길을 비켜 주었고, 세나는 주인공의 호흡이 달라질 때마다 속도를 늦췄다. 모모는 말없이 가장 가까운 쪽을 지켰다.' },
    { id: 'c13-mc-notice', mode: 'city', speaker: '주인공', text: '세 분 모두 그렇게 조심하지 않으셔도 됩니다.' },
    { id: 'c13-haru-answer', mode: 'city', speaker: '하루', text: '조심해서 나쁠 건 없어요.' },
    { id: 'c13-sena-answer2', mode: 'city', speaker: '세나', text: '오늘만큼은 환자답게 걸어요.' },
    { id: 'c13-momo-answer', mode: 'city', speaker: '모모', text: '저는 원래 천천히 걷는 편이라 괜찮아요.' },
    { id: 'c13-guild-arrive', mode: 'guild', narration: true, text: '길드에 도착하자 안내원이 네 사람의 표정을 확인하고 곧바로 다가왔다.' },
    { id: 'c13-reception', mode: 'guild', speaker: '안내원', text: '무슨 일이 있으신가요?' },
    { id: 'c13-sena-report', mode: 'guild', speaker: '세나', text: '{{playerName}} 씨의 상처에 미확인 반응이 있어요. 길드장에게 바로 보고해야 합니다.' },
    { id: 'c13-reception-serious', mode: 'guild', narration: true, text: '안내원의 표정이 굳었다. 그녀는 다른 질문을 하지 않고 길드장실로 향했다.' },
    { id: 'c13-wait', mode: 'guild', narration: true, text: '네 사람은 홀 한쪽에서 기다렸다. 모모는 의자에 앉지 못하고 서성였고, 하루는 닫힌 길드장실 문을 바라보았다.' },
    { id: 'c13-call', mode: 'guild', narration: true, text: '잠시 뒤 안내원이 돌아와 문을 열어 주었다.' },
    { id: 'c13-reception-call', mode: 'guild', speaker: '안내원', text: '길드장님이 네 분 모두 들어오라고 하십니다.' },
    { id: 'c13-enter-office', mode: 'guildmaster', narration: true, text: '주인공이 먼저 문을 넘고, 하루와 세나, 모모가 뒤따랐다. 책상 위에는 이미 지난 의뢰의 보고서가 펼쳐져 있었다.' },
    { id: 'c13-guildmaster-look', mode: 'guildmaster', speaker: '길드장', text: '상처가 아물지 않는다고 들었다. 처음부터 차례대로 설명해라.' },
    { id: 'c13-final', mode: 'guildmaster', narration: true, text: '세나가 동굴에서의 치료부터 현재 상태까지 설명하기 시작했다. 길드장은 한 번도 말을 끊지 않았고, 보고가 끝난 뒤에도 한동안 상처와 기록을 번갈아 보았다.' },
    { id: 'c13-clear', mode: 'black', center: 'CHAPTER 13 CLEAR' },
    { id: 'c13-end', mode: 'black', ending: true, center: '길드에 존재하지 않던 현상이 처음 보고되었다.' }
  ]
};