export type SceneKind='black'|'forest'|'battle'|'status'|'city'|'lobby'|'guild';
export type Scene={
  kind:SceneKind;
  speaker?:string;
  text:string;
  choices?:string[];
  action?:'guild';
};

export const scenes:Scene[]=[
  {kind:'black',text:'……여기는 어디지?'},
  {kind:'black',text:'아니.\n그보다 먼저—'},
  {kind:'black',text:'나는 누구지?'},
  {kind:'forest',text:'눈을 뜨자, 푸른빛이 나뭇잎 사이로 흘러내렸다.\n흙과 바람, 젖은 나무 냄새까지 지나치게 선명했다.'},
  {kind:'forest',text:'기억은 비어 있었다.\n그런데 몸은 이곳을 알고 있는 듯 자연스럽게 일어섰다.'},
  {kind:'forest',text:'같은 나무를 두 번 지나친 것 같았다.\n처음부터 길 같은 건 없었던 걸까.'},
  {kind:'battle',text:'나뭇가지가 부러졌다.\n검은 형체가 안개 사이에서 몸을 일으켰다.'},
  {kind:'battle',text:'손을 뻗는 순간, 푸른 입자가 모여 검의 형태를 이루었다.\n생각할 틈도 없이 몸이 먼저 움직였다.'},
  {kind:'status',text:'LEVEL UP\nLv. 1 → Lv. 2\n정신 에너지 운용 상승\n신체 반응 상승\n새로운 구현 가능성 감지\n\n전리품: 악몽의 정수 × 1'},
  {kind:'forest',text:'악몽은 검은 안개처럼 흩어졌다.\n그 자리에 푸른빛이 섞인 작은 결정 하나가 남았다.'},
  {kind:'forest',text:'승리의 감각은 짧았다.\n더 짙고 거대한 그림자가 숲을 찢으며 나타났다.'},
  {kind:'battle',text:'검이 튕겨 나갔다.\n차가운 발톱이 눈앞까지 다가온 순간— 푸른 섬광이 어둠을 갈랐다.'},
  {kind:'forest',speaker:'하루',text:'움직일 수 있어요?'},
  {kind:'forest',speaker:'하루',text:'……다친 곳은요?'},
  {kind:'forest',text:'내민 손을 잡고 일어서는 순간 다리에 힘이 풀렸다.\n그녀가 반사적으로 나를 받아냈다. 머리카락이 뺨을 스치고 숨결이 가까워졌다.'},
  {kind:'forest',speaker:'하루',text:'……괜찮아 보이진 않네요.'},
  {kind:'forest',speaker:'하루',text:'혼자예요?',choices:['아마도.','기억이 없어.','당신은 누구지?']},
  {kind:'forest',speaker:'하루',text:'그럼 여기 혼자 있으면 안 돼요.\n중앙도시까지 같이 가요.'},
  {kind:'black',text:'아무것도 기억하지 못한다.\n그런데 이상하게도, 그녀의 뒤를 따라가는 일만은 낯설지 않았다.'},
  {kind:'city',text:'숲의 끝에서 빛이 터졌다.\n안개 너머, 처음 보는 중앙도시가 오래전부터 나를 기다린 듯 서 있었다.'},
  {kind:'city',speaker:'하루',text:'왜 그래요? 가요.\n혼자 두진 않을 테니까.'},
  {kind:'lobby',text:'중앙도시 메인 로비가 해금되었습니다.\n튜토리얼 완료.'},

  {kind:'black',text:'CHAPTER 2\n\n기록되지 않은 사람'},
  {kind:'lobby',speaker:'하루',text:'우선 길드로 가보자.\n네가 이곳 사람이라면 뭔가 기록이 남아 있을지도 몰라.\n나도 임무 완료 보고를 해야 하니까, 어차피 가야 하거든.',action:'guild'},

  {kind:'city',text:'길드 타일을 선택하자 화면이 천천히 어두워졌다.\n\n잠시 후, 밝은 햇빛과 함께 도시의 풍경이 시야를 가득 채웠다.'},
  {kind:'city',text:'넓은 거리를 따라 사람들이 끊임없이 오갔다.\n높고 낮은 건물들이 길 양옆으로 빼곡하게 이어져 있었다.'},
  {kind:'city',text:'가게 앞에서 물건을 고르는 사람.\n길가에 앉아 이야기를 나누는 사람.\n무언가를 먹으며 웃고 떠드는 사람들까지.\n\n처음 보는 도시였지만, 이상하리만큼 평범한 풍경이었다.'},
  {kind:'city',text:'하지만 조금만 자세히 바라보자 한 가지 이상한 점이 눈에 들어왔다.\n\n무기를 든 사람이 많았다.'},
  {kind:'city',text:'허리에 검을 찬 남자.\n등에 거대한 창을 멘 여자.\n처음 보는 형태의 무기를 손질하며 길가에 앉아 있는 사람들까지.'},
  {kind:'city',text:'그리고 그들 대부분은 혼자가 아니었다.\n두 명, 세 명, 때로는 네 명씩 무리를 지어 같은 방향으로 향하고 있었다.'},
  {kind:'city',speaker:'주인공',text:'저 사람들은……?'},
  {kind:'city',speaker:'하루',text:'아, 임무 나가는 사람들이야.'},
  {kind:'city',speaker:'주인공',text:'임무?'},
  {kind:'city',text:'하루가 잠시 나를 바라봤다.\n\n그제야 다시 실감했다.\n나는 정말 아무것도 모른다.\n내 이름을 제외하면.'},
  {kind:'city',text:'내가 누구인지.\n어디서 왔는지.\n심지어 이곳이 어떤 세계인지조차.'},
  {kind:'city',speaker:'하루',text:'일단 길드부터 가자.\n네 기록이 남아 있다면 거기서 찾을 수 있을 거야.'},
  {kind:'city',text:'도시의 중심으로 가까워질수록 사람들의 수가 많아졌다.'},
  {kind:'city',text:'거대한 무기를 짊어진 이들.\n온몸에 상처를 입은 채 동료의 부축을 받으며 돌아오는 이들.'},
  {kind:'city',text:'서로 웃으며 이야기하는 사람들 사이로, 누군가의 이름이 적힌 작은 꽃다발을 들고 조용히 걷는 사람도 보였다.'},
  {kind:'city',text:'나는 그 모습을 잠시 바라봤다.\n하루는 아무 말도 하지 않았다.'},
  {kind:'city',text:'얼마 지나지 않아 우리는 거대한 건물 앞에 도착했다.\n수많은 사람이 끊임없이 드나드는 곳.\n\n건물 정면에는 단 하나의 글자가 크게 새겨져 있었다.\n\nGUILD'},
  {kind:'city',speaker:'하루',text:'여기가 길드야.'},
  {kind:'guild',text:'문이 열렸다.\n순간, 도시의 소음과는 전혀 다른 활기가 밀려왔다.'},
  {kind:'guild',text:'넓은 홀.\n벽을 가득 채운 수많은 임무 게시판.\n접수대 앞에 줄을 선 사람들.'},
  {kind:'guild',text:'테이블 위에 지도를 펼쳐놓고 작전을 논의하는 파티.\n새로운 동료를 찾으며 서로의 장비와 등급을 확인하는 사람들.'},
  {kind:'guild',text:'임무를 마치고 돌아온 이들은 접수대에 증표와 보고서를 제출하고 있었다.'},
  {kind:'guild',text:'이 건물은 단순히 사람들이 모이는 장소가 아니었다.\n이 도시의 모든 것이 이곳을 중심으로 움직이고 있었다.'},
  {kind:'guild',speaker:'하루',text:'뭐 해?\n이쪽이야.'},
  {kind:'guild',text:'나는 다시 하루를 따라 걸었다.\n내가 누구인지 알고 싶다면—\n아마 이곳에서부터 시작해야 한다.'},

  {kind:'guild',text:'하루를 따라 접수대로 향했다.\n여러 명의 직원이 쉴 새 없이 사람들을 응대하고 있었다.'},
  {kind:'guild',text:'임무서를 제출하는 사람.\n새로운 의뢰를 확인하는 사람.\n동료의 이름을 대며 무언가를 묻는 사람까지.'},
  {kind:'guild',speaker:'안내원',text:'하루 님?'},
  {kind:'guild',speaker:'하루',text:'아, 안녕하세요.'},
  {kind:'guild',speaker:'안내원',text:'무사히 돌아오셨네요. 임무는요?'},
  {kind:'guild',speaker:'하루',text:'끝났어요. 완료 보고하러 왔어요.'},
  {kind:'guild',text:'하루는 품에서 작은 패를 꺼내 건넸다.\n안내원이 그것을 접수대 위 장치에 올려놓자 희미한 빛이 퍼졌다.'},
  {kind:'status',text:'임무 완료 확인\n\n악몽 토벌 완료'},
  {kind:'guild',text:'악몽.\n분명 처음 듣는 말이어야 했다.\n그런데 그 단어를 보는 순간 머릿속 어딘가가 희미하게 흔들렸다.'},
  {kind:'guild',text:'잡힐 듯하면서도 잡히지 않는 감각.\n나는 무심코 미간을 찌푸렸다.'},
  {kind:'guild',speaker:'안내원',text:'그런데…… 이분은?'},
  {kind:'guild',speaker:'하루',text:'저도 잘 몰라요.\n임무에서 돌아오는 길에 만났어요.\n이름 말고는 아무것도 기억하지 못해요.'},
  {kind:'guild',speaker:'안내원',text:'기억상실인가요?'},
  {kind:'guild',speaker:'주인공',text:'아마도요.'},
  {kind:'guild',speaker:'안내원',text:'이름은 기억하시고요?'},
  {kind:'guild',text:'나는 내 이름을 말했다.\n안내원은 곧바로 앞에 놓인 장치를 조작하기 시작했다.'},
  {kind:'guild',speaker:'안내원',text:'잠시만 기다려주세요.'},
  {kind:'guild',text:'화면 위로 수많은 정보가 빠르게 지나갔다.\n그리고 잠시 후, 안내원의 손이 멈췄다.'},
  {kind:'guild',speaker:'안내원',text:'……어라?'},
  {kind:'guild',speaker:'하루',text:'왜요?'},
  {kind:'status',text:'검색 결과 없음'},
  {kind:'guild',speaker:'주인공',text:'없는 건가요?'},
  {kind:'guild',speaker:'안내원',text:'네. 적어도 길드 기록에는요.'},
  {kind:'guild',speaker:'하루',text:'그럴 수도 있어요?'},
  {kind:'guild',speaker:'안내원',text:'이름을 바꿨거나 등록 정보에 오류가 생겼을 가능성은 있어요. 하지만……\n\n정말 아무것도 기억나지 않으세요?'},
  {kind:'guild',speaker:'주인공',text:'네.'},
  {kind:'guild',speaker:'안내원',text:'그럼 지금 머물 곳은 있으세요?'},
  {kind:'guild',speaker:'안내원',text:'돈은요?'},
  {kind:'guild',speaker:'안내원',text:'소지품이나 신분을 증명할 만한 것은요?'},
  {kind:'guild',text:'나는 천천히 고개를 저었다.\n안내원은 난처한 표정으로 하루를 바라봤다.\n하루도 나를 바라봤다.'},
  {kind:'black',text:'나는 기억만 없는 게 아니었다.\n\n집도 없다.\n돈도 없다.\n신분도 없다.\n\n말 그대로—\n\n아무것도 없었다.'}
];